### ISSUE TITLE
Shell Issues: Arc titles, Arc reopening, Friends, Boxing

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1002]
Filing an issue to track items I'm experiencing this morning. Am only describing symptoms, possible there are a smaller set of underlying causes vs. the number of issues noted. Repro steps:

- check out ToT, build things
- delete all of your Arcs via Firebase Console
- create new Arc to set your avatar and connect friends. Do both of those things. Mark the arc as shared to friends.
- create new Arc to play Words. Make one move. Mark the arc as shared to friends.
- return to Launcher home and note:
  - none of the Arcs have plan-specific titles
  - it appears that I have no friends (`BOXED_avatar` is empty), though I chose some
  - the shared Words arc should have produced `BOXED_stats` (as well as `BOXED_board` and `BOXED_move`) but none are in the context per Handle Explorer
  - attempting to reopen an Arc from the launcher produces an empty Arc content region

@sjmiles @mmandlis

**Comment by sjmiles** [comment]
re: `delete all your Arcs via Firebase Console`

For completeness, you should also delete the `[user]/profile` and `[user]/arcs` nodes, these are where sharing flags and steps are stored.

**Comment by sjmiles** [comment]
Believe these to be fixed.
