### ISSUE TITLE
Need a way to disambiguate overloaded event handlers

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/arcs#1022]
In https://github.com/PolymerLabs/arcs/pull/1007 I needed to thread the `subId` to disambiguate from which slot an event was generated. A similar situation might occur with other kinds of repeated templates. I wonder if a better solution here might be a way to thread back some state from the model.

Something like:
```
<hex-cell player$="{{player}}" on-click="onCellClick" on-click-state="{{cellId}}">
```

**Comment by sjmiles** [comment]
Explicitly, 'key' and 'value' properties are passed along to the event handler, so if you do:

```
<hex-cell player$="{{player}}" on-click="onCellClick" key="{{cellId}}">
```

Then in `onCellClick(e)`, `e.data.key` will be `cellId`.
