### ISSUE TITLE
Accursed footer element is intrusive in a ghostly manner.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1049]
The invisible but not hidden `footer` element seems oddly positioned and overlaps the `textarea` used for Social post input, thus leading to a dead spot for clicking and cursors.

Filing issue as a reminder. Whoever gets to it first.

**Comment by sjmiles** [comment]
The `footer` is a spacer element that lives in the static flow and should always be positioned right below whatever content is in the `root` slot. This is done so the scrolling region is always larger by one-footer-height, which ensures no content is ever obscured behind the actual arc-footer.

It's not clear why footer is considered _above_ other content such that it is interfering with the `modal` slot.

I want to figure out the above, but I believe the short-term fix is probably to put `pointer-events: none` style on `footer` so it's inactive.
