### ISSUE TITLE
Restaurant demo replay appears broken.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1116]
To repro:

- Find restaurants, watch logging for `PersistentArc`, note when we write a step.
- Choose 'Make a reservation', watch logging again, note that when we write the second step (rev 2) we still have an array of Steps of size 1. It appears that we lose the first step, and it's overwritten with the second step.

**Comment by sjmiles** [comment]
This problem is in 
```
 async _consumePlan(arc, description, metadata) {
    // arc has changed, generate new description
    description = await ArcsUtils.describeArc(arc) || description;
```

`describeArc` goes async, but the method has captured a value for `metadata`, which causes an error.

**Comment by sjmiles** [comment]
Thanks for the repro btw.

**Comment by sjmiles** [comment]
Believe this is fixed.
