### ISSUE TITLE
Something is interacting badly between arc sessions and recipe replay

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1117]
Arcs have a session ID that is used to ensure that handle & slot ID generation doesn't clash across a serialization/deserialization boundary. Currently, the session ID is *randomly generated*.

This means that when the same recipe is replayed twice, the resulting arcs have different IDs.

While we don't understand the mechanism completely, it seems this is interacting badly with some part of recipe replay when reloading an arc. Effectively, reloading an arc works when there's a single recipe stored in the replay list, but when there are 2 then a second copy of the first recipe (with different IDs) is inserted.

**Comment by sjmiles** [comment]
Is this distinct from the problem fixed in #1120?

**Comment by shans** [comment]
Nope, same problem.
