### ISSUE TITLE
Implement the simplified tag naming syntax we discussed at an offsite

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/arcs#1149]
Basically, we treat the first tag as the name if a name is not specified:
 * `in Foo #foo` is equivalent to `in Foo foo #foo`
 * `in Foo #foo #bar` is equivalent to `in Foo foo #foo #bar`

The same should work for other uses of tags, eg. slots.

/cc @mmandlis @shans

**Comment by shaper** [comment]
Note that this applies to `&verbs` as well.

**Comment by lindner** [comment]
I'll work on this.

**Comment by lindner** [comment]
It appears that this logic is implemented in runtime/manifest-parser.peg

For people new to this environment these are implemented with https://pegjs.org/

**Comment by shaper** [comment]
@shans to comment on above but the proposal sounds roughly right to me.

Yes, if there's no name and no tag that seems like it should be a syntax error though I suppose we could auto-camel or auto-hacker-case the type name if present (it could also be an inline schema definition or shape like [~a] I think) as a fallback, but AFAIK that hasn't been discussed.

**Comment by lindner** [comment]
Added tags to arguments and implemented the name logic described.  If this is the right approach I can apply it towards more parts of the grammar.

**Comment by cromwellian** [comment]
@lindner Is this closeable now?

**Comment by Cypher1** [comment]
Will close this for the good of the issue tracker, feel free to re-open if there are problems.
