### ISSUE TITLE
`StorageStub`s never converted to real storage

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1159]
Certain handles are parsed by the manifest parser into StorageStubs here:
https://github.com/PolymerLabs/arcs/blob/master/runtime/manifest.js#L867

These stubs are never converted to real Storage objects, causing numerous downstream failures.

Storage Pinocchio wants to be a real boy!

This issue is currently blocking shell-prototype usage of runtime arc serialization.

**Comment by shans** [comment]
fixed in #1259 , but will merge separately

**Comment by sjmiles** [comment]
We merged this code in eventually.
