### ISSUE TITLE
Social EditPost content fails to render into DetailSlider.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1160]
https://github.com/PolymerLabs/arcs/pull/1154 seems to have broken post creation somehow, to repro:

- create a new arc for 'Write posts...'
- click the '+' button bottom right to open detail slider
- note JS console errors and the absence of a TextArea filling the DetailSlider where one should be able to enter text.

The assert at `dom-context.js` line 143 fails, but then the error message itself fails because `slotSpec` is not defined. This looks like an oversight in the error message string creation. But, assert wise, both `this.subId` and `subId` are null, and `providedSlotSpec.isSet` is false.

The call stack is from `_initInnerSlotContext` line 129.

```
dom-slot.js:84 Uncaught (in promise) ReferenceError: slotSpec is not defined
    at DomContext._validateSubId (dom-context.js:144)
    at DomContext._initInnerSlotContext (dom-context.js:129)
    at Array.from.forEach.elem (dom-context.js:124)
    at Array.forEach (<anonymous>)
    at DomContext.initInnerContexts (dom-context.js:113)
    at MutationObserver (dom-slot.js:81)
```

**Comment by mmandlis** [comment]
yes, I'll send a fix shortly. Sorry about that.

**Comment by shaper** [comment]
No problem! We need a Selenium test for Social post creation...

**Comment by mmandlis** [comment]
Actually, it has broken pretty much everything :( but selenium tests were already flaky, so I carelessly ignored it :(

**Comment by mmandlis** [comment]
I believe this should be fixed now, closing. Please, reopen, if you're still experiencing problems.
