### ISSUE TITLE
Muxing items with embedded recipes should be able to map handles from context.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1192]
We're now aiming for the Social app to use recipes embedded in `Post` entities to render each post. As part of this we agreed that it can make sense for the recipe to be able to map in handles accessible to the arc's context, vs. just those in the arc.

This is beneficial as it means the recipe containing `PostMuxer` needn't explicitly map in handles on behalf of the item-embedded recipes with particles (of unknown implementation and so handle data needs in the future) that may want to render an item.

Initial exploration with recipe detailed below fails with 'BOXED_avatar' handle not available. I think this is due to the logic in `multiplexer-dom-particle.js` for `_mapParticleConnections` taking a list of handles, and those are only the handles in the arc (`this._views`). Whereas, in `outer-PEC.js` `onArcLoadRecipe` we retrieve handles via `Arc.findHandleById` which will in turn fall back to `_context.findStorageById`.

I believe we may need to also grab that `_context` list of handles and include them in the views we proxy, rename, and update as `otherConnections` in `multiplexer-dom-particle.js`.

Sample recipe pre-interpolation by `PostMuxer.js`:

```
particle ShowSinglePost in 'https://$cdn/artifacts/Social/source/ShowSinglePost.js'
  ShowSinglePost(in Post {Number createdTimestamp, Text message, Text author, URL image, Number imageWidth, Number imageHeight, Text renderRecipe, Text renderParticleSpec, Text owner} post, in [Avatar {URL url, Text owner}] avatars)
  affordance dom
  consume item
  description `show ${post}`
recipe
  map 'BOXED_avatar' as avatars
  use '{{item_id}}' as v1
  slot '{{slot_id}}' as s1
  {{other_views}}
  ShowSinglePost
    post <- v1
    {{other_connections}}
    consume item as s1
```

Sample post-interpolation:

```
particle ShowSinglePost in 'https://$cdn/artifacts/Social/source/ShowSinglePost.js'
  ShowSinglePost(in Post {Number createdTimestamp, Text message, Text author, URL image, Number imageWidth, Number imageHeight, Text renderRecipe, Text renderParticleSpec, Text owner} post, in [Avatar {URL url, Text owner}] avatars)
  affordance dom
  consume item
  description `show ${post}`
recipe
  map 'BOXED_avatar' as avatars
  use '!1116802698706397:demo-yi4w7bofltv7z6hz:61' as v1
  slot '!1116802698706397:demo-yi4w7bofltv7z6hz:63' as s1
  
  ShowSinglePost
    post <- v1
    
    consume item as s1
```

The error we get on attempt to load the interpolated recipe into an inner arc:

```
Recipe is not resolvable recipe
  use '!1116802698706397:demo-yi4w7bofltv7z6hz:61' as view0 // Post {Number createdTimestamp, Text message, Text author, URL image, Number imageWidth, Number imageHeight, Text renderRecipe, Text renderParticleSpec, Text owner}
  map 'BOXED_avatar' as view1 // [Avatar {URL url, Text owner}]
  slot '!1116802698706397:demo-yi4w7bofltv7z6hz:63' as slot0
  ShowSinglePost as particle0
    avatars <- // unresolved handle-connection: missing handle
    post <- view0
    consume item as slot0
```

FYI @mmandlis @shans

**Comment by shaper** [comment]
@mmandlis from my summary above, this part:

> I believe we may need to also grab that `_context` list of handles and include them in the views we proxy, rename, and update as `otherConnections` in `multiplexer-dom-particle.js`.

Is this possible in some manner from `multiplexer-dom-particle.js`, like, right [here](https://github.com/PolymerLabs/arcs/blob/master/runtime/multiplexer-dom-particle.js#L120)?

**Comment by mmandlis** [comment]
the `views` there aren't just all the handles in the arc, but rather just the handles that are connected in the transformation particle.
what imo we do need to do, is to extend `mapHandle` (or create a new method) that will map handles into the inner arc from the real arc (or context) by IDs or tags. @shans WDYT?

**Comment by shaper** [comment]
Or per chat discussion with @mmandlis she notes maybe it's fine to just add `avatars <- avatars` in the Particle definition where the connection is noted as missing.

**Comment by shaper** [comment]
Essentially obsolete, and we'll be discussing further in person at next meetup.
