### ISSUE TITLE
windows autobuilds intermittently failing

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#1242]
I'm seeing a few failures on the appveyor build:

```
npm install
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-04-30T07_01_37_522Z-debug.log
Command exited with code 1
```

It appears to be due to a known bug in npm: https://github.com/npm/npm/issues/19989

There are a few suggestions in that thread. I'll cycle through a few of them to see if they help.

**Comment by smalls** [comment]
5.8.0 didn't fix it: https://ci.appveyor.com/project/arcs/arcs-3i77k/build/0.0.165

![foo](https://user-images.githubusercontent.com/562883/39595615-e367e680-4ec4-11e8-85dc-3db4b5bcceb9.png)

**Comment by shaper** [comment]
Seems totes fixed mayhaps by last two PRs? Can reopen if we see more. https://ci.appveyor.com/project/arcs/arcs-3i77k/history
