### ISSUE TITLE
ensure the extension doesn't create duplicate handles

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#1255]
The extension currently creates handles by type, and tries to ensure it only creates a single handle for a given type. For instance, a single handle named `browserContext_Products` will contain all products known to the browser.

At some point before #1246, the mechanism I'd been using to look at existing handles (`arc._context._handles`) was undefined in some (or all) cases. In #1246 I added a simple check to unblock use of the extension, but it's not currently clear if that list is ever populated.

In this work let's ensure that only a single list for a given type is ever created, and add a test.

**Comment by shaper** [comment]
Stale, extension needs larger review when we get back to it, closing for now.
