### ISSUE TITLE
Dynamic loads from browser environment need to be asynchronous

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#129]
The use of sync XHR in browser-loader triggers a browser warning as sync XHR is deprecated (and bad practice in any event). Using `eval` in the browser environment is also bad practice, and in particular makes the particle code invisible to the DevTools (maybe fixable via sourceMaps, but IMO better to fix the root cause).

Using sync XHR to load code that is then `eval`d  is double-plus ungood (https://github.com/PolymerLabs/arcs/commit/6d7e5e8fd12b93f9db638db73db118fe67a85d4f#diff-3063f0d93f4e10ec263645618f5aca81R75).

The best practice methods for loading code are all asynchronous and the current code expects to be able to `loadParticle` synchronously which IIUC means we need plumbing changes before modifying `browser-loader.js`.

Additionally, I think it's likely Particles will want to be able to load dependencies (code libraries, subclasses) dynamically.

**Comment by dstockwell** [comment]
`eval` is hopefully just temporary, once I switch over to webworkers (soon!) we'll be able to use `importScripts`.

**Comment by sjmiles** [comment]
Thanks Doug! 

I should have realized the `eval` thing was temporary. 

Also, `importScripts` is in fact synchronous, so at least for now my assertion that things need to be asynchronous is bogus.
