### ISSUE TITLE
restaurant demo is failing in travis

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#1339]
Output from Travis:

waiting for suggestion [Find restaurants]
found suggestion "Find restaurants near selenium's location."
accepted suggestion: Find restaurants
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
[Tue May 15 2018 23:01:55 GMT+0000 (UTC)] "GET /shell/artifacts/Events/source/PartySize.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/66.0.3359.181 Safari/537.36"
[Tue May 15 2018 23:01:55 GMT+0000 (UTC)] "GET /shell/artifacts/Restaurants/source/ReservationAnnotation.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/66.0.3359.181 Safari/537.36"
[Tue May 15 2018 23:01:55 GMT+0000 (UTC)] "GET /shell/artifacts/Restaurants/source/ReservationForm.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/66.0.3359.181 Safari/537.36"
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title
Couldn't find element with selector #webtest-title

**Comment by piotrswigon** [comment]
The timeout increase didn't work. It's weird how ReservationAnnotation and friends are requested couple of seconds after choosing Find Restaurants. I suspect this is because of the speculative execution of a recipe that is now possible with Find Restaurants in the context. Not sure though why restaurants are not rendered.

**Comment by piotrswigon** [comment]
No idea what has happened, but it succeeds again. Well, closing this.
