### ISSUE TITLE
social posts aren't updated live anymore

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#1399]
E.g. do
http://localhost:8080/shell/apps/web/?arc=-LDoDjH2XMjGkBRogp5i&user=-LBYGLHNzVrAvHho_nzX
and in another window play a word game and share it (e.g. as Walt or Maria or almost any of the other users, as long as they are Berni's friends :) )

expected: post immediately appears at the top
actual: post doesn't appear at the top until after a reload of the arc

**Comment by shans** [comment]
At least on my system (though it sounds like @sjmiles is getting a different result), the data just doesn't arrive in the social feed's handle until I reload.

e.g. if I open a console on the feed and do `arc._stores[4]._version`, it might be 9 (for arguments sake). Also there are 9 entries in the collection.

Then I create a new game arc, share it, wait, and look at `arc._stores[4]._version` again. It's still 9 and there are still 9 posts. My new game hasn't shown up in the feed.

I reload, and immediately, `arc._stores[4]._version` has been updated to 10, there are 10 entries in its collection, and my game has shown up.

What does this imply? Somehow the data isn't getting from firebase back into the store until a reload occurs. I have no idea why this would be happening though :(

**Comment by sjmiles** [comment]
It looks like the reason @shans and I were seeing different things was due to a *Ranker particle that consumes the raw post list and produces a sorted post list. I was looking at the raw post list and @shans was looking at the sorted list. The problem appears to be that Ranker is operating on slightly stale data (pre-change data is delivered while processing the change event).

**Comment by shans** [comment]
I more-or-less managed to trace this back to something that looks a lot like the issues we were having when we tried to build the github integration.

Mick's new event API is designed to fix these issues, so I switched PostTimeRanker over to using that instead. That seems to work well.
