### ISSUE TITLE
sigh is slow and devtools task appears to take 73% of total time

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1449]
On my Linux workstation `sigh devtools` is taking ~73% of total build time:

Total sigh time post-clean: 1m23.395s (it's similar even without cleaning beforehand)
Devtools-specific task time post-clean: 1m1.015s

I know we asked to put it back into the main build when it used to be separate, but I recall it being much faster, not sure if maybe some config changed or we pulled in a lot more code or something else.

I see this TODO in `sigh.js`:

```
  // TODO: To speed up the development we should invoke crisper for each file
  //       separately without bundling and then watch for updates.
```

Maybe unrelated but we also see a warning about deoptimizing, `[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.` which seems to stem from polymer build command. There may be useful info here:

https://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e

@piotrswigon @shans this is definitely not a P1 since one can just run whatever set of tasks one wants, but figured to file for discussion. I remember @shans saying at meetup we should pull it out of default. It would be nice to know that it's always up to date without having to remember to run separately, though.

**Comment by piotrswigon** [comment]
I might have caused it by including the library for visualizing traces? Though that was already couple of weeks ago, will investigate! I definitely have noticed it taking significantly more time in the last week.
