### ISSUE TITLE
Implement storage consistency

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/arcs#1471]
* [x] Remove or figure out a plan for ‘version’ in Particle API
* [x] Move Scheduler inside the PEC, dispatch events separately (but in sequence).
  * [x] Remove the old scheduler
  * [x] Add a new scheduler inside PEC
* [x] Add ability to detect self-mutation in notifications from storage-object to storage-proxy
* [x] Variables
  * [x] Update in-memory variable to suppress concurrent mutations
* [ ] Collections
  * [x] Add a model for CRDT collections, use it in storage-proxy and in-memory-store with dummy keys (undefined)
  * [x] Set real membership keys at storage-proxy and storage shim, update serialize/deserialize to preserve them.
  * [x] Make collection mutation synchronous inside PEC.
  * [ ] (deferrable) Protocol to replace ‘temporary’ keys with ‘proper’ membership keys and cleanup. This happens at the outer-pec, since that’s the context that has access to the per-arc ID generation machinery.
* [x] Firebase
  * [x] Introduce CRDT serialization at firebase storage-objects
  * [x] Track a queue of pending mutations and notify locally
  * [x] Transactionally write mutations to the remote store
  * [ ] Write unit tests. Mock firebase by detecting writes in calls to `FireBase*._transaction` and push changes by calling `_remoteStateChanged`
  * [ ] Disable the version increment check in stoage-proxy
* [ ] Batch events dispatched by the scheduler.
  * [ ] Requires significant changes to the Particle API and tests 
* [ ] …
* [ ] Profit / figure out more steps.

**Comment by lindner** [comment]
Can this be closed in favor of the new storage refactor work?

**Comment by mykmartin** [comment]
Sure can!
