### ISSUE TITLE
loading serialized arc breaks

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#1477]
For
https://polymerlabs.github.io/arcs-live/shell/apps/web/?serial=&arc=-LEvXmu2o0f6rFjgrN6H

I get
assert-web.js:11 Uncaught (in promise) Error: Cannot instantiate an unresolved recipe
    at assert (assert-web.js:11)
    at Arc.instantiate (arc.js:363)
    at Function.deserialize (arc.js:245)

I did map in data from another arc (the favorite foods), in case that could be the reason.

**Comment by sjmiles** [comment]
Turns out this is likely my bug after all. @mmandlis  detected a race condition between context-stores (BOXED_* and PROFILE_*) and the attempted deserialization.

I suspect this will be fixed if we require one full pass of context preparation before initializing the arc, which is something we wanted to do anyway for performance concerns.

**Comment by sjmiles** [comment]
This is a bigger problem then I had originally realized.

Before serialization, the shell would instantiate an arc, populate the arc and the arc context with various stores, and then instantiate recipes.

Using runtime-serialization there is no opportunity to _populate ... with ... stores_, all stores are expected to be identified in the manifest (and context manifest).

Some of the stores we want to inject will ultimately be part of the runtime-storage system (and therefore not problematic), but some are province of shell (i.e. stores shared from other arcs). 

One solution is to inject these stores into memory manifest(s) before deserialization. This could be a clean solution if the stores are archived in manifest format in the database.

Another solution could be to build an affordance into the arc lifecycle for injecting things into the context before deserializing the primary manifest.

**Comment by seefeldb** [comment]
+shane

> One solution is to inject these stores into memory manifest(s) before deserialization. This could be a clean solution if the stores are archived in manifest format in the database.

Which database do you mean here?

I assume that somewhere in the deserialization flow we look up a store by id. Can we add a hook there, that lets to shell create/supply those on the fly? And then later move a lot of that code from the shell into that layer? The concept of "virtual" stores that have to be mapped to a concrete one at deserialization time is something we need to support.

**Comment by sjmiles** [comment]
@seefeldb Met with @shans who pointed out there is already a storage abstraction in the runtime that we should take advantage of to implement some form of what your describe; at the very least it will allow us to encapsulate whatever solution behind a storage-key, which is architecturally ideal.

**Comment by sjmiles** [comment]
Lots of work was initiated around this issue. It's not yet fully solved, but I believe this exact problem formulation isn't so useful anymore. Closing.
