### ISSUE TITLE
Recipe created via serialization fails to resolve 

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1479]
The attached recipe fails to resolve because of the fate on line 101 (according to Strategizer).

`? #selected as handle4`

Changing it to

`create #selected as handle4`

It's a complicated recipe, but naively it seems like it should work as the former. Fwiw, this is a recipe generated by the experimental recipe memoization system (serializing an existing Arc + minor format tweaks).

[GeneratedTV.recipe.txt](https://github.com/PolymerLabs/arcs/files/2100366/GeneratedTV.recipe.txt)

Note there are two handles that end up with `#selected` tag (one of type TVShow, one of type TVEpisode), maybe this is relevant.

**Comment by piotrswigon** [comment]
We don't allow resolving `?` to anything but `create` right now. It's not too much work do change that, i.e. if types and tags match we can resolve `?` handle to a store via `map`/`use`/`copy` fate.

Taking a little bit longer term view on this though:
1) I can imagine `?` being used to say: "Create this or use existing one, I don't care". I don't however see right now how we could express this in the `require`/`construct` world.

2) In the longer term I don't think developer should use `?` to mean `use` or `map`, as those will be semantically different (as far as I think we agreed, at least in Syd). Today `map`/`copy` vs. `use` is respectively taking from outside / inside this arc. In the longer term however `use`/`require` would mean "give me an instance of this, I don't really care where you find it", so it may be resolved to a store in the arc, store outside current arc, coalescing a recipe to satisfy it etc. On the other hand `map` would mean "give me *the most relevant* instance of this for the user, again, I don't care where you find it, but it has to be *most important* / *canonical* version of this data".

We can add resolving `?` to other fates for the short term, but in the longer term it might not be needed. Also, we've survived so far without it. @shans @dstockwell @mmandlis opinions?

**Comment by sjmiles** [comment]
See #1671

**Comment by piotrswigon** [comment]
FWIW Maria fixed this and '?' handles can now be mapped to any storage. Yay @mmandlis!
