### ISSUE TITLE
Explore parallelizing lint step in sigh.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1506]
I noticed the `lint` phase of `sigh` runs in serial, ~500 total files, batched into 100 at a time (due to Windows command buffer limits according to a comment), and takes ~12s on my workstation. I thought perhaps we could parallelize this. My initial naive attempt to do so via `spawn` appears to roughly work on Linux and takes ~5s, but on Windows I've not yet figured out how to wait for the spawned child processes to return (and gather their exit codes) before proceeding.

Hackery [here](https://github.com/shaper/arcs/commit/aa596f784ac39b26fcfd06c743964e0d931af598) note the commented out bit at bottom must be flipped.

[cross-spawn](https://www.npmjs.com/package/cross-spawn) could be helpful.

**Comment by smalls** [comment]
We have [npm-run-all](https://www.npmjs.com/package/npm-run-all) as a devDependency, the [node API](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/node-api.md) might be an option. I think that'll be a little higher level than cross-spawn.

**Comment by lindner** [comment]
Consider only linting changed files?  I did a quick search and found this:

https://www.npmjs.com/package/lint-changed

Not sure if it's directly usable since I'm still an npm n00b.
