### ISSUE TITLE
Arcs Webdriver test is crashing.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1527]
An Arcs Webdriver test is failing, it looks like a browser crash. I re-ran once and see same error. The landed patch seems trivial and was green prior to landing. https://github.com/PolymerLabs/arcs/commit/a1063ff60b51b867270aa4d511b8a31ef8b61475

https://travis-ci.org/PolymerLabs/arcs/builds/395130428?utm_source=email&utm_medium=notification

```[chrome #0-0] Session ID: 7f2820d696067563e0a0501c173f0496
[chrome #0-0] Spec: /home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Arcs demos
[chrome #0-0]   ✓ can book a restaurant
[chrome #0-0]   ✓ can buy gifts
[chrome #0-0]
[chrome #0-0] Arcs system
[chrome #0-0]   1) can load with global manifests
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 2 passing (1m, 9s)
[chrome #0-0] 1 failing
[chrome #0-0]
[chrome #0-0] 1) Arcs system can load with global manifests:
[chrome #0-0] unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdAttribute("0.3181618222418241-2", "glowing") - index.js:312:3
[chrome #0-0]
```

**Comment by shaper** [comment]
Latest builds, [Travis](https://travis-ci.org/PolymerLabs/arcs/builds/395193816) failing but [AppVeyor](https://ci.appveyor.com/project/arcs/arcs-3i77k/build/0.0.761) passing.

**Comment by shaper** [comment]
I can repro locally on my Linux machine with `npm run test-wdio -- --mochaOpts.grep "global manifests"`

**Comment by shaper** [comment]
Test above passes at 1616cc54a73f62841184b06c6dcb480672bfa485 and fails at 922efb952c4906da6594b6f91869a065b138355c.

Thus it appears https://github.com/PolymerLabs/arcs/pull/1513 is the breaking change and we've found a situation that we may want to reduce and pass to v8 team for scrutiny. @shans as FYI and I'll look at doing this next.

I'm going to skip the test for now so that we can get an updated `arcs-live` to test. @seefeldb

**Comment by shaper** [comment]
It seems the change may only break Linux Chrome. @piotrswigon and @sjmiles find the build is ok for them on OSX.

**Comment by shans** [comment]
Is it flaky too? I 'm pretty sure it passed on Travis before I committed

**Comment by shaper** [comment]
I agree it's mystifying how Travis was green. I haven't seen it flakily pass on Linux today. It sad-tabs 100% on my machine and I haven't seen a Travis run pass the affected test on any runs today either.

I can help reduce a test case but reverting seems warranted as interim step since in parallel we're debugging a number of other bugs and issues @seefeldb is experiencing with the demos, and it's hard to determine what may be due to some unknown issue with this PR vs others, and the red build also prevents `arcs-live` from updating though I sent a PR to skip the affected test, but that itself could be a bad idea since it would be pushing a build that could potentially in fact be broken in some way.

**Comment by shaper** [comment]
OK, to recap repro steps perform the below on a Linux machine:

`git revert -n af576a54488375be0a18995183654f895c9fa99a && ./tools/sigh && npm run test-wdio -- --mochaOpts.grep "global manifests"`

**Comment by shaper** [comment]
Resolved after re-landing speculative plan grouping, disabling coalescer strategy temporarily, adding simple speculator cache, and relanding the type change.
