### ISSUE TITLE
Performance: More detailed tracing for planning, speculation.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1544]
We're interested in more detailed tracing data around planning and speculation. Part of exploring speculative resources, workload, and Worker scalability.

**Comment by piotrswigon** [comment]
I've added tracing visible in devtools extension for increased transparency. Exploration of scalability is left to be done, however I'm not sure that's a good rotation task, @shaper wdyt?

**Comment by piotrswigon** [comment]
I'll close this for now, let's reopen when we decide what more we need/want.
