### ISSUE TITLE
gift shopping demo is broken

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#1566]
to reproduce:
- accept 'Show products from your browsing context (Minecraft Book plus 2 other items) and choose from products recommended based on products from your browsing context and Claire\'s wishlist (Book: How to Draw plus 2 other items).' suggestion
- click `Add` button on any of the recommended products
results in exception: 
```
firebase.4.2.0.js:321 Uncaught (in promise) Error: Reference.child failed: First argument was an invalid path = "arcs/-LG2bLR_NCDhLflqWMqy/shim_handles/shortlist/data/manifest:./../../artifacts/Products/Products.recipes::3". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
    at G (firebase.4.2.0.js:321)
    at e.child (firebase.4.2.0.js:321)
    at change.add.forEach.record (cloud-handles.js:144)
    at Array.forEach (<anonymous>)
    at HTMLElement._localSetChange (cloud-handles.js:142)
    at handle.on.change (cloud-handles.js:120)
    at InMemoryCollection._fire (storage-provider-base.js:66)
    at InMemoryCollection.store (in-memory-storage.js:141)
    at PECOuterPort.ParticleExecutionHost._apiPort.onHandleStore (particle-execution-host.js:60)
    at PECOuterPort._handle (api-channel.js:178)
```

**Comment by shans** [comment]
What are the shim_handles in the id? Is this a new shell thing?

**Comment by mykmartin** [comment]
Note that the _localSetChange code has been around for 2 months: https://github.com/PolymerLabs/arcs/blame/master/shell/app-shell/elements/cloud-data/cloud-handles.js#L144 - why is this only surfacing now?

**Comment by mmandlis** [comment]
2 months is a long time, i'm inclined to think that i tried it since (but yeah, we need a selenium test for it too).
@sjmiles Scott, any ideas of anything else that might have changed and affected it?

**Comment by sjmiles** [comment]
`shim_handles` [sic, these are stores] has been around forever (with different names). This is the property of an Arc record that the shell uses to persist store data in Firebase.

I can't see why Myk's mods wouldn't work, but I'll take a look.

I also can't think of any recent change that would have caused this.

**Comment by mykmartin** [comment]
The problem has in fact been there since Scott's big merge. Going back to the merge commit (4d492123) still shows the error, testing at the commit prior to that (f56c61ec) doesn't.

**Comment by sjmiles** [comment]
Thanks Myk. I believe the reason it's not affecting more Arcs is because the Gifts demo is using static data embedded inside of a Manifest, which is statistically unusual.

**Comment by sjmiles** [comment]
@mykmartin can you provide me with the `custom function that maps .#$[]% to the usual %<hex> notation`?

**Comment by sjmiles** [comment]
So, any kind of blanket encoding will be a problem for the existing corpus of Arc data, unless we also encode some kind of sentinel bytes, but this seems like more trouble than it's worth.

My top priority remains turning off `shim-handles` anyway in favor of runtime storage, so I'm leaning towards a simple patch.

Forcing all '.' and '/' to '%' seems to work, I may just push that.

**Comment by mykmartin** [comment]
That doesn't work for me; I get the following error whether I use the "full" encoding or just the simple `./` replacement:
```
Uncaught (in promise) TypeError: Cannot read property 'set' of undefined
    at models.forEach (xen-template.js:304)
    at Array.forEach (<anonymous>)
    at _renderSubtemplates (xen-template.js:291)
    at _setSubTemplate (xen-template.js:284)
    at _set (xen-template.js:250)
    at set (xen-template.js:224)
    at Object.set (xen-template.js:343)
    at DomContext.updateModel (dom-context.js:81)
    at DomSlot._doRender (dom-slot.js:109)
    at DomSlot.setContent (dom-slot.js:99)
```

My change is:
```
  _localSetChange(handle, path, change, remoteValue) {
    log('localSetChange', change);
    let xfn = s => {
      if (s) {
        let o = s;
        //s = s.replace(/[./]/g, '%')  // for ./ -> %
        s = s.replace(/%/g, '%25');
        s = s.replace(/#/g, '%23');
        s = s.replace(/\$/g, '%24');
        s = s.replace(/\./g, '%2E');
        s = s.replace(/\[/g, '%5B');
        s = s.replace(/\]/g, '%5D');
        s = s.replace(/\//g, '%2F');
        console.log(o, '->', s);
      }
      return s;
    };
    if (change.add) {
      change.add.forEach(record => {
        log('trigger: local add', record);
        Firebase.db.child(`${path}/data/${xfn(record.id)}`).set(ArcsUtils.removeUndefined(record));
      });
    } else if (change.remove) {
      change.remove.forEach(record => {
        log('trigger: local remove', record);
        Firebase.db.child(`${path}/data/${xfn(record.id)}`).remove();
      });
    } else {
      warn('Unsupported "handle.change" event', change);
    }
  }
```
I'm running webpack, returning to the launcher (using index.debug.html), reloading and creating a new arc between every change.

**Comment by sjmiles** [comment]
This is actually _working_, in the sense that the you have achieved the next exception (which is due to a ill-formed subtemplate in ShowCollection.js). Fwiw, there is another PR en route to tolerate and warn on the bad subtemplate condition.

>> I'm running webpack, returning to the launcher (using index.debug.html), reloading and creating a new arc between every change.

Fwiw, reloading with a clean cache is all you have to do when you modify shell-side code.

**Comment by mykmartin** [comment]
> This is actually working, ...

:D

> Fwiw, reloading with a clean cache is all you have to do when you modify shell-side code.

I did think that was the case, but just wanted to rule out any possible side effects. Also, I wasn't sure if my changes to the firebase path encoding would persist (in firebase) between reloads of the same arc, hence the new arc each time.

**Comment by sjmiles** [comment]
The primary issue is resolved, although the method used for cleaning Firebase keys is somewhat dubious. Closing for now.
