### ISSUE TITLE
Entity `id` can be hidden by `id` field

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1574]
Today, we collate (_box_) data from multiple users into a single index to provide a simplified query ability.

However, there is no field in general on an Entity that we can use to identify the owner (or source) of that Entity.

Shell has a working solution that involves encoding the owner id into the Entity id itself, which works well. However, sometimes the Entity's schema creates an `id` field obscuring access to the Entity's (symbol) id.

There is a note in the code that (symbol) `id` shouldn't be exposed in any case, but it's very useful today for the boxing affordance.

Suggested fix incoming as PR.

**Comment by seefeldb** [comment]
Hiding the `id` is part of defense-in-depth for privacy protections, to make re-identification harder (we'll also have to be careful in the future with timestamps and other meta data). And really it should be the case that it never gets into the innerPEC anyhow!

However, `owner` or `source` or whatever this concept evolves to will be a thing. Maybe it would be better to introduce `$owner()` now and just return the part of the `id` where the owner is encoded?

**Comment by sjmiles** [comment]
I guess I'm inclined to do the tiny fix instead of a half-measure. I didn't make privacy worse, as the id was already available (all I did was alias it). But that's just my $0.02. 

Fwiw, I will soon introduce this method into dom-particle:

  /** @method boxQuery(box, userid)
   * Returns array of Entities found in BOXED data `box` that are owned by `userid`
   */

This is closer to what we ultimately want in the API. If we can implement this in the outerPEC, then we don't have to expose anything from the ID. Seems like we need new `handle` API to make the better solution work, I didn't want to do that without consultation with runtime team.

**Comment by sjmiles** [comment]
I looked at the `userIDComponent` stuff in runtime, and it looks like I can store the owner id in the `uid:` component on the Entity id. Then Particles can grab that information via `entity.getUserID()]`.

This way I can remove the `$id` alias and generally none of this code will rely on whole id access.

@shans is it ok for me to use `uid:` this way?

**Comment by shans** [comment]
This seem ok to me, yeah.

**Comment by sjmiles** [comment]
We used the `userIDComponent` to create `getUserID` API to avoid Particles handling id's directly. 

We can consider variations and so on, but the immediate problem is resolved.
