### ISSUE TITLE
Description capitalization incorrect in some cases

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1618]
In this example, 'Estimate' and 'Find' should not be capitalized.

> Buy gifts for Claire (Claire)'s Birthday on 2017-08-04, Estimate arrival date for products from your browsing context (Minecraft Book plus 2other items), and Find alternate shipping for products which won't make it on time for products from your browsing context.

**Comment by mmandlis** [comment]
Can't reproduce this anymore with the updated demo, please, reopen if there is a repro.
