### ISSUE TITLE
can't create new post

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#1626]
on arcs-live, select the `Write posts, show post list, edit a post, and show details about post.` suggestion.
a new arc is created. the text `Get started by naming your miniblog and creating your first post!` appears, but there is no + button to create a new post.

Weirdness: it's somewhat flaky, it did appear once, but never since.

**Comment by shaper** [comment]
I believe you but I can't reproduce in ten reloads on Linux.

It's hard coded to 600px wide. Is your window smaller than that? Maybe it's just off to the right.

**Comment by mmandlis** [comment]
you're right, i'm stupid (and the time when i was able to see it, i didn't have dev tools open, haha).
