### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1628]
Seeing many errors like below, as Walt user at ToT. Believe this error has been around for at least a week or two.

```
Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at CollectionProxy._processUpdate (storage-proxy.js:248)
    at CollectionProxy._processUpdates (storage-proxy.js:164)
    at CollectionProxy._onUpdate (storage-proxy.js:147)
    at callback (storage-proxy.js:81)
    at PECInnerPort.ParticleExecutionContext._apiPort.onSimpleCallback (particle-execution-context.js:67)
    at PECInnerPort._handle (api-channel.js:178)
    at MessagePort.APIPort._port.onmessage (api-channel.js:90)
_processUpdate @ storage-proxy.js:248
_processUpdates @ storage-proxy.js:164
_onUpdate @ storage-proxy.js:147
callback @ storage-proxy.js:81
ParticleExecutionContext._apiPort.onSimpleCallback @ particle-execution-context.js:67
_handle @ api-channel.js:178
APIPort._port.onmessage @ api-channel.js:90
```

**Comment by sjmiles** [comment]
At https://github.com/PolymerLabs/arcs/blob/master/runtime/particle-execution-host.js#L57 an event structure is expected that is `{handle, data: {value, keys}, particleId}`

However, at https://github.com/PolymerLabs/arcs/blob/master/runtime/storage-proxy.js#L312 the `data` object is constructed like so  `let data = {id, keys};`

I believe `value` in the former is intended to match `id` in the latter, but the expansions don't match.

**Comment by dstockwell** [comment]
I intended to pass `id` as `id`. So the bug is in particle-execution-host. There's a test that covers storage-proxy doing the right thing, but no tests invoked that logic in particle-execution-host 😞
