### ISSUE TITLE
behavior of `store.remove(id)` if id is not in store

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1673]
It looks like if I `store.remove(id_not_in_store)` we end up throwing an exception at StorageProxy.js#248 (it tries to evaluate `value.id` for a null value).

If I have diagnosed this correctly, then it probably should do something more meaningful (i.e. work silently, error, or warn more directly).

I may have misdiagnosed this, it just came up in the middle of debugging something else.

**Comment by mykmartin** [comment]
I can't seem to repro this - is this inside or outside the PEC?

If outside, the StorageProxy shouldn't be invoked at all. If inside, the Handle.remove API uses entities, not ids. I tried using handle._proxy.remove but didn't have any problems.

**Comment by mykmartin** [comment]
Ok I'm seeing the problem when running live (I was using unit tests before). Investigating.
