### ISSUE TITLE
Gift shopping demo - Chooser particle doesn't render

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#1680]
"Add items from Claire's wishlist" (ie Chooser particle) doesn't render, when the suggestion is accepted.
However, it does render on "refresh"

**Comment by shans** [comment]
It looks like this might be a race condition between firebase (from cloud-handles) and the copy of the handle?

**Comment by mmandlis** [comment]
@sjmiles could you, please, take a look?

**Comment by sjmiles** [comment]
Yes, this problem was in cloud-handles. 

Variables that are copied have an initial value not mirrored in FB, and cloud-handles was clobbering that value with nothingness.

Repairs en route, although we will make cloud-handles go away wholesale, asap.
