### ISSUE TITLE
Duplicate suggestions with the only difference of search tokens

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#1714]
non empty search that produces an already existing suggestion will show up twice, because search affects the recipe hash.

**Comment by mmandlis** [comment]
@shans and I discussed a potential solution of:
- considering `search` resolved only if ALL tokens were resolved
- adding a strategy to discard non-resolved tokens for terminal recipes
- not serializing resolved search tokens

Then search-based recipe
```
recipe
  search `nearby restaurants`
```
is resolved to
```
recipe
  FindRestaurants
```
and it is same as straight forward recipe that was declared in a manifest:
```
recipe
  FindRestaurants
```

This solution doesn't work, because then when filtering the resulted suggestions by 'nearby restaurants', this recipe isn't found.

**Comment by shans** [comment]
how was this working before? We kept the entire search string around?

**Comment by mmandlis** [comment]
yes, before we would serialize everything, like:
```
recipe
  search `all the nearby restaurants`
    tokens `all` `the` // `nearby` `restaurants`
  FindRestaurants
```
where the resolved search tokens come in the comment //
