### ISSUE TITLE
Assert in planificator after accepting suggestion

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#1715]
There's an assert at planificator.js:259 if I start up arcs (as Berni) with ?serial=&store= and accept the 'plaid' recipe suggestion.

The assert ensures that planString (presumably the selected suggestion?) matches one of the current plans.

planString is:
```
"recipe SelectableCopyListRecipe
  copy 'manifest:https://sjmiles.github.io/arcs-stories/0.4/Demo/PlaidData.manifest:store0:b0d838ca9044b7e05be77e0fb412ea41ef947cd7' #items as handle0 // [PlaidAccount {...}]
  create #selected as handle1 // PlaidAccount {...}
  copy '!1101707015171344:app-shell-a8eyy6ozeu7cjye0d:particle-literal:PlaidAccountItem' as handle2 // HostedParticleShape
  slot 'rootslotid-root' #root as slot1
  ItemMultiplexer as particle0
    hostedParticle = handle2
    list <- handle0
    consume item as slot0
  SelectableList as particle1
    items = handle0
    selected = handle1
    consume root as slot1
      provide action as slot2
      provide annotation as slot3
      provide item as slot0
      provide postamble as slot4
      provide preamble as slot5"
```

There are 29 current plans. The closest match is:

```
"recipe
  create #items #xactions as handle0 // [PlaidTransaction {...}]
  use '!1101707015171344:app-shell-a8eyy6ozeu7cjye0d:129' #selected as handle1 // PlaidAccount {...}
  map 'manifest:https://sjmiles.github.io/arcs-stories/0.4/Demo/PlaidData.manifest:store1:3efbba6e214eb60a2e64ac32e2d8c9f9fe2e167d' as handle2 // [PlaidTransaction {...}]
  create #selected as handle3 // PlaidTransaction {...}
  copy '!1101707015171344:app-shell-a8eyy6ozeu7cjye0d:particle-literal:PlaidTransactionItem' as handle4 // HostedParticleShape
  slot 'rootslotid-root' #root as slot1
  ItemMultiplexer as particle0
    hostedParticle = handle4
    list <- handle0
    consume item as slot0
  PlaidTransactionFilter as particle1
    account <- handle1
    accountTransactions = handle0
    transactions <- handle2
  SelectableList as particle2
    items = handle0
    selected = handle3
    consume root as slot1
      provide action as slot2
      provide annotation as slot3
      provide item as slot0
      provide postamble as slot4
      provide preamble as slot5"
```

Note that this is the next-stage recipe (i.e. adding transactions to the accounts). Is it possible that the plan list has already been updated to match the new recipe (i.e. the first plan was instantiated) and that this assert is in effect a race condition?

This hypothesis is supported by 2 other items:
(1) the recipe has already loaded at the point of this assert (arc.activeRecipe.toString() contains the plan)
(2) the suggestion list has already been updated to include "Show plaid transaction list" at the point of this assert

**Comment by mmandlis** [comment]
It is reproducible with my user as well.
But not without `?serial=&store=`.
How do these affect instantiated plan / replanning, I wonder?

**Comment by shans** [comment]
Maybe just performance? As in with these settings, something is faster or slower, which manifests the race?

**Comment by mmandlis** [comment]
old planificator deleted https://github.com/PolymerLabs/arcs/pull/2294
