### ISSUE TITLE
PlaidTransactions regression

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1777]
Previously, the coalescer could produce a `Show plaid transaction list` suggestion by automatically combining `ItemMultiplexer`, `SelectableList`, and `PlaidTransactionFilter` (for an Arc that already contains `Show plaid accounts...`).

Bisecting on ArcsLive, this suggestion is [produced ](https://cdn.rawgit.com/PolymerLabs/arcs-live/cc682005ff7b22dda3cfbccde0d2c7f36641e0ff/shell/apps/web/index.html?arc=-LJzwpAoUnZ2r57nP1rO&search=plaid) on 7/31 (cc682005ff7b22dda3cfbccde0d2c7f36641e0ff), but no longer by the first rebuild on 8/1 (5d35d99b9264be6e5b028b88edd61c291abc3c7f).

Perhaps due to commit 88e364b5b4227385465af31347b6bf74d47f9279?

**Comment by shans** [comment]
That looks likely. I'm probably not going to be able to pull together enough context to fix/address this in a reasonable time, is it OK to wait for @mmandlis to get back?

**Comment by sjmiles** [comment]
Yes, that's ok. I know you have three plates worth on your plate already. Thanks for spot-checking, that's all I needed when I assigned you.

**Comment by mmandlis** [comment]
This is happening because the coalescing updated in #1713 (@sjmiles, thanks for the bisecting!) tries to coalesce all the possible handles, and finds `selected` (as the selected account) and `selected` (as the selected transaction) as a possible match. 
This is wrong, because their type isn't the same. Will work on a fix now.

**Comment by shans** [comment]
Actually, it isn't wrong. The type system is correctly inferring that these recipes can merge as long as the data on the merged handle is (at least) both a PlaidTransaction and a PlaidAccount.

There's no technical reason at all why this combined recipe can't be used, so you'll need to work out another way to eliminate it - possibly by trying to resolve the combined handle to point to a store? Alternatively by providing an explicit type for the handles (though I don't think we yet support this)?
