### ISSUE TITLE
Node/Web Import Compatibility

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1810]
Historically, we maintained ES6 module compatibility across all modules, so that we could `import` a source tree from either Node or Web context without loss of generality. This ability is particularly useful for doing edit/debug cycles without requiring a build step.

`shell/apps/web/index.debug.html` is an example entry-point that took advantage of this feature.

Recently we have introduced some Node-specific import syntax which break this compatibility (name-resolution vs path-resolution [shout out to Empathy]) . 

Examples: 
https://github.com/PolymerLabs/arcs/blob/master/runtime/ts/storage/firebase-storage.ts#L14
https://github.com/PolymerLabs/arcs/blob/master/shell/source/ArcsLib.js#L21

Sometimes this problem can go away if one uses full paths instead of relying on Node resolution. 

For example
```
import * as firebase from 'firebase/app';
``` 
can be replaced with 
```
import firebase from '../../node_modules/firebase/app/dist/index.esm.js';
```
.. but there are other alternatives too. 

Also, @lindner mentioned maintaining a build of node_modules resources separate from the runtime code. This is attractive as the node build should change rarely, cutting down on build time. It would also make it easier to ensure no runtime code relies on node name-resolution, solving the compatibility problem with minimal tooling.

**Comment by shans** [comment]
Am I wrong in my belief that we only stopped maintaining this compatibility with @lindner 's recent patch? Or are there some older patches too?

**Comment by sjmiles** [comment]
I think this came up as part of @linder's work. We talked about it f2f, he asked me to make this ticket.

**Comment by sjmiles** [comment]
Fwiw, it's relatively easy to resolve this problem wrt Firebase. For example, in `firebase-storage.ts` I can replace
```
// keep in sync with shell/source/ArcsLib.js
import * as firebase from 'firebase/app';
import 'firebase/database';
import 'firebase/storage';
```
with 
```
declare var firebase: typeof import('firebase');
import {firebase} from '../../firebase.js';
```
Where `runtime/firebase.js` looks like this:
```
import firebase from '../node_modules/firebase/app/dist/index.esm.js';
import '../node_modules/firebase/database/dist/index.esm.js';
import '../node_modules/firebase/storage/dist/index.esm.js';
export {firebase};
```

Unfortunately, this doesn't actually make `index.debug.html` work as the new runtime/ts source uses node-style imports in general which isn't compatible with the browser loader. For example, `ts-build/storage-provider-factory.js` contains:
```
import { InMemoryStorage } from './in-memory-storage';
import { FirebaseStorage } from './firebase-storage';
export class StorageProviderFactory {
```
That import syntax are not ES6 compatible. It's possible we can do some similar trick via loading the types explicitly, but at some point I would guess that makes using Typescript less valuable.

**Comment by sjmiles** [comment]
Sorry for the noise, but I kinda have it backwards above. 


```
import { InMemoryStorage } from './in-memory-storage';
```

**Comment by lindner** [comment]
Some interesting writeup here:

https://nolanlawson.com/2017/01/09/how-to-write-a-javascript-package-for-both-node-and-the-browser/

I wonder if we could make a single import that covers our external dependencies?  That way node and the browser could have a consistent view of the world....

**Comment by sjmiles** [comment]
Marking as a `p1` until we create a POR or at least isolate an assignee.

**Comment by shaper** [comment]
I'm making @lindner the owner here following Highlander principle, but @shans @sjmiles should obviously continue to discuss.

**Comment by sjmiles** [comment]
I did a bunch of work to solve some of these problems from a pragmatic POV, see this [document](https://docs.google.com/document/d/1Sa8c7LcK9BQFQQPN3HBC1MKb2EkiH3QbApsgicrjMVU/edit#).

**Comment by lindner** [comment]
The current plan for Node + ES modules is here:

http://2ality.com/2018/12/nodejs-esm-phases.html

You'll note that it includes browser equivalence as a core tenet; however it also adheres to mjs and other design decisions.

I'll see if there's some way we can get around the issues you identified.

**Comment by shaper** [comment]
Pinging for status update as this is marked P1.
