### ISSUE TITLE
Find out what prevents Arcs from running on IOS/Safari

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1828]
Last time I looked, the shell ran ok, but somewhere Arcs runtime gets stuck waiting for a Promise or other async effect to complete (which never does).

I assigned all the engineers in case somebody wants to jump on this. Please un-assign yourself if this feels out of scope for you.

**Comment by mmandlis** [comment]
I think, this is smth to do with out of memory:
Loading every manifest as solo works fine, except the restaurants one. If I comment out any single recipe out of Restaurants, I get suggestions too. With all the possible combinations of coalescing it gets stuck. 
This is as far as I got for now.

**Comment by shaper** [comment]
Someone with a Mac should own this, to explore with Safari. @mmandlis can you look at some point? The initial task seems to be just to explore a bit more, and you already did some work bisecting of sorts. Not a high P1 but I agree with Scott that it'd be nice to get some insight.

I don't think we should `wontfix` this.

**Comment by lindner** [comment]
If we close this we should create a new issue to run webdriver tests with
Sauce or some other cross-browser mechanism.
