### ISSUE TITLE
Arcs Circular Dependencies

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#1878]
There are probably more, but these ones were quickly found:

madge --circular .
Processed 1311 files (20.4s) (105 warnings)

✖ Found 12 circular dependencies!

1) runtime/recipe/type-checker.js > runtime/ts-build/type.js
2) runtime/ts-build/type.js > runtime/ts-build/schema.js > runtime/entity.js
3) runtime/ts-build/type.js > runtime/ts-build/schema.js
4) runtime/recipe/type-checker.js > runtime/ts-build/type.js > runtime/ts-build/shape.js
5) runtime/ts-build/type.js > runtime/ts-build/shape.js
6) runtime/ts-build/type.js > runtime/tuple-fields.js
7) runtime/ts-build/type.js > runtime/type-variable.js
8) runtime/manifest.js > runtime/ts-build/storage/storage-provider-factory.js > runtime/ts-build/storage/synthetic-storage.js
9) runtime/handle.js > runtime/ts-build/reference.js
10) runtime/arc.js > runtime/recipe-index.js
11) runtime/ts-build/hosted-slot-consumer.js > runtime/ts-build/hosted-slot-context.js
12) shell/components/data-explorer.js > shell/components/data-item.js

**Comment by shans** [comment]
Would be interested in a discussion of whether this is an short-term or long-term issue; for example, types are circular because they are recursive (i.e. a type can be a type variable that can contain a resolved type). Trying to fix this issue is going to complexify the code; is it worth doing anything soon or something that can be saved for the next type system refactor?

**Comment by raulverag** [comment]
Circular dependencies aren't a problem within modules, but certainly are across module boundaries. As I look at where to draw module boundaries in detail, I'll consult (or regenerate) this list. First I'll get up to speed on madge.

**Comment by raulverag** [comment]
I've installed madge and tried this for myself:

madge --circular .
Processed 918 files (12.5s) (69 warnings)

✖ Found 13 circular dependencies!

1) build/runtime/recipe/type-checker.js > build/runtime/type.js > build/runtime/interface-info.js
2) build/runtime/type.js > build/runtime/interface-info.js
3) build/runtime/recipe/type-checker.js > build/runtime/type.js
4) build/runtime/recipe/type-checker.js > build/runtime/type.js > build/runtime/schema.js
5) build/runtime/particle-spec.js > build/runtime/recipe/type-checker.js > build/runtime/type.js > build/runtime/schema.js > build/runtime/reference.js > build/runtime/handle.js
6) build/runtime/reference.js > build/runtime/handle.js
7) build/runtime/type.js > build/runtime/schema.js > build/runtime/reference.js > build/runtime/handle.js
8) build/runtime/type.js > build/runtime/schema.js > build/runtime/reference.js
9) build/runtime/type.js > build/runtime/schema.js
10) build/runtime/type.js > build/runtime/type-variable-info.js
11) build/runtime/manifest.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/synthetic-storage.js
12) build/runtime/hosted-slot-consumer.js > build/runtime/hosted-slot-context.js
13) modalities/dom/components/elements/data-explorer.js > modalities/dom/components/elements/data-item.js

None of these look particularly problematic to me, as they all remain within the module I intend to put them in.

I'm going to lower the priority on this but leave it open and assigned to me, just as a reminder to occasionally check this. Feel free to comment and up the priority if you see something that looks serious.

**Comment by raulverag** [comment]
madge needs updating to deal with our current code base. Version 3.4.4 gives the following output. None of these look serious, as they all remain within their modules.

$ madge -c .
Processed 1988 files (26.8s) (96 warnings)

✖ Found 42 circular dependencies!

1) build/runtime/interface-info.js > build/runtime/recipe/type-checker.js > build/runtime/type.js
2) build/runtime/recipe/type-checker.js > build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js
3) build/runtime/entity.js > build/runtime/reference.js
4) build/runtime/entity.js > build/runtime/reference.js > build/runtime/handle.js
5) build/runtime/particle-spec.js > build/runtime/particle-check.js
6) build/runtime/recipe/type-checker.js > build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js > build/runtime/reference.js > build/runtime/handle.js > build/runtime/particle-spec.js
7) build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js > build/runtime/reference.js > build/runtime/handle.js > build/runtime/particle-spec.js
8) build/runtime/reference.js > build/runtime/handle.js
9) build/runtime/handle.js > build/runtime/storage-proxy.js
10) build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js > build/runtime/reference.js > build/runtime/handle.js > build/runtime/storage-proxy.js
11) build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js > build/runtime/reference.js > build/runtime/handle.js
12) build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js > build/runtime/reference.js
13) build/runtime/type.js > build/runtime/schema.js > build/runtime/entity.js
14) build/runtime/type.js > build/runtime/schema.js
15) build/runtime/type.js > build/runtime/type-variable-info.js
16) build/runtime/recipe/handle.js > build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js
17) build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js > build/runtime/recipe/handle-connection.js > build/runtime/recipe/recipe-util.js
18) build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js > build/runtime/recipe/handle-connection.js
19) build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js
20) build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js
21) build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js > build/runtime/recipe/slot.js
22) build/runtime/manifest.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/synthetic-storage.js
23) build/runtime/manifest.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/volatile-storage.js > build/runtime/runtime.js > build/runtime/arc.js
24) build/runtime/manifest.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/volatile-storage.js > build/runtime/runtime.js > build/runtime/arc.js > build/runtime/particle-execution-host.js
25) build/runtime/storage/storage-provider-factory.js > build/runtime/storage/volatile-storage.js > build/runtime/runtime.js > build/runtime/arc.js
26) build/runtime/manifest.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/volatile-storage.js > build/runtime/runtime.js
27) build/runtime/runtime.js > build/runtime/testing/fake-slot-composer.js > build/runtime/modality-handler.js > build/runtime/headless-slot-dom-consumer.js > build/runtime/slot-dom-consumer.js
28) devtools/deps/moment/src/lib/create/check-overflow.js > devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js
29) devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-array.js > devtools/deps/moment/src/lib/create/local.js
30) devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-array.js > devtools/deps/moment/src/lib/units/week-calendar-utils.js > devtools/deps/moment/src/lib/units/year.js > devtools/deps/moment/src/lib/moment/get-set.js
31) devtools/deps/moment/src/lib/units/year.js > devtools/deps/moment/src/lib/moment/get-set.js
32) devtools/deps/moment/src/lib/create/check-overflow.js > devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/from-string-and-format.js
33) devtools/deps/moment/src/lib/create/from-string-and-format.js > devtools/deps/moment/src/lib/create/from-string.js
34) devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/from-string-and-format.js > devtools/deps/moment/src/lib/create/from-string.js > devtools/deps/moment/src/lib/units/day-of-week.js
35) devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/from-string-and-format.js > devtools/deps/moment/src/lib/create/from-string.js
36) devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/valid.js
37) devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/locale/locales.js > devtools/deps/moment/src/lib/locale/base-config.js
38) devtools/deps/moment/src/lib/duration/constructor.js > devtools/deps/moment/src/lib/duration/valid.js
39) devtools/deps/moment/src/lib/duration/create.js > devtools/deps/moment/src/lib/duration/constructor.js > devtools/deps/moment/src/lib/duration/valid.js
40) devtools/deps/moment/src/lib/duration/create.js > devtools/deps/moment/src/lib/units/offset.js
41) devtools/deps/moment/src/lib/duration/create.js > devtools/deps/moment/src/lib/units/offset.js > devtools/deps/moment/src/lib/moment/add-subtract.js
42) modalities/dom/components/elements/data-explorer.js > modalities/dom/components/elements/data-item.js

**Comment by piotrswigon** [comment]
@raulverag this can be closed now, right? :)

**Comment by raulverag** [comment]
Well, madge still finds the following. Clearly the webpack plugin we used has limitations at best or just doesn't work at worst. Damn.

$ madge --circular .
Processed 2086 files (30.7s) (93 warnings)

✖ Found 30 circular dependencies!

1) build/runtime/recipe/handle.js > build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js
2) build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js > build/runtime/recipe/handle-connection.js > build/runtime/recipe/recipe-util.js
3) build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js > build/runtime/recipe/handle-connection.js
4) build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js
5) build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js > build/runtime/recipe/particle.js
6) build/runtime/recipe/slot-connection.js > build/runtime/recipe/recipe.js > build/runtime/recipe/slot.js
7) build/runtime/manifest.js > build/runtime/runtime.js > build/runtime/arc.js
8) build/runtime/manifest.js > build/runtime/runtime.js > build/runtime/arc.js > build/runtime/particle-execution-host.js
9) build/runtime/runtime.js > build/runtime/arc.js
10) build/runtime/manifest.js > build/runtime/runtime.js > build/runtime/arc.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/synthetic-storage.js
11) build/runtime/runtime.js > build/runtime/arc.js > build/runtime/storage/storage-provider-factory.js > build/runtime/storage/volatile-storage.js
12) build/runtime/manifest.js > build/runtime/runtime.js
13) build/runtime/runtime.js > build/runtime/testing/fake-slot-composer.js > build/runtime/modality-handler.js > build/runtime/headless-slot-dom-consumer.js > build/runtime/slot-dom-consumer.js
14) devtools/deps/moment/src/lib/create/check-overflow.js > devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js
15) devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-array.js > devtools/deps/moment/src/lib/create/local.js
16) devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-array.js > devtools/deps/moment/src/lib/units/week-calendar-utils.js > devtools/deps/moment/src/lib/units/year.js > devtools/deps/moment/src/lib/moment/get-set.js
17) devtools/deps/moment/src/lib/units/year.js > devtools/deps/moment/src/lib/moment/get-set.js
18) devtools/deps/moment/src/lib/create/check-overflow.js > devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/from-string-and-format.js
19) devtools/deps/moment/src/lib/create/from-string-and-format.js > devtools/deps/moment/src/lib/create/from-string.js
20) devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/from-string-and-format.js > devtools/deps/moment/src/lib/create/from-string.js > devtools/deps/moment/src/lib/units/day-of-week.js
21) devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/from-string-and-format.js > devtools/deps/moment/src/lib/create/from-string.js
22) devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/create/from-string-and-array.js > devtools/deps/moment/src/lib/create/valid.js
23) devtools/deps/moment/src/lib/units/month.js > devtools/deps/moment/src/lib/create/utc.js > devtools/deps/moment/src/lib/create/from-anything.js > devtools/deps/moment/src/lib/locale/locales.js > devtools/deps/moment/src/lib/locale/base-config.js
24) devtools/deps/moment/src/lib/duration/constructor.js > devtools/deps/moment/src/lib/duration/valid.js
25) devtools/deps/moment/src/lib/duration/create.js > devtools/deps/moment/src/lib/duration/constructor.js > devtools/deps/moment/src/lib/duration/valid.js
26) devtools/deps/moment/src/lib/duration/create.js > devtools/deps/moment/src/lib/units/offset.js
27) devtools/deps/moment/src/lib/duration/create.js > devtools/deps/moment/src/lib/units/offset.js > devtools/deps/moment/src/lib/moment/add-subtract.js
28) modalities/dom/components/elements/data-explorer.js > modalities/dom/components/elements/data-item.js
29) server/dist/deployment/cloud.js > server/dist/deployment/gcp/gcp.js > server/dist/deployment/gcp/gcpdisk.js
30) server/dist/deployment/cloud.js > server/dist/deployment/gcp/gcp.js > server/dist/deployment/k18s/manager.js

**Comment by raulverag** [comment]
Running from just within the build directory gives the following:

$ cd build
$ madge --circular .
Processed 481 files (3.1s) (3 warnings)

✖ Found 13 circular dependencies!

1) runtime/recipe/handle.js > runtime/recipe/slot-connection.js > runtime/recipe/recipe.js
2) runtime/recipe/recipe.js > runtime/recipe/particle.js > runtime/recipe/handle-connection.js > runtime/recipe/recipe-util.js
3) runtime/recipe/slot-connection.js > runtime/recipe/recipe.js > runtime/recipe/particle.js > runtime/recipe/handle-connection.js
4) runtime/recipe/recipe.js > runtime/recipe/particle.js
5) runtime/recipe/slot-connection.js > runtime/recipe/recipe.js > runtime/recipe/particle.js
6) runtime/recipe/slot-connection.js > runtime/recipe/recipe.js > runtime/recipe/slot.js
7) runtime/manifest.js > runtime/runtime.js > runtime/arc.js
8) runtime/manifest.js > runtime/runtime.js > runtime/arc.js > runtime/particle-execution-host.js
9) runtime/runtime.js > runtime/arc.js
10) runtime/manifest.js > runtime/runtime.js > runtime/arc.js > runtime/storage/storage-provider-factory.js > runtime/storage/synthetic-storage.js
11) runtime/runtime.js > runtime/arc.js > runtime/storage/storage-provider-factory.js > runtime/storage/volatile-storage.js
12) runtime/manifest.js > runtime/runtime.js
13) runtime/runtime.js > runtime/testing/fake-slot-composer.js > runtime/modality-handler.js > runtime/headless-slot-dom-consumer.js > runtime/slot-dom-consumer.js

**Comment by raulverag** [comment]
The first step, and it might be my last on this, is to add madge to our packages and a command, or flag, or lint step, to sigh.

**Comment by raulverag** [comment]
Sigh now has a `cycles` command, which is invoked as part of `lint`. This runs `madge` in the `build` directory, as above.

**Comment by raulverag** [comment]
Unassigning as I'm done.

**Comment by shaper** [comment]
The WIP PR above moves cycles from 11 to 8 (but I have not yet finished updating the tests).

**Comment by shaper** [comment]
Excitingly, we are down to only 6 remaining after #4360 lands, and #4359 aims to solve those.

```
1) runtime/recipe/handle.js > runtime/recipe/slot-connection.js > runtime/recipe/recipe.js
2) runtime/recipe/recipe.js > runtime/recipe/particle.js > runtime/recipe/handle-connection.js > runtime/recipe/recipe-util.js
3) runtime/recipe/slot-connection.js > runtime/recipe/recipe.js > runtime/recipe/particle.js > runtime/recipe/handle-connection.js
4) runtime/recipe/recipe.js > runtime/recipe/particle.js
5) runtime/recipe/slot-connection.js > runtime/recipe/recipe.js > runtime/recipe/particle.js
6) runtime/recipe/slot-connection.js > runtime/recipe/recipe.js > runtime/recipe/slot.js
```
