### ISSUE TITLE
Serialization and `RecipeUtil.matchesRecipe` don't work well together

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#1942]
In arcs-live:
- accept `Show products from your browsing context` suggestion
- products list showing, next suggestions are: `check manufacturer info...` and `check shipping... `
- reload the page
- additional suggestion `MuxedProductItem.` shows up - before the reload it was recognized as "already active" by `RecipeUtil.matchesRecipe(this._arc._activeRecipe, plan)` in https://github.com/PolymerLabs/arcs/blob/master/runtime/planner.js#L136

**Comment by mmandlis** [comment]
BEFORE SERIALIZATION
arc._activeRecipe.toString() is
```
recipe
  use '!372427057411742:app-shell-crov48udg84xr48u:27' #shoplist as handle0 // [Product Thing {...}]
  use '!372427057411742:app-shell-crov48udg84xr48u:29' as handle1 // HostedParticleShape
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:22' as slot0
  slot 'rootslotid-root' #root as slot1
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:23' as slot2
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:24' as slot3
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:25' as slot4
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:26' as slot5
  ItemMultiplexer as particle0
    hostedParticle = handle1
    list <- handle0
    consume item as slot0
  List as particle1
    items <- handle0
    consume root as slot1
      provide item as slot0
      provide action as slot2
      provide annotation as slot3
      provide postamble as slot4
      provide preamble as slot5
  description `show ${List.items}`

The plan that is being recognized as duplicate is:
```
recipe MuxedProductItem &muxProduct
  use '!372427057411742:app-shell-crov48udg84xr48u:27' as handle0 // [Product Thing {...}]
  copy '!372427057411742:app-shell-crov48udg84xr48u:particle-literal:ShowProduct' as handle1 // HostedParticleShape
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:22' as slot0
  ItemMultiplexer as particle0
    hostedParticle = handle1
    list <- handle0
    consume item as slot0
```

**Comment by mmandlis** [comment]
AFTER DESERIALIZATION:
Active recipe is:
```
recipe
  use '!372427057411742:app-shell-crov48udg84xr48u:27' #shoplist as handle0 // [Product Thing {...}]
  use '!372427057411742:app-shell-crov48udg84xr48u:29' as handle1 // HostedParticleShape
  slot 'slotid-!38112248231063:app-shell-crov48udg84xr48u:1' as slot0
  slot 'rootslotid-root' #root as slot1
  slot 'slotid-!38112248231063:app-shell-crov48udg84xr48u:2' as slot2
  slot 'slotid-!38112248231063:app-shell-crov48udg84xr48u:3' as slot3
  slot 'slotid-!38112248231063:app-shell-crov48udg84xr48u:4' as slot4
  slot 'slotid-!38112248231063:app-shell-crov48udg84xr48u:5' as slot5
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:22' as slot6
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:23' as slot7
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:24' as slot8
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:25' as slot9
  slot 'slotid-!372427057411742:app-shell-crov48udg84xr48u:26' as slot10
  ItemMultiplexer as particle0
    hostedParticle = handle1
    list <- handle0
    consume item as slot0
  List as particle1
    items <- handle0
    consume root as slot1
      provide item as slot0
      provide action as slot2
      provide annotation as slot3
      provide postamble as slot4
      provide preamble as slot5
  description `show ${List.items}`
```
The suggestion (NOT recognized as already active):
```
recipe MuxedProductItem &muxProduct
  use '!372427057411742:app-shell-crov48udg84xr48u:27' as handle0 // [Product Thing {...}]
  copy '!372427057411742:app-shell-crov48udg84xr48u:particle-literal:ShowProduct' as handle1 // HostedParticleShape
  slot 'slotid-!38112248231063:app-shell-crov48udg84xr48u:1' as slot0
  ItemMultiplexer as particle0
    hostedParticle = handle1
    list <- handle0
    consume item as slot0
```

**Comment by mmandlis** [comment]
NOTE: after deserialization, the active recipe has twice as much slots. The "second" set of slots has the same IDs as the originally existing slots, but they aren't connected to particles. Instead the "first" set of slots (with the new IDs) is consumed and provided.

**Comment by shans** [comment]
It's normalization which is causing the problem. Specifically, before normalization on line 270ish in arc.js (just before instantiation, inside serialization) there's 1 copy of the slots; after there's 2 (but it's hidden because the second copy doesn't have IDs so only the old copy shows up in a .toString()).

I suspect this is something to do with how slots normalize?

**Comment by mmandlis** [comment]
actually, it is the deserialization. The `serialization` string passed to `arc.deserialize` is:
```
@active
recipe
  use '!1035761311285223:app-shell-dsf159iezm088n5c:22' #shoplist as handle0 // [Product Thing {...}]
  use '!1035761311285223:app-shell-dsf159iezm088n5c:24' as handle1 // HostedParticleShape
  slot 'slotid-!1035761311285223:app-shell-dsf159iezm088n5c:17' as slot0
  slot 'rootslotid-root' #root as slot1
  slot 'slotid-!1035761311285223:app-shell-dsf159iezm088n5c:18' as slot2
  slot 'slotid-!1035761311285223:app-shell-dsf159iezm088n5c:19' as slot3
  slot 'slotid-!1035761311285223:app-shell-dsf159iezm088n5c:20' as slot4
  slot 'slotid-!1035761311285223:app-shell-dsf159iezm088n5c:21' as slot5
  ItemMultiplexer as particle0
    hostedParticle = handle1
    list <- handle0
    consume item as slot0
  List as particle1
    items <- handle0
    consume root as slot1
      provide item as slot0
...
```

The extra slots are added during the manifest parsing. Actually this is exactly what I fixed here:
https://github.com/PolymerLabs/arcs/pull/1940/files#diff-7cf67f07396d399da8d0403d5df1dc2bR773
but I thought this is a problem I was introducing by adding IDs to local slots, but in fact this problem is already here.

**Comment by shans** [comment]
Yes, it's deserialization, but that's not the full picture. No, it's nothing to do with parsing. It's happening during the normalization step inside deserialization.

If I console.log recipe.toString() immediately before https://github.com/PolymerLabs/arcs/blob/master/runtime/arc.js#L271 then it still looks basically like what you have above.

If I console.log the same thing immediate after that line, then slot0->slot6, slot2->slot7, ... but not in the actual particle mappings .. i.e. normalization duplicated the slots.

**Comment by shans** [comment]
Hmm, though your fix disagrees with that. Is the parsing creating duplicate slots with the same ID, which are just renamed during normalization?

**Comment by mmandlis** [comment]
the fix was pushed and the extra slots are gone.
but the problems remain - after deserialization:
1) `check manufacturer information` suggestion still suggested after it was accepted (is not recognized as active)
2) `MuxedProductItem` suggestion appears
