### ISSUE TITLE
TV demo lets you mark which shows you are watching and see who else is watching them as well

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#1980]

**Comment by seefeldb** [comment]
Also, annotate shows on lists (including recommendations and recents, see #1982) with whether they have friends watching

**Comment by sjmiles** [comment]
Done
* Shows can be favorited by clicking the heart icon on either search results or recommended lists.
* Suggestions and Show Detail should now show friends that have favorited the selected show (and shared the relevant Arc).
Not Done
* Shows in lists don't yet show who else is watching
* There is no way to un-favorite a show

**Comment by sjmiles** [comment]
Stale, closing.
