### ISSUE TITLE
 Cannot read property 'id' of null

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#1998]
```
(node:11304) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at values.map.value (file:///Users/mmandlis/arcs/arcs/runtime/ts-build/storage/in-memory-storage.js:229:35)
    at Array.map (<anonymous>)
    at InMemoryCollection.storeMultiple (file:///Users/mmandlis/arcs/arcs/runtime/ts-build/storage/in-memory-storage.js:225:16)
    at InMemoryVariable.cloneFrom (file:///Users/mmandlis/arcs/arcs/runtime/ts-build/storage/in-memory-storage.js:314:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

The entity in a Person, and the backing store is firebase-storage, and 
```
const underlying = await handle.backingStore.getMultiple(literal.model.map(({id}) => id));
```
in in-memory-storage.ts ln 361 return an array with one element `null`.

@sjmiles I think you were seeing this error too, is it still happening?

**Comment by mykmartin** [comment]
Do you have any repro steps? I'm looking at the code in question now..

**Comment by mmandlis** [comment]
I reproduce it with remote planning.  The exact steps are:
- in arcs-live, create an arc with 'find restaurants near ...'
- run ./serve.sh (under `shell/apps/remote-planning/`) and you get the exception (you can debug it with ./debug.sh)

NOTE: if you want to use user Myk, you need to set a user id in shell/apps/remote-planning/index.js (Myk is `-LMtek9Od_C2Fv1Z_l0-`)

**Comment by mykmartin** [comment]
I tried serve.sh and don't see any errors. It produces two "plans" blocks with lists of (I presume) suggestion texts, and then just sits there.

**Comment by mykmartin** [comment]
It's running with user Cletus.

**Comment by mmandlis** [comment]
Did you create the "restaurants" arc on arcs-live?

I don't have a good explanation, but i think it might have been fixed with https://github.com/PolymerLabs/arcs/pull/2001 - because it only happens for me with arcs that are created on live, but not on the newer version. Let's wait until it gets pushed to verify.

Thanks for looking!

**Comment by mykmartin** [comment]
Dammit, brainfart, didn't do the arcs-live step. :roll_eyes:

**Comment by mmandlis** [comment]
that's the best strategy, possibly, it's already fixed :)

**Comment by mykmartin** [comment]
Guess not, I just got the error

**Comment by mykmartin** [comment]
... or not? Looks like my local changes for the music demo were interfering. Trying to do too many things at once...

**Comment by mmandlis** [comment]
let's leave this for now, and I'll let you know, if this happen again with ToT. sorry for the extra distraction.

**Comment by mmandlis** [comment]
lots and lots of debugging. more or less consistently happening to me with restaurants demo. 
what I found is that during planning, the arc's store holding the Person is changing. 

This is the arc's active recipe:
```
  use '!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:26' as handle0 // GeoCoordinates Thing {...}
  **use '!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:27' as handle1 // Person Thing {...}**
  use '!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:29' #nosync #restaurants as handle2 // [Restaurant Thing {...}]
  use '!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:30' as handle3 // Restaurant Thing {...}
  map 'PROFILE_avatar' as handle4 // [Avatar {...}]
  map 'PROFILE_userName' as handle5 // [UserName {...}]
  map 'SYSTEM_user' as handle6 // User {...}
  slot 'slotid-!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:20' as slot0
  slot 'slotid-!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:21' as slot1
  slot 'slotid-!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:22' as slot2
  slot 'slotid-!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:23' as slot3
  slot 'slotid-!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:24' as slot4
  slot 'slotid-!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:25' as slot5
  slot 'rootslotid-root' #root as slot6
  ExtractLocation as particle0
    location -> handle0
    person <- handle1
  FindRestaurants as particle1
    location <- handle0
    restaurants = handle2
    consume root as slot6
      provide masterdetail as slot5
  RestaurantDetail as particle2
    selected <- handle3
    consume detail as slot0
      provide action as slot1
  RestaurantList as particle3
    list <- handle2
    selected = handle3
    consume master as slot2
      provide annotation as slot3
      provide modifier as slot4
  RestaurantMasterDetail as particle4
    list <- handle2
    selected = handle3
    consume masterdetail as slot5
      provide detail as slot0
      provide master as slot2
  UserPerson as particle5
    avatars <- handle4
    names <- handle5
    person -> handle1
    user <- handle6
```

several `cloneForSpeculative` executions run in parallel, but during the first couple 
store `!315148350750948:-LNXeIzlmfPSZ1_sDXgJ:27` 
has value id `!1055911603951819:-LNXeIzlmfPSZ1_sDXgJ:0:inner:1:0` and this works fine
but at some point it is updated to the next version with value id `!1055911603951819:-LNXeIzlmfPSZ1_sDXgJ:0:inner:1:2` and then the exception is triggered. 

I tried clone a shared speculative arc and to pass that to the speculator to clone from, but it only seemed to help if planning is done for a single arc. 
Also, I don't completely understand why the Person backing store wouldn't have the newer version of the user, so I need someone more knowledgeable to look at it with me... (
