### ISSUE TITLE
Storage `on('change')`: two `add` events, only one expected

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2064]
Given a virginal `store` (freshly created, has no records, using a firebase `storageKey`), then the code below:

```js
store.on('change', info => log('changes', info), this);

await store.remove('xxxxxxx');

await store.store({
  id: 'xxxxxxx',
  rawData: {
    description: 'Phony Arc Meta',
    color: 'red'
  }
}, ['crdt-keys']);
```

produces this console output:
```js
changes {add: Array(1), version: 2, originatorId: null}
changes {originatorId: null, version: 3, add: Array(1), remove: Array(0)}
```

I'm confused as to why there are two `add` records and two version bumps.

**Comment by sjmiles** [comment]
One of the notifications is coming from `store (firebase-storage.js;768)` and the other from `ensureBackingStore.then` (firebase-storage.js;665)`

**Comment by sjmiles** [comment]
Follow up problems: after the above code executes, there is one item in the store. If I remove it, I get **no change event**.

```
store.on('change', info => log('changes', info), this);
await store.remove('xxxxxxx');
```
console output: **none**

There is no event, but the item is removed from the store. At this point if I attempt to add a new record:

```
    store.on('change', info => log('changes', info), this);
    await store.store({
      id: 'xxxxxxx',
      rawData: {
        description: 'Phony Arc Meta',
        color: ['purple', 'blue', 'green'][Math.floor(Math.random()*3)]
      }
    }, [String(Math.random())]);
```

I get this:

```
assert-web.js:11 Uncaught (in promise) Error: cannot add without new keys
    at assert (assert-web.js:11)
    at CrdtCollectionModel.add (crdt-collection-model.js:45)
    at FirebaseCollection.store (firebase-storage.js:764)
```

Note that the `keys` in question are not the keys I passed to `store` but some backingStore (?)  keys (seem to be based on some id).

**Comment by shaper** [comment]
Assigning to @mykmartin over @shans so that there's a single owner (and because 'm' comes before 's' in the alphabet), but feel free to discuss/shuffle subsequently, or put in your queue and let us know what it's behind,

**Comment by shaper** [comment]
Pinging for status update as this is marked P1.

**Comment by mykmartin** [comment]
Can still repro, will track down and kill with fire...base.

**Comment by mykmartin** [comment]
PR 2773 fixes the double event bug. I haven't been able to repro the follow-on problems: remove generates an event and adding another value with the same id works.

**Comment by sjmiles** [comment]
Cool, I think we can close this. I suspect some of this came from Shells using improper ids, or other things we have fixed along the way.
