### ISSUE TITLE
Need Storage support for Arc serializations

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2065]
Modern runtime Arcs maintain data-stores via Storage abstractions, but we need support for persisting serializations. Otherwise, Shell is forced to persist serializations using Firebase hardcodes.

At the minimum, this could be solved with a synthetic-store that could read/write/observe an Arc's serialization. Sooner or later, I suspect we will want an Arc to manage it's serialization transparently.

**Comment by mykmartin** [comment]
Adding Raul; sounds like a runtime-API-shaped request :)

**Comment by shaper** [comment]
@shans to comment, this is blocking @sjmiles new shell work which has follow-on impact to @mmandlis planificator work and how we approach ongoing demo activities.

**Comment by mykmartin** [comment]
@sjmiles What do we need to do to unblock this? In the long run I imagine it'll just be a method in the runtime API, but we obviously need something before that's ready.

One option is to set up a 'serializations' space in the top-level firebase structure (a la backingStores), then provide an interface to access that based on arc ids. The shell would still need to have the top-level storage key, but I think that's always going to be the case, right?

**Comment by shans** [comment]
serialized Arcs should eventually be a stored type (i.e. rather than a method in the runtime API, it's just a store at a particular storage location (storageKey)). This will at some point require type system support but in the short term we can do the same thing as we're doing for handles.

Eventually we'll try to map deltas (new recipes to instantiate) into some kind of CRDT thingo, but that's a ways off.

**Comment by mykmartin** [comment]
> it's just a store at a particular storage location (storageKey)

Isn't that part of the problem Scott's raised?

> Shell is forced to persist serializations using Firebase hardcodes.

**Comment by shans** [comment]
No, "Firebase hardcodes" is what happens when you can't use the storage system for some reason. In this case it's because the current storage layout doesn't match what's expected of a variable.

**Comment by mykmartin** [comment]
Ok. So what do we need to do to unblock the current state in the short term?

**Comment by shans** [comment]
Scott could just start reading/storing manifests through a Store; the only problem here is that it's not backwards compatible, so existing arcs would stop working.

**Comment by shans** [comment]
Another option would be to build a synthetic store that converted between representations; though this could be tricky wrt writing new values.

**Comment by sjmiles** [comment]
To rewind a little ... 

Stores automatically persist themselves, I guess I assumed Arcs would do the same thing. The Arc itself best knows when it's serialization has changed, and it knows how to marshal the needed Storage objects.

Seems that's not what you guys are considering, can you explain what the advantage is to leaving this work to the outer process (aka Shell)?

**Comment by sjmiles** [comment]
> Scott could just start reading/storing manifests through a Store; 

I'll give this a try, but I still am curious about my question above.

> the only problem here is that it's not backwards compatible, so existing arcs would stop working.

This is not a problem, nobody has any _important arcs_.

**Comment by sjmiles** [comment]
I can create a `serialization` store in an Arc, but ironically, it doesn't appear in the serialization because it's not employed by the active recipe. 

Since it's not ultimately in the serialization, (1) it cannot be recreated (there is a check that disallows creating a store if there is already a matching firebase-node, which enforces that dangling stores remain dangling) and (2) the data (serialization itself) doesn't persist.

**Comment by shans** [comment]
Quick summary of discussion with Scott: arc serialization/deserialization to stores should be under control of the runtime, perhaps with a basic override mechanism that's accessible to the shell.

**Comment by sjmiles** [comment]
Note: I removed `blocker` as currently all `p1` are considered blockers unless they have `non-blocker` label. Sounds dumb as I write it, but it actually reduces the total number of labels.

**Comment by shaper** [comment]
It's my understanding @mykmartin is actively working on this per chat discussion, just checking since there's no update on the issue here. @sjmiles are you aware of what's in flight or would you like a summary of what's planned, done, yet-to-come from @mykmartin?

**Comment by mykmartin** [comment]
Yep, CL is about to go for review now.

**Comment by sjmiles** [comment]
This is fixed by #2347 and #2351.

Shell no longer depends on Firebase, there is much rejoicing!

There are a few p2 cleanup tasks, but we'll handle those separately.
