### ISSUE TITLE
Error: cannot add without new keys (0_6_0)

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2096]
```
assert-web.js:11 Uncaught (in promise) Error: cannot add without new keys
    at assert (assert-web.js:11)
    at CrdtCollectionModel.add (crdt-collection-model.js:45)
    at FirebaseCollection.store (firebase-storage.js:764)
```

Repro: 

1. open shell (`shell_0_6_0/web-shell/`, doesn't work in Live right now [will fix])
2. toggle favorite (star) for an Arc in launcher
3. repeat until error appears (usually right away, but sometimes takes two tries for me)

**Comment by shaper** [comment]
@shans to comment, this is blocking @sjmiles new shell work which has follow-on impact to @mmandlis planificator work and how we approach ongoing demo activities.
