### ISSUE TITLE
Feature request: optional handle connections

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2104]
Sometimes Particles can use information if it's available, but do not require it. 

For example, `BOXED` data is only sometimes available depending on the user's friend structure. 

Today the shell forces certain well known stores into existence so common recipes will resolve regardless of whether those stores have actual content. However, the class of shareable types is unbounded, so this solution is only a stopgap.

I can imagine optionality support limited to read-only handles, if that helps.

As of today, I believe Particles could deal equally well with being provided no handle, or an empty handle, for a non-resolved optional connection. The former is detectable by the Particle, I could argue both sides of whether that's desirable.

**Comment by seefeldb** [comment]
Related:
* Should we support default values?
* What happens if that optional handle appears during the runtime (BOXED_: user makes a friend, but also otherwise when e.g. a new suggestion is accepted)

**Comment by shans** [comment]
handles can currently be marked as optional during parsing:
```
particle Foo in 'bar.js'
  in Entity? optionalInput
  out [Entity]? optionalOutput
```

We probably haven't rolled this through the stack completely though. I can start to look at improving this support after tech debt burndown?

**Comment by mmandlis** [comment]
Last time I checked, such recipes would resolve, but fire an assert, if instantiated. But strategies have changed a lot since, so probably won't even resolve.

**Comment by Cypher1** [comment]
https://github.com/PolymerLabs/arcs/pull/2255

**Comment by shaper** [comment]
This may be P2, I'm marking P1 as @sjmiles has it on his tracking issue https://github.com/PolymerLabs/arcs/issues/2262, but if it's not actually blocking landing shell 0_6_0 then it's probably P2.

**Comment by raulverag** [comment]
I think this is a language/architecture feature and only incidentally an API feature, so I'm removing myself as an assignee. Per the issues policy, this should really have only one assignee, who will be responsible for making the feature decision. Then the bug can be reassigned if someone else will implement.

**Comment by sjmiles** [comment]
@Cypher1 I'm not sure what is unclear from my original description, I'm afraid I'm going to repeat myself, so please let me know what part is unclear.

Today, if a handle is specified in any way in a Particle manifest, a matching handle must exist somewhere in the recipe for it to resolve. 

However, there are some Particles that do not _require_ a handle, but can take advantage of said handle if it exists. Today this leads to proliferating manifests, one for permutation of optional and required handles, which is long term untenable.

If we could mark handles as optional (existentially, not directionally) we could avoid forking manifests.

**Comment by sjmiles** [comment]
Permission to revise and extend my remarks!

Actually how I'm solving the optional-handle problem today is not by writing permuted manifests (this is really not manageable even now) but by forcing various stores to exist in context a-priori.

This is a bit nasty: the code is involved and it creates various timing problems. I would be very happy to do away with it. I think I will qualify this issue as `p1` but `non-blocking`.

**Comment by Cypher1** [comment]
Updating assignment to reflect that I'm working on this at the moment.
I'm leaving @shans also assigned as I'm only 20% and anything urgent might have to go through him.

**Comment by Cypher1** [comment]
I'm working on some tests (that I don't intend to add at the moment) to work out where the gaps are in the functionality of the '?' syntax.

Currently this is only for handles, but I intend to ensure that the same works for slot-handles (slandles).
https://github.com/PolymerLabs/arcs/pull/2387

**Comment by shaper** [comment]
Pinging for status update as this is marked P1.

**Comment by mmandlis** [comment]
FYI https://github.com/PolymerLabs/arcs/pull/2644 (WIP) is not directly related, but is a step in the same direction and makes the optional handle connections support somewhat easier (i think).

**Comment by shaper** [comment]
The shell blocking issue was closed, this seems more like a P2 given discussion, but @sjmiles feel free to discuss importance and we can move back to P1 if appropriate.

**Comment by sjmiles** [comment]
This is important to me because the workaround is to make recipe permutations which are a hassle to maintain. I don't know how that stacks up priority-wise against other workstreams.

**Comment by Cypher1** [comment]
Very much agree, we have been working on this. I believe the runtime has support for optional handles now (as of https://github.com/PolymerLabs/arcs/pull/2737) but the strategizer may not be able to select Particles without fulfilling their optional handles.

@piotrswigon are you able to look into this in the Stragegizer or is there further runtime work to be completed?

**Comment by shans** [comment]
There's a potential further issue, even after the Strategizer supports this: given an optional handle connection, and a handle that matches in type, both the variant of the recipe that connects one to the other and the variant that does not are valid.

This means we'll probably end up with both versions in our list of suggestions. Not sure what best to do about that short-term; but long-term I think we have some reasonable ideas.

**Comment by piotrswigon** [comment]
I verified everything works end-to-end with a following recipe:

```
schema Thingy
  Text abc

particle Particle in 'source/Particle.js'
  consume detail
  in? Thingy abc

recipe With
  map #things as things
  slot 'rootslotid-root' as slot0
  Particle
    consume detail as slot0
    abc = things
  description `With optional connection`

recipe Without
  slot 'rootslotid-root' as slot0
  Particle
    consume detail as slot0
  description `Without optional connection`

store ThingyStore of Thingy #things in ThingyStoreRes
resource ThingyStoreRes
    start
    [{"abc": "abc"}]
```

particle code is:
```
defineParticle(({DomParticle}) => {
  return class extends DomParticle {
    get template() {
      return '<div>Render</div>';
    }
    async setHandles(handles) {
      super.setHandles(handles);
      console.log(handles);
    }
  };
});
```

Both recipes are resolved and showing up as suggestions. `setHandles(...)` correctly gets invoked with a single-handle or an empty map respectively.

No errors are reported anywhere.

This is obviously a trivial example, @sjmiles if you do find issues let us know.

**Comment by piotrswigon** [comment]
Closing this issue for now, as it appears to work.
