### ISSUE TITLE
HostedParticleShapes only resolve against context

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2105]
`hostedParticle` assignments only work if the Particle is defined in the `arc.context` (and not simply inline). Until recently we loaded (almost) all recipes into context by default, masking this issue.

For example, given:

```
import '../List/List.recipes'
import './Playlist.schema'

particle PlaylistItem in 'source/PlaylistItem.js'
  in Playlist playlist
  consume item

recipe PlaylistView
  map #items as items
  create #selected as selected
  ItemMultiplexer
    list = items
    hostedParticle = PlaylistItem
  SelectableItems
    list = items
    selected = selected
```

The system throws like so:

```
Error: Cannot find store manifest:https://$artifacts/Music/Playlist.recipe::0:b42c142249cd1b94df045af5493837c93f2fb2c1:PlaylistItem
    at assert (assert-web.js:11)
    at Arc.instantiate (arc.js:442)
```

If `PlaylistItem` particle is defined in `arc.context` then the `HostedParticleShape` is used from there, and the recipe resolves normally.

**Comment by piotrswigon** [comment]
I will take a stab at this. Removing others from Assignees.

**Comment by piotrswigon** [comment]
@sjmiles Can you confirm if this is fixed? The entire mechanism for hosted particle serialization is revamped, so I think this should no longer happen, but do let me know if there are still problems.
