### ISSUE TITLE
StorageStub in arc context's allStores

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2141]
The `playlists` store https://github.com/PolymerLabs/arcs/blob/556734262d343605be2400e639f1c9986c025cc6/artifacts/Music/Music.recipes#L17 appears as StorageStub in arc's context and never inflated.
(This is a BigCollection fwiw)

**Comment by mmandlis** [comment]
@mykmartin can this be considered fixed? i see with the recent changes all the `// #2141: ...` comments are gone.

**Comment by mykmartin** [comment]
I'm not sure what to do with this; it's bit-rotted somewhat. It's using a hard-coded storage location that no longer exists, and the original purpose of the file was the M1 milestone when we were moving PAs. I guess it's still useful as an example.

That said, the StorageStub machinery is going to change with Shane's refactor, so this issue will be rendered moot.
