### ISSUE TITLE
with pouch, planner doesn't seem to see in-arc handles

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#2180]
(this is based on the recent version, not yet using cloud planning!)

repro:
 - new arc with "restaurants" (pick the one without reservations or calendar, just restaurants search)
 - expected: see a suggestion pop up for making reservations
 - actual: suggestion doesn't appear, not even in '*'
 - actual: but interestingly, reservations suggestions together with another restaurant search does appear, just not standalone applying to the current search

looking into strategizer with the devtools, i see that the only paths that produce something involve the coalescer. my suspicion is therefore that the planner/strategizer doesn't see the pouch based handles in the current arc.

**Comment by lindner** [comment]
I'm looking into this.

Which user?

For Paul: I see unresolved handles, but I also don't have a favorite food set.
For Cletus: I see errors  with crdt duplicate keys and no suggestions.

**Comment by seefeldb** [comment]
For user Berni, but you don't need favorite food set for reservations to show up. Reservations should work for all users.

Favorite food would trigger another suggestion (".. has your favorite food ...").

**Comment by lindner** [comment]
I am able to observe firebase getting the 'Table for 2' recommendation when selecting a restaurant.

Using pouchDb does not show this recommendation.
Using planificator=new 

So Firebase may have the same issue under some circumstances.

**Comment by lindner** [comment]
I have not yet been able to solve this.  I have some interim fixes that do not resolve this, but will continue trying for the next few hours.

**Comment by lindner** [comment]
It's now working in my current environment that contains the planner changes and some other cleanups.  I'm not sure it's worth bisecting to find out why..

**Comment by lindner** [comment]
<img width="445" alt="screen shot 2018-11-06 at 5 52 14 pm" src="https://user-images.githubusercontent.com/96715/48105623-14f68880-e1ed-11e8-93e9-8aa0e948fd56.png">

**Comment by lindner** [comment]
Not reproducable.
