### ISSUE TITLE
Consolidate or document all special Shell Query Params

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2207]
We've started adding a number of query params that change Shell behavior.  Let's consider consolidating them in an options object or at least write some documentation on them.

**Comment by sjmiles** [comment]
So, fwiw, these have historically been documented in the shell/ [README](https://github.com/PolymerLabs/arcs/blob/master/shell/README.md).

That file needs updating. Should maybe be part of Sherrif's duties? Without a QA person, this kind of information is doomed to degrade.

Also, just FYI, option processing is intended to be collated into

[arc-config.js](https://github.com/PolymerLabs/arcs/blob/master/shell/app-shell/elements/arc-config.js)

or for 0_6_0, in

[web-config.js](https://github.com/PolymerLabs/arcs/blob/master/shell_0_6_0/web-shell/elements/web-config.js)

There is an exception for _pass-through_ options, like `debug=` which is processed by the Xen library (the only one I can think of atm).

**Comment by shaper** [comment]
https://github.com/PolymerLabs/arcs/tree/master/shells/web-shell
