### ISSUE TITLE
'Pipes receives' test failing on Travis, master

### ISSUE THREAD

**Issue by Cypher1** [PolymerLabs/arcs#2220]
Travis is failing with
```
[chrome #0-0] timedout waiting for "[title^="Bodyguard is on BBC One"]"
```
The relevant test seems to have been added in #2198.

I'm wondering if we can turn off the tests for a bit or have a fix?
The tests seem to pass on AppVeyor and locally, so it seems likely that this is a platform / setup dependency.

**Comment by sjmiles** [comment]
> why such high timeouts, why so slow?

My best understanding is that the runtime code that manages `backingStores` is pathological today: it creates numerous duplicate entries, and the entire corpus needs to be read into RAM from remote storage (more than once?).
