### ISSUE TITLE
Improving use of Travis

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2239]
Without Travis running a solid battery of integration tests, we tend to pile up low-level errors that affect the Shell but aren't visible in runtime tests.

This issue to is help us tracking problems we have encountered using Travis:

1. The `npm run test-with-start` doesn't work on my Windows machine (neither for @shans IIRC).
2. I (@sjmiles) tend to have local test success but failures in remote Travis. I haven't found a good way to debug/scope what's happening remotely. In theory, one can mimic the remote Travis build environment (e.g. under Docker), but I haven't been able to make that work.

**Comment by sjmiles** [comment]
Most recent problems with Travis occurred when I pushed tests for the `pipes` sub-system. These changes borked the build and were reverted.

#2238 is a PR I built with almost the same changes, plus some robustness tweaks (and quadrupled timeouts). The PR itself passes the Travis build test preview, but it did last time too. I'm not sure what happens between here and being pulled into main.

Re: crazy timeouts: my latest understanding from runtime team is that we are still suffering from pathological treatment of `backingStores`. IIUC, that corpus of objects is heavily redundant and also is read in it's entirety into RAM from remote-storage (more than once?).

**Comment by sjmiles** [comment]
More notes re: #2238

- when I first pushed these tests, only the pipes::receives test was failing on remote travis, this has never been explained
- @lindner reported errors about `receiveEntity` that I believe was due to the page not spinning up before the test poked it (racing), I've added some waitFor to address this
- errors around `#webtest-title` (Restaurants) were due to expired certs on the remote service server (these are now updated)

**Comment by sjmiles** [comment]
Making another attempt at Selenium tests with #2262.

Timeouts are increased dramatically, added some robustness.

**Comment by shaper** [comment]
Considered making this P1. Open to thoughts. Since we've done some work, feels like we can wait a bit and see, perhaps.

**Comment by lindner** [comment]
I think we're in better shape these days.

At this point I think it might be worthwhile investing in Cloud Build:

go/travis-to-cloudbuild

**Comment by sjmiles** [comment]
Stale, closing for now.
