### ISSUE TITLE
'Failed to parse suggestion: Parse error' in suggestion.js 

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2273]
From invoking `shell_0_6_0/web-shell/` (doesn't reproduce on`arcs-live` right now, sorry)

![image](https://user-images.githubusercontent.com/98045/48864524-a800f800-ed81-11e8-894e-fef891f0a085.png)

**Comment by mmandlis** [comment]
search in recipe fails to deserialize, for example, the following recipe:
```
recipe
  search `show video foo`
    tokens `foo` // `show` `video`
  create #ctrl as handle0 // [VideoControls Thing {...}]
  slot 'rootslotid-root' #root as slot0
  ControlVideo as particle0
    controls = handle0
    consume root as slot0
  ShowVideo as particle1
    controls <- handle0
    consume root as slot0
```
fails with: "Error: Parse error in '' line 4.
Expected " ", "//", "@", "\n", "\r", "alias", "import", "meta", "particle", "recipe", "resource", "schema", "shape", "store", or [ ] but "c" found.
    create #ctrl as handle0 // [VideoControls Thing {...}]"

To reproduce in arcs-live: type `show video foo` in the search bar.

@Cypher1 I think this was introduced in one of the more recent manifest changes.
@sjmiles I'm going to change the way search is stored in recipes and suggestions, so unless this is really blocking you, maybe not worth fixing for now.

**Comment by mmandlis** [comment]
This should be fixed with https://github.com/PolymerLabs/arcs/pull/2297. Please, reopen, if you see it again.
