### ISSUE TITLE
'Failed to parse suggestion: can't resolve plan' in suggestion.js

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2274]
From invoking `shell_0_6_0/web-shell/` (doesn't reproduce on`arcs-live` right now, sorry)

![image](https://user-images.githubusercontent.com/98045/48865013-1b573980-ed83-11e8-986d-e8b41ac16385.png)

**Comment by piotrswigon** [comment]
@mmandlis did you do any exploration of why this happens? If no, that's fine, will take a look soon.

**Comment by mmandlis** [comment]
I believe this is the second of the two problems I emailed you about yesterday - where the handle's type is determined by the hosted particle (ReservationAnnotation in this case), but the hosted particle spec is in the store and not available at manifest parsing time. 
I attempted a fix in https://github.com/PolymerLabs/arcs/pull/2212, but then shans@ and I discussed and agreed that instead we should serialize with the restricted store type instead.

**Comment by piotrswigon** [comment]
@sjmiles I assume this is a P1, please correct me if I'm wrong.

**Comment by piotrswigon** [comment]
If @mmandlis is right then this should be fixed. Can we try to reproduce it? If it still happens I will happily explore what's going on.

**Comment by sjmiles** [comment]
Looks like it's fixed, thanks!
