### ISSUE TITLE
Dev Extension Error 

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2305]
![image](https://user-images.githubusercontent.com/98045/49043413-d74ba680-f17f-11e8-8d11-daa6b97043af.png)

This is on my Windows machine (loading arcs-live).

**Comment by piotrswigon** [comment]
Bizarre, this codepath should not execute when ArcsExplorer runs as an extension against a page.

Could you add following lines at the top of devtools/src/devtools.js:
```
  console.log('chrome.devtools: ', chrome.devtools);
  console.log('chrome.devtools.inspectedWindow: ', chrome.devtools.inspectedWindow);
  console.log('chrome.devtools.inspectedWindow.tabId:', chrome.devtools.inspectedWindow.tabId);
```
And then let me know what you see in the extension console (right click somewhere in arcs explorer and select 'inspect')?

**Comment by sjmiles** [comment]
It looks like the bug I posted is transient, but dev tools is still not appearing. This is the more common error:

![image](https://user-images.githubusercontent.com/98045/49048641-58129e80-f190-11e8-95f8-2db91b0c15cd.png)

**Comment by sjmiles** [comment]
For completeness I added the logs you requested. Here is the console output:

![image](https://user-images.githubusercontent.com/98045/49048850-3bc33180-f191-11e8-8c82-f4ef84bfe024.png)

**Comment by sjmiles** [comment]
I also failed to mention that the result is that Strategy Explorer is blank, other tools seem to be mostly working.

**Comment by piotrswigon** [comment]
Ah, cool, I do see that SE is blank. That may be related to @mmandlis changes to how we serialize generations from remote planning, I will investigate now and try to fix ASAP.

**Comment by piotrswigon** [comment]
I found we now need to have `?planificatorDebug=true` in the URL for the plan producer to write generations to show to strategy explorer.

**Comment by piotrswigon** [comment]
@mmandlis WDYT about peeking at the state of DevTools connection to decide whether to write generations in Firebase? For remote planning it will always says no (for now), but for the local plan production it will free us from using the `?planificatorDebug=true` in the URL.

I would prefer it, as the URL param is not very discoverable. @sjmiles opinions?

**Comment by mmandlis** [comment]
I'll send a PR shortly

**Comment by sjmiles** [comment]
Thanks for the information. We should definitely automate this wherever we can. 

Are the generations particularly costly to transcribe?

**Comment by sjmiles** [comment]
Fwiw, when I run with `?planificatorDebug=true` the StrategyExplorer shows some information briefly, then it gets cleared right away. 

It's likely I'm doing something wrong, but I still cannot use the tool for debugging.

**Comment by mmandlis** [comment]
created: https://github.com/PolymerLabs/arcs/pull/2315

**Comment by sjmiles** [comment]
Largely fixed. There is an ongoing question about serving the DevTools from non-volatile environments.

@mmandlis still would like an answer to:
> Are the generations particularly costly to transcribe?

**Comment by mmandlis** [comment]
> @mmandlis still would like an answer to:
> 
> > Are the generations particularly costly to transcribe?

It is possible to enable storing the `generations` in non-volatile environments (by passing a `debug=true` to the planificator::create method). It is just that they are significantly larger than planner results otherwise, so we felt it is wrong to enable it by default.

**Comment by sjmiles** [comment]
Ok, thanks info!
