### ISSUE TITLE
Implement PouchDB-based BigCollection

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2326]
For parity with Firebase support the BigCollection APIs.

**Comment by shaper** [comment]
@lindner do you already know what we need to do here, or do you need to sync with @mykmartin? I know there were some design/approach issues that he discovered when doing the Firebase implementation so I thought worth checkpoint here as well to ensure you get his input soon if needed.

**Comment by shaper** [comment]
Ping on above, holidays are nigh, if we want input from @mykmartin we'd likely need to talk today/tomorrow.

**Comment by shaper** [comment]
Pinging for status update as this is marked P1.

**Comment by lindner** [comment]
Closing this as it will need to be rethought for storage refactor.
