### ISSUE TITLE
Verify that PouchDb implements event triggering correctly.

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2327]
The Firebase event triggers are implemented in a different way than the Pouch version.

Audit code for each event emitter and verify that Pouch does the same thing under the same conditions.

**Comment by shaper** [comment]
Checking status here, I know we discussed a bit in person and you'd found some differences between Firebase events and Pouch, and were going to (1) get Pouch to behave like Firebase, and (2) talk with @mykmartin, but this is just my from-memory (and I may be mixing issues).

**Comment by lindner** [comment]
Would prefer to add _fire() testing, but have not gotten there quite yet.  The Volatile and Firebase tests are still stuck in non-typescript land, so that still makes it difficult to mock.

[There's a reason I was spending so much time converting to typescript!]

That said this is manually verified across all code paths.  There was one cloneFrom call that needed updating, plus the version number handling was needed for proper triggering and that's in too.
