### ISSUE TITLE
Exceptions from firebase-storage.js (0_6_0)

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2330]
Should appear directly after opening https://polymerlabs.github.io/arcs-live/shell_0_6_0/web-shell/

These errors seems to be modulating over time, I'll try to keep the issues up to date.

![image](https://user-images.githubusercontent.com/98045/49178437-a0eb6400-f304-11e8-8954-7b7c41c46b60.png)

**Comment by mykmartin** [comment]
I'm seeing similar errors. Will pick this up after finishing up the arc serialisation work, because it's possible that's the underlying cause. Don't worry about updating the bug as the nature of the exceptions change.

**Comment by sjmiles** [comment]
As predicted by Myk, these errors have cleared up after the last several PRs. I'm declaring victory.
