### ISSUE TITLE
slot-dom-consumer.ts:253 Slot root has unexpected inner slot (0_6_0)

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2332]
Repro:

1. open https://polymerlabs.github.io/arcs-live/shell_0_6_0/web-shell/
2. type 'restaurant' in search
3. choose '[demo] find rest...'
4. return to launcher
5. choose '[demo] find rest...' a second time

Should produce numerous `unexpected inner slot` warnings.

**Comment by piotrswigon** [comment]
This fix is on me. The problem is caused by having slot IDs in the template since #2228 - thanks @mmandlis for figuring this out.
