### ISSUE TITLE
UI infrastructure introduces hidden dependency on DomParticle

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#2341]
ParticleExecutionContext assumes that Particles have all of these methods, because there's no way to tell whether a particle is actually a DomParticle or not.

In fact, these methods should all be provided on Particle directly, because you shouldn't have to use DomParticle to do rendering.

onInnerArcRender calls renderHostedSlot
onUIEvent calls fireEvent
onStartRender calls renderSlot and uses _slotByName
onStopRender uses _slotByName and name

**Comment by mmandlis** [comment]
- `_slotByName` - data member of Particle is protected, should be made public.
- `fireEvent`, `renderSlot`, `renderHostedSlot` - add empty methods in class Particle
