### ISSUE TITLE
Planificator fails when configured with `?plannerStorageKeyBase=firebase`

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2360]
The error happens https://github.com/PolymerLabs/arcs/blob/master/runtime/ts/plan/planificator.ts#L157

storage-provider-factory.js:25 Uncaught (in promise) Error: unknown storage protocol: firebase/dummylocation
    at StorageProviderFactory.getInstance (storage-provider-factory.js:25)
    at StorageProviderFactory._storageForKey (storage-provider-factory.js:33)
    at StorageProviderFactory.parseStringAsKey (storage-provider-factory.js:61)
    at Function._initSuggestStore (planificator.js:114)
    at Function.create (planificator.js:39)
    at HTMLElement._createPlanificator (arc-planner.js:72)
    at HTMLElement._willReceiveProps (arc-planner.js:50)

**Comment by mmandlis** [comment]
I tried to work around this by setting the storageKeyBase to `firebase:/`, but with firebase it also has to end with '.firebaseio.com'
https://github.com/PolymerLabs/arcs/blob/5550c422cc21b16f32334da3ce79d7ea4789fafb/runtime/ts/storage/firebase-storage.ts#L54
so this kind of solution won't work. Probably still need some DB specific key handling here, WDYT?

**Comment by lindner** [comment]
Are you specifying a storageKeyBase for firebase?  I have not attempted that and instead rely on the Arc storageKey.

I'll look in a few minutes.

**Comment by mmandlis** [comment]
Similar problem is with remote-planning, where I must specify the storageKey:
https://github.com/PolymerLabs/arcs/blob/12b3ecb3722d8e3bd221db4c55b97610eb3876dc/shell/apps/remote-planning/interface.js#L33

**Comment by lindner** [comment]
Aha, the code needs to default to launcher arc storageKeyBase if not specified.  Some of the explicit checks were removed, but not all.

**Comment by lindner** [comment]
We will fix this with better documentation.
