### ISSUE TITLE
improve search string user experience 

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2401]
currently arcs persists the last search string per user, per arc.
some questions needs to be figured out / fixed:
- when should the search string be cleared?
  - when a (searched for) suggestion was accepted?
  - when user leaves the arc?
  - after a certain period of time (expiry)?
while the search string is present, it should be displayed in shell's search input.
- is launcher arc's search treated any differently?

**Comment by sjmiles** [comment]
web-shell has a concept of _focused_ arc, which is the one that:

- is visible in DOM
- renders suggestions into the suggestion ui
- responds to search-text changes

I will modify web-shell to reset the search to '' whenever changing the focused arc.
