### ISSUE TITLE
`storage` and `storageKeyBase` URL params are confusing

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2413]
`storage` is the keyBase indicating where Arcs should be stored
`storageKeyBase` (or equivalent `plannerStorageKeyBase`) is the keyBase indicating where Suggestions should be stored

The name of the params are wrong and confusing.

**Comment by lindner** [comment]
Some options?

 1. config UI that allows you to switch parameters.
 2. Don't allow mixed storageKeys
 3. Write the storageKeyBase to the primary storage storageKeys.  This would allow all config information to be containined in the system itself.  Maybe even consider creating a configuration arc?

**Comment by mmandlis** [comment]
As a very first step I would like to just give the URLs params consistent, intuitive and unambiguous names.

Right now we support `storage` to define where the arc itself it stored (which also applies to the search strings storage). 
And for plans, to override the default storage (which is same as the arcs storage) we have all three options - `plannerStorage` or `plannerStorageKeyBase` or `storageKeyBase` to (https://github.com/PolymerLabs/arcs/blob/7fba9377017ef2cc6c504997c21978044b64756e/shells/web-shell/elements/web-config.js#L59).

2 - I talked to @shaper about it and we decided that it's good to support mixed storageKeys - it gives us flexibility and also helps keep us honest using the storage abstraction in a clean way.

**Comment by sjmiles** [comment]
In Shells I standardized the internal names with a `plannerPrefix`, to wit:

- plannerStorage
- plannerDebug
- plannerOnlyConsumer

I support this standard naming as params (plus old ones for backward compatibility):

```
plannerStorage: params.get('plannerStorage') || params.get('plannerStorageKeyBase') || 
    params.get('storageKeyBase'),
plannerDebug: params.get('plannerDebug'),
plannerOnlyConsumer: params.get('plannerOnlyConsumer') || params.get('onlyConsumer') === 'true'
```

Aside: url params (and dom attributes) are _true by existing_ by default, we generally avoid requiring String true (as for `onlyConsumer` above).

**Comment by sjmiles** [comment]
Another aside: IIUC all working storageKeys can be extended with additional path information, so in this sense, all storageKeys are also storageKeyBases. 

Unless there is some specific meaning for the suffix Base, it's simpler to do away with it. Please let me know if I've missed something important.

**Comment by sjmiles** [comment]
re: _it's good to support mixed storageKeys _

Keep in mind that any time we have referenced data (Arc-A is here, Suggestion-A [belongs to Arc-A] is there) we introduce referential-integrity issues. Specifically, if arc A is deleted, who cleans up Suggestion-A? If database node containing Arc-A also parents the associated metadata, we don't have this problem.

Just something to consider from a KISS advocate.

**Comment by mmandlis** [comment]
> re: _it's good to support mixed storageKeys_
> 
> Keep in mind that any time we have referenced data (Arc-A is here, Suggestion-A [belongs to Arc-A] is there) we must contend with referential-integrity. E.g. if arc A is deleted, who cleans up Suggestion-A? If database node containing Arc-A also parents the associated metadata, we don't have this problem.
> 
> Just something to consider from a KISS advocate.

Filed https://github.com/PolymerLabs/arcs/issues/2458 to track deletion of suggestions of deleted arcs (it used to be implemented in the firebase-only version of user-planner).

Closing this one.
