### ISSUE TITLE
Duplicate `TV shows` suggestion

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2445]
Reproducible in arcs-live.

The only difference is, one has `map 'PROFILE_piped-tv_show' as handle11 // [TVMazeShow {...}]` and other has `map 'BOXED_all_piped-all_tv_shows' as handle11 // [TVMazeShow {...}]`

Do we need both suggestions? If so, probably we should tweak the recipe description to include a description of the distinguishing handle (and assign description to the handle).
WDYT?

**Comment by mmandlis** [comment]
TV shows.
recipe TVMazeDemo
  create #found #nosync as handle0 // [TVMazeShow {...}]
  create #nosync #uniquePiped as handle1 // [TVMazeShow {...}]
  create #shows #tiles as handle2 // [~a] // [TVMazeShow {...}]
  create #nosync #selected as handle3 // TVMazeShow {...}
  create #nosync #uniqueProfile as handle4 // [TVMazeShow {...}]
  map 'PROFILE_all_piped-all_tv_shows' as handle5 // [TVMazeShow {...}]
  map 'PROFILE_shows-tiles' as handle6 // [TVMazeShow {...}]
  map 'BOXED_shows-tiles' as handle7 // [TVMazeShow {...}]
  map 'BOXED_userName' as handle8 // [UserName {...}]
  create #nosync as handle9 // [~a] // [Description {...}]
  map 'PROFILE_friends' as handle10 // [User {...}]
  map 'BOXED_all_piped-all_tv_shows' as handle11 // [TVMazeShow {...}]
  map 'SYSTEM_user' as handle12 // User {...}
  create #nosync #watchers as handle13 // [User {...}]
  create #alsoWatch #nosync as handle14 // Text {...}
  create #nosync #query as handle15 // TVMazeQuery {...}
  slot 'rootslotid-modal' #modal as slot5
  slot 'rootslotid-root' #root as slot16
  ActionMultiplexer as particle0
    hostedParticle = TVMazeShowActions
    list <- handle0
    shows <- handle2
    consume action as slot0
  ActionMultiplexer as particle1
    hostedParticle = TVMazeShowActions
    list <- handle1
    shows <- handle2
    consume action as slot1
  DetailSlider as particle2
    selected = handle3
    consume modal as slot5
      provide content as slot2
  SelectableTiles as particle3
    list <- handle0
    selected = handle3
    consume root as slot6
      provide action as slot7
      provide annotation as slot0
      provide tile as slot8
  SelectableTiles as particle4
    list <- handle1
    selected = handle3
    consume root as slot9
      provide action as slot10
      provide annotation as slot1
      provide tile as slot11
  SelectableTiles as particle5
    list <- handle4
    selected = handle3
    consume root as slot12
      provide action as slot13
      provide annotation as slot14
      provide tile as slot15
  TileMultiplexer as particle6
    hostedParticle = TVMazeShowTile
    list <- handle0
    consume tile as slot8
  TileMultiplexer as particle7
    hostedParticle = TVMazeShowTile
    list <- handle1
    consume tile as slot11
  TileMultiplexer as particle8
    hostedParticle = TVMazeShowTile
    list <- handle4
    consume tile as slot15
  TVMazeDeduplicate as particle9
    shows <- handle5
    uniqueShows = handle1
  TVMazeDeduplicate as particle10
    shows <- handle6
    uniqueShows = handle4
  TVMazeDemoShell as particle11
    boxedShows <- handle7
    boxedUserNames <- handle8
    descriptions -> handle9
    foundShows <- handle0
    friends <- handle10
    recentShows <- handle11
    selected = handle3
    user <- handle12
    watcherText -> handle14
    watchers = handle13
    consume root as slot16
      provide recommended as slot9
      provide search as slot6
      provide searchbar as slot17
      provide shows as slot12
  TVMazeSearchBarRoot as particle12
    query -> handle15
    consume root as slot17
  TVMazeSearchShows as particle13
    query <- handle15
    shows = handle0
  TVMazeShowMultiPanel as particle14
    alsoWatch <- handle14
    show <- handle3
    shows <- handle2
    consume content as slot2
      provide action as slot3
      provide items as slot4
  description `${TVMazeDemoShell}`
f8ad93e9322e0450cfb456ef2607223a0bd4b550
```

**Comment by sjmiles** [comment]
I tried to comment out ` map 'PROFILE_piped-tv_show' as pipedShows` and the system put it back (with another option)!

To disable that data, I instead should have replaced it with `create #nosync as pipeShows`, which I did in #2466.

**Comment by sjmiles** [comment]
Stale, closing.
