### ISSUE TITLE
Preventing Coalescence

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2446]
Pipes UX presents a new use case. When we pipe an entity, say `{"type": "tv_show", "name": "star trek"}` the system spins up an Arc to process that entity. 

At this point the Shell is not visible to the user, the goal is be able to provide meaningful suggestions related to that entity. The entity-processing-arc is responsible for those suggestions. 

For the example entity, a suggestion might be `Star Trek is on NBC at 20:30 on Thursday.` which is what we surface to the user. Only after the user chooses that suggestion do we make Shell visible.

The problem today is that the Coalescer will aggressively bind the (non-rendering) EntityProcess recipe to the EntityShow recipe, skipping over the part where we surface the meaningful suggestion.

Normally, this behavior is A Good Thing, as it avoids the user having a blank screen. But in this use case, it's desirable to prevent coalescing.

**Comment by piotrswigon** [comment]
For me to understand better:

Does `Star Trek is on NBC at 20:30 on Thursday.` reflect a non-rendering recipe? What happens when the user selects it? Do we then show up a follow up suggestion that involves rendering?

**Comment by piotrswigon** [comment]
The bottomline - I'm trying to figure out in abstract when non-rendering recipes are OK and when they're not. Clearly not everything needs to show UI. It would be good if we could encode it, even in a very low-fi version.

**Comment by sjmiles** [comment]
`Star Trek is on NBC at 20:30 on Thursday` is a rendering recipe. This is Step Two: render knowledge about Star Trek.

Step One is: gather knowledge about Star Trek. This is the bit that is non-rendering.

The DevicePipe sends a request to find out about Star Trek, triggering Step One.
Then Step Two is offered to the user as a Suggestion (but not executed until the suggestion is chosen).

However, if I use Strategizer to determine the right Recipe for Step One, then today it merges Step One and Step Two, and I never get the in-between Suggestion to surface to the user.

I'm not sure this can be made automatic, I imagine it will be simpler to have some point of control. Perhaps a way to disable coalescer temporarily in a Planner (or Arc).

**Comment by piotrswigon** [comment]
Is below correct?

1. Entity is extracted by AiAi and tunneled to Arcs.
2. Shell creates a new Arc with the Entity.
3. Shell triggers planning for _Knowledge Gathering_ and instantiates found suggestions.
4. Once the arc is idle (Knowledge gathering is done), shell triggers planning for _Knowledge Rendering_.
5. Found suggestions are surfaced to the end user.

The bit I don't get is how do we know which recipes/suggestions are good for knowledge gathering and which for knowledge rendering? Is the first step to check simply which recipes are rendering?

So the flow would be:

1.  Create an Arc with a handle containing the entity.
2. Plan and instantiate all non-rendering suggestions.
3. Plan and surface most highly ranked suggestions to the user.

If this is correct, then we can have a parameter in the planner which would be passed to the instantiated strategies (including the Coalescer) that we're ok with (or even request!) non rendering suggestions. Based on this parameter Coalescer would not coalesce to satisfy 'every suggestions should render something' requirement which it may try to enforce today.

Sounds sensible to me. Do tell me though if I'm missing the point somewhere. 😄

@shans @seefeldb

**Comment by piotrswigon** [comment]
On a second thought I'm not sure of the gathering vs. rendering phases being separate in the long term. Though I'm ok with adding this quickly to enable demoes etc.

This conceptually fits with the speculative execution I think. Fetching and rendering would be performed speculatively, judged, and if relevant surfaced to the user.

We may want non-rendering suggestions to perform actions, e.g. "Notify me when Shameless season 3 is available on Netflix 🔔". That non-rendering suggestion involves alerting the user, so we would know it is not just knowledge gathering, but it shows some cracks in this model.

Just my 2c.

**Comment by sjmiles** [comment]
I'm going to start and the end: I think what I would suggest at first is simply a way to disable coalescer. 

Seems to me the usage is not knowable from the data and/or the recipes, but only from the modality the employing code find itself in.

The flow today is like this:

1. Entity is extracted by AiAi and tunneled to Arcs.
2. Shell creates a new Arc with the Entity. This arc performs Knowledge Gathering straight away (via  e.g. TVShowFind). Since I hardcode this recipe, I avoid coalescer issues.
3. Suggestions are surfaced, one of which will be Knowldege Rendering (e.g. TVShowPanel)

I was experimenting with the flow of tomorrow as so:

1. Entity is extracted by AiAi and tunneled to Arcs.
2. Shell creates a new Arc with the Entity (there always has to be a recipe, not sure what this looks like, it may just be a dummy).
3. Planning occurs, particles that can absorb Entity are determined by Speculative Execution (cannot be done statically, depends on the data inside of Entity).
4. Planner presents the correct recipe for processing Entity, this is instantiated into the Arc (causing Knoweldge Generation).
5. Planning occurs again, these Suggestions are surfaced to the user.

Today, step 4 produces recipes that are colaesced (as described). There is no chance to perform step 5. If I could simply disable coalescer at step 4, my problem would go away.

**Comment by sjmiles** [comment]
I do not request or trigger planning, from my perspective the Planificator does that on it's own schedule. 

I imagine either the Planificator or the Arc interfaces would be the ones to provide `.disableCoalescer = true/false` (or whatever).

**Comment by mmandlis** [comment]
What is "suggestion" was just another type of modality and a particle could simply render to a "suggestion" slot (and not require coalescing)?

**Comment by sjmiles** [comment]
I don't understand how your proposal fits in with what I'm trying to do, can you elaborate?

**Comment by sjmiles** [comment]
Crossing the streams a little, but given that Planning might be happening remotely, it seems like a non-starter to try to reconfigure planing on-the-fly.

My second volley (for MVP) is somehow marking a Recipe as _not-suitable-for-colescing_.

**Comment by piotrswigon** [comment]
FWIW I don't understand why coalescer even triggers here. It thought it only triggers if a recipe cannot be resolved because a handle or slot is missing. Can you point me to the recipe you want to have running for the incoming entity?

**Comment by piotrswigon** [comment]
I'll be away from tomorrow till Monday. If this is pressing you or Maria can remove coalescer from the list of strategies and we can move from there.

**Comment by sjmiles** [comment]
This is not particularly pressing, sorry for any miscommunication.

The system is working today, I just have to hard-code the AiAi entity-types that we support, as we have in the past.

When it dawned on me that I could use Speculative Execution to have pluggable support for arbitrary types, I built an experiment and discovered this problem. 

Bottom line, it's not a p1.

**Comment by sjmiles** [comment]
I'll work on conjuring an example of what I'm calling aggressive coalescing that we can look at together.

I had a different idea of when coalesced was employed, and it sounds like I had bad assumptions. I'll check my results.

**Comment by piotrswigon** [comment]
It is possible coalescer can be too aggressive - there's quite a bit of code there and I don't think I remember all the conditions we discussed and put there.

**Comment by sjmiles** [comment]
Fwiw, was chatting with Berni and he said that architecturally, this should all be done as part of speculative execution.

First, find a particle that has (dynamic) relevance, then coalesce it to produce the final valid suggestions.

This might actually work today, although I think the flow would be different (i.e. it would coalesce stuff first, then remove irrelevant combinations). I will experiment.

**Comment by sjmiles** [comment]
I attempted to arrange this as follows:

1. DeviceClientPipe receives a data object (called an "Entity" unfortunately)
2. Shell constructs a manifest that embeds the data object  as a PipeEntity (today,  just `{Text type, Text Name}`)
3. Particles exist that transform compatible PipeEntity's into other objects. E.g. TVMazeShowPipe can convert PipeEntity (with `type: 'tv_show'`) into `TVMazeShow`. 
4. Pipe particles `must provide content`, so Coalescer find something that consumes `content` (usually a simple renderer).
5. Pipe particles determine compatibility at runtime (during Speculative Execution) and communicate irrelevancy if the types don't match (today, by returning false from `shouldRender`).
6. Planner ultimately surfaces Suggestions that are (a) relevant to the PipeEntity type and (b) render some `content`.

I believe this is roughly how Berni envisioned it when I discussed it with him, and it largely works as described. Unfortunately, what it does not do today is return **dynamic suggestion text** at step 6. So, instead of "Bodyguard is on BBC One" we get "See TVShow information".

Takeaway: dynamic suggestions are constructed from asynchronous fetch, which is not supported today under Speculative Execution.

In order to make it work, I had to break it into two steps again, which is how this ticket was born in the first place. This involves setting up the Particles so that the Strategizer stops after finding a matching Pipe Particle (instead of Coalescing a proper recipe).

Mostly I do this by making sure the renderers have false `shouldRender` if the input data is null (normally, I would have them render a blank state, so Arcs can _clear_ a value and have stable rendering. 

 Using `shouldRender` is often hacky, either because I actually would prefer to render (as above) or the particle actually doesn't care about rendering (Pipe Particles render bogus templates so they can use `shouldRender`). Maybe this can be fixed by using `this.relevance` (or some Relevance API) instead of `shouldRender` for relevance control?

**Comment by piotrswigon** [comment]
Your takeaway is not entirely correct. For the September offsite demoes we introduced some hacks that allow dynamic descriptions. Here's a PR that introduced that for the now playing demo: #1966. This is very low fidelity, but works.

**Comment by piotrswigon** [comment]
Hey @sjmiles, what's the status of this Issue? Is there something for me to do?

**Comment by sjmiles** [comment]
I need to recombobulate the pipes work to use `setBusy`, then I will re-file if there is new information.
