### ISSUE TITLE
Duplicate `[demo] find restaurants and make reservations near you.` suggestion

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2447]
To reproduce in arcs-live:
- type `find` in search
- both: `find restaurants near you.` and `[demo] find restaurants and make reservations near you.` suggestions are visible
- accept `find restaurants near you.` suggestion
- now `[demo] find restaurants and make reservations near you.`  appears 3 times.
the only difference between the three is the `action` slot that is consumed by `ReservationForm`.
`action` slot is provided by various other particles in the active recipe, hence multiple suggestions are created.

**Comment by mmandlis** [comment]
@sjmiles is it intentional that we have both - `find restaurants near you.` and `[demo] find restaurants and make reservations near you.`?

**Comment by lindner** [comment]
I can't reproduce this.  I only see *Find restaurants near you*

**Comment by sjmiles** [comment]
Stale.
