### ISSUE TITLE
Planning represented in DevTools

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2514]
I would like to to add a separate page to the Arcs extension with Planning related info, including:
- each re-planning event, what triggered it, how long it took, the suggestions that were generated etc
- list of all suggestions at the given moment, including metadata (not available in strategy-explorer, eg rank) + whether each suggestion is visible (and why)
- info about suggestion / search storages 
… and more stuff probably.

FYI @piotrswigon

**Comment by piotrswigon** [comment]
That sounds awesome. Maybe we should put some thinking in what view should be visible for consumer-only and producer-only components? When both are present in the same component we should display all the information. WDYT?

I would be very happy to assist in any way needed. Would it make sense for me to maybe help you get things off the ground just by setting up a basic page and sending some initial info in an event, which would let you develop things further hopefully with less friction?

**Comment by piotrswigon** [comment]
Progress continues with #2614 and #2615.

**Comment by mmandlis** [comment]
basic Planning log representation in DevTools is done. closing this issue and will file specific ones for future features / bug fixes.
