### ISSUE TITLE
Flaky test: remote planificator merges remotely produced suggestions

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#2519]
Fails once in about 4-5 runs on my laptop.

**Comment by mmandlis** [comment]
@piotrswigon Can you add the error here? It is not reproducible for me, so i might need your help to debug.

**Comment by piotrswigon** [comment]
False alarm. The flakiness seems to be caused by one of my patches. I need to investigate what is happening there. Sorry @mmandlis !

**Comment by piotrswigon** [comment]
Ha, I just got a similar failure on AppVeyor:
https://ci.appveyor.com/project/arcs/arcs-3i77k/builds/21344909

Investigating.

**Comment by mmandlis** [comment]
Ha, i also filed an error for it: https://github.com/PolymerLabs/arcs/issues/2521
I've seen it earlier today too.

**Comment by piotrswigon** [comment]
I had the other test (merges remotely produced suggestions) failing one in 4 times at home. Maybe it has to do with network latency? Though these use local storage, right? So that's weird.

**Comment by mmandlis** [comment]
The newer failure (#2521) should be fixed with: https://github.com/PolymerLabs/arcs/pull/2522.
Closing this one for now. Please, reopen, if the original failure is reproducible again. Thanks.
