### ISSUE TITLE
Introduce typescript generics where it makes sense

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2561]
There are a number of places where generics would help make the code easier to understand and use.  Specifically there are some types that wrap other types.  Those would make good candidates to convert.

To start the generic discussion please see `CollectionType` in `type.ts`.  It wraps another type and provides collectionType() to get at the underlying object.  That currently returns Type, instead the class could be parameterized with the base class and it could return that instead.

**Comment by lindner** [comment]
@eggplanthater - might want to look at this afterwards.

**Comment by lindner** [comment]
here's some sample code that might just work!

```
abstract class Type {
    hey() {
        console.log('hey');
    }
   
}
class Var extends Type {

}
class Collection<T extends Type> extends Type {
    constructor(private type: T) {
        super();
    }
    containedType(): T {
        return this.type;
    }
}

const t = new Collection<Var>(new Var());
console.log(t.containedType());

const t2 = new Collection<Type>(t);
console.log(typeof t2.containedType());


```

**Comment by lindner** [comment]
this avoids a lot of code that does this:

```
   const foo = type.containedType as Var;
```

**Comment by mykmartin** [comment]
:+1:

**Comment by thebrianchen** [comment]
@lindner can we close this issue now?
