### ISSUE TITLE
restaurant demo partially broken 

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#2567]
Steps: Type restaurants, selected nearby restaurants suggestion, tap on a result:

Expected: "Make a reservation for 2 at 19:00" or so
Actual: "Make a reservation"

Steps: Tapping that reservation suggestion.

Expected: Calendar suggestion
Actual: No default suggestions

**Comment by sjmiles** [comment]
I factored ReservationForm and ReservationAnnotation into discrete bits (they used to do duplicate work).  This is also why there are two declarations of ReservationForm in the recipe (one for the all restaurants, one each for the per-restaurant annotations).

That required moving the description generation into ReservationAnnotation and I just didn't get that done. I'll do it today.

**Comment by sjmiles** [comment]
Working on this issue, currently blocked on https://github.com/PolymerLabs/arcs/issues/2581.

**Comment by sjmiles** [comment]
I believe the core problem here is fixed. Please re-open or open new tickets as needed.

**Comment by sjmiles** [comment]
I don't have the suggestions quite right yet.

**Comment by shaper** [comment]
@sjmiles is this still not fixed with #2649?

**Comment by sjmiles** [comment]
It's mostly fixed, but the output is different that before. I left this open until I could have a f2f with Berni and get his input.

**Comment by lindner** [comment]
@seefeldb -- can we close?
