### ISSUE TITLE
Include original slot names to the DOM template

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2578]
Follow up #2228 and #2345
Having slot names in the DOM will make debugging so much easier. 
FYI @sjmiles

**Comment by sjmiles** [comment]
Meta: it is true in general that the more of the human-generated names we use the easier it will be to reason about what is happening at runtime (of course, the converse is true, that if the _goal_ is obfuscation, then you want to replace all of the names). I believe we are also going to want/need to be able to extract/generalize a Plan back into a Recipe: especially for capturing an ActiveRecipe into something reusable. I suspect these concepts (human readability and generalization) overlap.

**Comment by sjmiles** [comment]
At some point I made the slot system copy `slotid` onto `slotname` attribute so at least the human-name is available in DOM.

Maybe in future we want that value to be stored somewhere in serialization too, but I think this is enough for now.
