### ISSUE TITLE
Ensure Syntax Errors are lenient

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#2585]
I.e. if there's a syntax error in one manifest file, this will not cause construction of a corrupted context.

**Comment by shaper** [comment]
Seems important so made p1 but I can imagine alternate perspectives.

**Comment by shaper** [comment]
It's been months, this feels like it can't be a p1 or we'd have been experiencing more pain. Please comment if you feel otherwise.

**Comment by Cypher1** [comment]
What is a corrupted context? Is this bug about the peg parser being able to continue after detecting syntax errors or about the generated manifest class tracking these errors and not allowing itself to be run?

**Comment by piotrswigon** [comment]
OMG, I feel bad, I don't understand what this issue is about myself.

It's definitely something related to syntax errors in imported manifests. @Cypher1 do you have a plan for how these issues should be handled? Sarah recently filed #3568 which seems related.

I will close this issue as I don't know what it is about :/
