### ISSUE TITLE
`Planificator::setSearch` can fail to trigger planning

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2616]
Sometimes entering a search term in WebShell doesn't cause suggestions to update: afaict it looks like `planificator.setSearch` can fail to update the planner. 

I can usually recreate it by trying to search right after refreshing the WebShell, which implies to me that maybe the problem is related to calling `setSearch` while the Planner is busy.

**Comment by mmandlis** [comment]
@sjmiles so far i wasn't able to reproduce the problem :(
do any suggestions at all show up for you? are you using the same search string over and over again, or different string every time?

**Comment by sjmiles** [comment]
I put a [video](https://drive.google.com/open?id=1w4eEA98_xM-OGdGzncZAuqoR_B3TLgf3) of the problem on the team drive.

**Comment by mmandlis** [comment]
I was able to reproduce it. 
This only happens with the arcs storage is PouchDB: 
`?plannerStorage=volatile&storage=pouchdb://local/test`
and in the case when search for this arc was previously set to the same string. 

Planificator doesn't load the existing search from storage, so it doesn't recognize when trying to set search to the same value. However in Firebase same value still triggers 'change' event, but not in pouch, so replanning is not triggered.

https://github.com/PolymerLabs/arcs/pull/2676 fixes the problem by resetting the search value for the current arc when planificator is created.
