### ISSUE TITLE
Xen interaction with Typescript & tests

### ISSUE THREAD

**Issue by Cypher1** [PolymerLabs/arcs#2759]
There may be an architectural reason behind this, but it seems that Xen is somewhat untested and is also not written in TypeScript.

This makes it somewhat difficult to understand and then work around (there's no types for documentation and some of the Object manipulation is also tricky).

Can we add tests for it to mitigate this and make it easier to modify classes that interact with Xen (e.g. the dom-particles)?

Is there anything we can do to improve the type checking? (Particularly, I've been having trouble converting the dom particles to typescript so that I can have tsc warn me with incorrect field names etc).

Thanks

**Comment by Cypher1** [comment]
@sjmiles @shans

**Comment by shaper** [comment]
It looks like Runtime dependency is only `slot-dom-consumer.ts`, and there, only `xen-template`. There is an explainer doc under `./modalities/dom/components/xen/xen-explainer.html`.

A VC with @sjmiles to discuss further may be one reasonable next step. It is my understanding he prefers to work in straight JS, and is iterating on Xen quickly enough that he prefers not to add unit tests. We could consider having someone else fork and maintain a subset ongoing to do those things if we thought warranted.

**Comment by shaper** [comment]
Another alternative is to consider a way to factor that one Xen dependency out of Runtime so that it's, say, an interface.

**Comment by sjmiles** [comment]
Yes, everything Walt said, except there's not really a good excuse for missing unit tests. It doesn't change very often, so is not prone to breakage, that's my rationale(-ization).

The intent is that Xen is a commodity thing, as if it were installed via NPM, and not part of Arcs proper.

**Comment by sjmiles** [comment]
For the record: 
`dom-particle` imports `xen-state` (innerPEC)
(in addition to what Walt noted about `slot-dom-consumer` importing `xen-template` [outerPEC])

**Comment by sjmiles** [comment]
Also, I'm happy to help come up with type information for any specific API. I gave myself a TODO to look at that surface (xen-api used by runtime), but I'm afraid I'm not going to get to it anytime soon.

**Comment by Cypher1** [comment]
Thanks @sjmiles. Would converting to TS limit you? If nothing else it would reduce the reducethislist file (which seems to be a stated goal that we have, but primarily I think it would also help us to get type inference on the _state member of the Particle classes.

If the APIs are any-typed, so be it, but I think it would be helpful to at least have the annotations available, if not actually being particularly specific.

**Comment by sjmiles** [comment]
Yes, I prefer avoiding conversion of Xen to TS. As mentioned, I thought there was a way to create some kind of intermediate file to bridge the worlds?

Perhaps `state` and friends are problematic since they are (by design) generic dictionaries? This is the kind of JS plasticity Xen is intended to leverage for high speed and small foot-print.
