### ISSUE TITLE
Create a User Exception pathway 

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#2764]
Also modify the system exception endpoints that are actually reporting on user exceptions to use the new pathway instead.

**Comment by shans** [comment]
[Cameron is going to look at this]

**Comment by csilvestrini** [comment]
Shane, what did you want to happen when UserExceptions are thrown? Currently, SystemExceptions are just logged to the console and rethrown in arc-exceptions.ts. Did you want UserExceptions to be handled differently?
