### ISSUE TITLE
Pouch: Restaurants demo fails on step #2 to choose time.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#2863]
Repro steps:

* Visit web shell with new Pouch user ex. `http://localhost:9119/shells/web-shell/index.html?log=&plannerStorage=volatile&storage=pouchdb://local/foouser`
* Choose `Find restaurants near you.` suggestion and wait for results to load.
* Choose `You are free at 19:00...` suggestion.

Note error as:

```
Uncaught (in promise) Error: can't find store of id !96693423723245:foo--LbyEnYae6T_NtQYj7Rv:21
    at assert (assert-web.ts:12)
    at Arc._instantiateParticle (arc.ts:437)
    at arc.ts:576
    at Array.forEach (<anonymous>)
    at Arc.instantiate (arc.ts:576)
    at Object.onArcLoadRecipe (particle-execution-host.ts:231)
```

There are three earlier errors in the log as:

```
StorageProxy '!96693423723245:foo--LbyEnYae6T_NtQYj7Rv:8' received stale update version 1; current is 1
```

FYI @lindner

**Comment by shaper** [comment]
Firebase fails with one `can't find store` error, and a bunch of `StorageProxy '!994857782637212:foo--LbyHohOlGll2YQCXWIf:21' received stale update version 3; current is 3` sorts of errors, but eventually is operational. Pouch seems to never get to an operational state.

**Comment by lindner** [comment]
I had to whittle down the hundreds of calls in description to help make sense of this.  #2905 makes this easier.

With that we see that the requests to read the the handles are executed off the onClick handler, which invalidates the state and leads to recalculating the descriptions.

```
  | create | @ | description.ts:51
  | (anonymous) | @ | slot-composer.ts:157
  | initializeRecipe | @ | slot-composer.ts:157
  | instantiate | @ | arc.ts:583
  | async function (async) |   |  
  | instantiate | @ | arc.ts:523
  | instantiatePlan | @ | arc-host.js:97
  | set plan | @ | arc-host.js:54
  | update | @ | web-arc.js:79
  | _update | @ | xen-async.js:36
  | _doUpdate | @ | xen-base.js:36
  | _doUpdate | @ | xen-debug.js:42
  | _validate | @ | xen-state.js:122
  | Promise.then (async) |   |  
  | _async | @ | xen-state.js:97
  | _invalidate | @ | xen-state.js:102
  | _invalidate | @ | xen-debug.js:50
  | _invalidateProps | @ | xen-state.js:67
  | _setProperty | @ | xen-state.js:42
  | _setProperty | @ | xen-debug.js:8
  | set | @ | xen-element.js:36
  | _set | @ | xen-template.js:254
  | set | @ | xen-template.js:216
  | set | @ | xen-template.js:342
  | _doUpdate | @ | xen-base.js:42
  | _doUpdate | @ | xen-debug.js:42
  | _validate | @ | xen-state.js:122
  | Promise.then (async) |   |  
  | _async | @ | xen-state.js:97
  | _invalidate | @ | xen-state.js:102
  | _invalidate | @ | xen-debug.js:50
  | _setState | @ | xen-state.js:92
  | _setState | @ | xen-debug.js:15
  | set state | @ | xen-async.js:7
  | onChooseSuggestion | @ | web-shell.js:325
```

Immediately after this the Handle data is set via `onHandleSet`

``` 
  | set | @ | pouch-db-variable.ts:216
  | onHandleSet | @ | particle-execution-host.ts:92
  | before | @ | api-channel.ts:383
  | _processMessage | @ | api-channel.ts:237
  | APIPort._port.onmessage | @ | api-channel.ts:215
```

I investigated and Firebase has some code that allows an initial `set` to trigger the initialized state:


```
   if (this.version == null) {
      assert(!this.localModified);
      // If the first modification happens before init, this becomes
      // init. We pick the initial version which will be updated by the
      // transaction in _persistChanges.
      this.version = 0;
      this.resolveInitialized();
```

Still looking at the best way to support that, or alternates.

That said it seems brittle and there should be some way of blocking the plan update until after the handles are written.

**Comment by sjmiles** [comment]
I think we have to loop in @shans, @mmandlis et al on this.

Re the first stack trace:

  | create | @ | description.ts:51
  | (anonymous) | @ | slot-composer.ts:157
  | initializeRecipe | @ | slot-composer.ts:157
  | instantiate | @ | arc.ts:583
I suspect everything below here is irrelevant, `arc.instantiate` is where the magic happens.

**Comment by mmandlis** [comment]
I tried it on both - locally and arcs-live and this is the exception I'm getting:
```
assert (assert-web.ts:11)
_instantiateParticle (arc.ts:440)
(anonymous) (arc.ts:579)
instantiate (arc.ts:579)
onArcLoadRecipe (particle-execution-host.ts:243)
await in onArcLoadRecipe (async)
```

and it is followed by (but i this is probably caused by the one above):
```
description.ts:132 Uncaught (in promise) TypeError: Cannot read property 'rawData' of null
    at Function._getPatternByNameFromDescriptionHandle (description.ts:132)
    at async Function._createParticleDescription (description.ts:105)
    at async Promise.all (/arcs-live/shells/web-shell/index 7)
    at async Function.initDescriptionHandles (description.ts:91)
    at async Function.create (description.ts:51)
    at async Promise.all (/arcs-live/shells/web-shell/index 0)
    at async DomSlotComposer.initializeRecipe (slot-composer.ts:157)
    at async Arc.instantiate (arc.ts:583)
```
The particle it fails for is `ReservationMultiAnnotation`

**Comment by lindner** [comment]
I dug into this a little deeper and there are two calls into `onArcLoadRecipe`

The first is `ReservationAnnotation`
```
arc.ts:510 instantiate recipe
  use '!833132910810778:user--LcgletXh5K_M-3Q6Jtk:21' as handle0 // Event {...}
  use '!745969886451346:user--LcgletXh5K_M-3Q6Jtk:inner30:1' as handle1 // Restaurant {...}
  slot '!745969886451346:user--LcgletXh5K_M-3Q6Jtk:inner30:2' as slot0
  ReservationAnnotation as particle0
    event = handle0
    restaurant <- handle1
    consume annotation as slot0 

 activeRecipe = Recipe {_requires: Array(0), _particles: Array(1), _handles: Array(2), _slots: Array(1), _localName: undefined, …} (2) 
resultingHandles = [Handle, Handle]
```

Note the 2 handles.  One is !833132910810778:user--LcgletXh5K_M-3Q6Jtk:21

Next comes the load of `ReservationMultiAnnotation`

```
instantiate @ arc.ts:510
arc.ts:510 instantiate recipe
  use '!833132910810778:user--LcgletXh5K_M-3Q6Jtk:21' as handle0 // Event {...}
  use '!745969886451346:user--LcgletXh5K_M-3Q6Jtk:inner30:3' as handle1 // Restaurant {...}
  slot '!745969886451346:user--LcgletXh5K_M-3Q6Jtk:inner30:4' as slot0
  ReservationAnnotation as particle0
    event = handle0
    restaurant <- handle1
    consume annotation as slot0 Recipe {_requires: Array(0), _particles: Array(2), _handles: Array(3), _slots: Array(2), _localName: undefined, …} 

resultingHandles = [Handle]

```

The mergeInto has removed the handles from the active recipe.

Later on in arc.instantiate things blow up because of this.

**Comment by lindner** [comment]
So I've managed to move the problem around.

Adding async-mutex around usages of the active recipe in the Arc prevents some of the above errors, but then issues appear further along.

**Comment by lindner** [comment]
With the mutex'd instantiate and changes to make Pouch stateless I am seeing reservation slots appear.

Will teast apart into smaller PRs to find out what the real solution is.  (And hope that removing logging does not cause race conditions)

**Comment by lindner** [comment]
Also there's a race condition, in `construct`.  Reference mode is enabled after the object is constructed so you have to deal with that as well.

**Comment by lindner** [comment]
Retested on head and this is now working properly without the stateless pouchdb changes.

I would like to land the refactor still, but this is now much lower priority now that this is working.
