### ISSUE TITLE
change events for Variables

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2877]
Collection observers (`store.on('change')`) send `remove`/`add` events in pairs whenever an Entity is modified. This allows observers to easily maintain correct state.

Variable observers send only `data` events, so an observer doesn't know (without additional bookkeeping) how to deal with the previous data.

For example, the Context generator collates a list of all `userName` records. If I change a `userName` record (in a Variable), the event doesn't supply enough information to remove the old `userName` record.

It would be useful to have analogous event pairs as for Collection. @shans suggested `clear`/`set` events. Alternatively, the `data` event could supply `previous-entity-id`.

**Comment by csilvestrini** [comment]
Where we'd like to end up with Collections is that `add` and `remove` events are only for adding/removing entities to/from the collection. Mutations to entities already in the collection should be a different kind of event (e.g. an entity mutation event).

The situation with Variables should ideally look similar. I'd suggest a `set` event that gives you the previous entity and the new entity. Entity mutations would ideally be a separate event (i.e. the same entity mutation event for collections), with the rationale that modifying an entity is a completely different thing compared to setting a new entity in a Variable. Until we have proper mutation events, we could represent mutations to entities as `set` events, where the old and new entities provided share the same entity id, but have separate data.

`clear` events would just a be `set` with a null new entity.

**Comment by sjmiles** [comment]
I have a practical problem today, which is that I can't keep Context up to date with respect to Variables because of a missing signal. I'm looking for a (hopefully) immediate solution to that problem.

Otherwise, I don't have any axes to grind about how the signals are presented, as long as I have a sufficient set.

> clear events would just a be set with a null new entity.

The critical bit today is that if a Variable lets go of an Entity, I would like to have a signal that tells me that the Entity is going away and includes the original data. Otherwise, I have to keep a clone of every Entity, and a map them to Variables so I can clean up if a Variable is cleared.

To say it another way: if an Entity (identified by it's id) was referenced by a Collection|Variable and now it is not, I need to be notified that that relationship is going way. And of course, I need to know when an Entity becomes referenced by a Collection|Variable also.

Does that make sense?
