### ISSUE TITLE
Consider removing @license directives

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2973]
Our typical license header looks like this:
```
/**
 * @license 
 * Copyright (c) 2017 Google Inc. All rights reserved.
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 * Code distributed by Google as part of this project is also
 * subject to an additional IP rights grant found at
 * http://polymer.github.io/PATENTS.txt
 */
```
The @license directive tells minifiers (like WebPack) to preserve this comment (instead of stripping it out as for most comments). IMO and unless there is some other reason for that directive, we only need _one_ @license per build target. Otherwise, as today, the build target ends up with numerous copies of this same license header.

**Comment by lindner** [comment]
Would you be okay with lightly minimized webpack js?

**Comment by sjmiles** [comment]
Not sure what you are asking.

**Comment by lindner** [comment]
The typescript compiler can strip comments entirely.  Seems excessive.

Here's something that does light minimization and removes the comments from the output and puts them in a separate file.  I made sure that sourcemaps are preserved and the output actually has newlines...

```
const TerserPlugin = require('terser-webpack-plugin');

const lib = './shells/lib';

module.exports = {
  mode: 'none',
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        cache: true,
        extractComments: 'all',
        parallel: true,
        sourceMap: true,
        terserOptions: {
          ecma: 8,
          compress: false,
          mangle: false,
          module: true,
          output: {
            semicolons: false
          }
        }
    })
   ]
  },
  devtool: 'source-map',
....
```

**Comment by sjmiles** [comment]
When we build distribution files (e.g. pipe-shell/<platform>/dist) we run as much compression as we can get. It doesn't matter so much for the development files.

But this misses the point of my issue. There is a built in feature (in most packers) to treat `@license` headers specially. If we put `@license` only in package entry-points, then our build files contain one appropriate license.

If we put `@license` on everything, we end up with a million copies of that license, even if it's in an external file. This is not some huge thing, but it seems like it would be good to remove `@license` from any of our source that doesn't somehow stand alone (which is 99% of it, I think).

**Comment by lindner** [comment]
So I've done some investigation here.   

@license is also used by IDEs to hide the comment by default.  It is also stripped out by typedoc so it can be recognized as boilerplate.  Open Source policy requires us to include such headers, so they have to stay..

So what we can do is strip out our own license headers and use the webpack banner plugin to put a single license back.

**Comment by lindner** [comment]
Reopening to land some webpack magic...

**Comment by lindner** [comment]
Closing as webpack is doing fairly well with this.
