### ISSUE TITLE
Getting rid of the <interleaved-list> hack

### ISSUE THREAD

**Issue by noelutz** [PolymerLabs/arcs#299]

**Comment by sjmiles** [comment]
I think I voiced the idea that became this issue, but in hindsight I realize I hadn't really capture the goal I was aiming for. My intent was less specifically about <interleaved-list> then about improving the particle-developer-facing experience in the domain of set-slots.

Specifically, what's in my head is the ability for a Particle to declare and render, anywhere and in any quantity, a slots with (1) a slot id and (2) a token to identify an Entity (from one of the Particle's input lists).

So, for example, a Particle that takes a list of Product could produce any number of `annotation` slots and associate each slot with a particular Entity. Then Particles that can consume that Entity type and slot type can be used to render that slot.

Maria is working on this issue, but the current solution is only partial (she has successfully removed `interleaved-list` so technically has satisfied the issue!) IMO, it's ok to use the partial solution to satisfy this issue for purposes of milestone tracking, as long as we as sure to capture the overall issue going forward.
