### ISSUE TITLE
Arcs CDN built from master

### ISSUE THREAD

**Issue by noelutz** [PolymerLabs/arcs#300]
- Merge Scott's CDN [changes](https://docs.google.com/document/d/1gr9dN8lCFW8puG5tGAvKTsp1Qe-2iZB0TeysMgCzZfw/view) into master (gulp file, ...)
- Create PolymerLabs/arcs-cdn repo and push an initial Arcs library.
- Document CDN [push process](https://docs.google.com/document/d/1rzz43MFvIVW1f307fnpVpJRBqjoVwOZsWgU0XyXijuE/view)

**Comment by sjmiles** [comment]
> Create PolymerLabs/arcs-cdn repo and push an initial Arcs library.

This is done. E.g. https://polymerlabs.github.io/arcs-cdn/v0.02/ArcsLib.js

**Comment by sjmiles** [comment]
> Merge Scott's CDN changes into master (gulp file, ...)

This is done. Note that some of the changes I aimed at master didn't have to go that low. I've put the cdn source and the build scripts directly into the cdn repo.

**Comment by sjmiles** [comment]
> Document CDN [push process](https://docs.google.com/document/d/1rzz43MFvIVW1f307fnpVpJRBqjoVwOZsWgU0XyXijuE/view)

I updated the new CDN-centric build process in the CDN [readme](https://github.com/PolymerLabs/arcs-cdn/blob/gh-pages/README.md).

**Comment by sjmiles** [comment]
@noelutz I think this issue is largely satisfied. Let me know if I should do anything else.

**Comment by noelutz** [comment]
LGTM. Thanks!
