### ISSUE TITLE
Misleading manifest-parser error

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#3019]
```
manifest.ts:399 Parse error in 'https://$particles/RenderEx/RenderEx.recipes' line 47.
Expected identifier but keyword, 'create' found.
    create #volatile as TilesOutput
    ~~~~
```

The actual problem here is that `TilesOutput` is capitalized.

**Comment by Cypher1** [comment]
@shans This is the second time (that I can find issues for #2961 ) where not having manually inserted errors on partial parse of a node (specifically, after a keyword that we can use as a sign that back tracking will fail).

We should investigate this later, but I will attempt to improve this message in the mean time (parse tree reordering may be enough).

**Comment by sjmiles** [comment]
If you are in there, this one also relates to parser-error-reporting #2570 

Not so related, but since we are here, I'll also bump #2467

**Comment by Cypher1** [comment]
As far as I can tell #2570 doesn't relate to the actual parser's error reporting, but to the exception handling in manifest.ts, so is a different issue (which I also want to fix).
As to #2467, noted, will comment with clarification there.
