### ISSUE TITLE
Refmode Firebase handles not persisting

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#3040]
BackingStore data is created, but the `referenceMode: true` handles are missing connective tissue. 

![image](https://user-images.githubusercontent.com/98045/57902464-092ff280-781e-11e9-9e54-e875c9c2db25.png)

Bisecting led me here:

https://github.com/PolymerLabs/arcs/commit/17f565f70f3699c574707cafc2212be2d7160d23#diff-1cb03d2486b8fbbf2a5228bbb948c24a

Also I guess we are missing test coverage here since the problem went unnoticed for a couple of weeks.

**Comment by lindner** [comment]
Before marking this fixed we should add integration tests of Profile UI including name editing followed by an explicit reload.  I can add that...
