### ISSUE TITLE
TF(JS): Using different versions depending on platform (Node vs Web, w/wo GPU, Mobile)

### ISSUE THREAD

**Issue by alxrsngrtn** [PolymerLabs/arcs#3072]
I came across a [useful recommendation](https://github.com/tensorflow/tfjs/issues/298#issuecomment-401052395) when trying to debug something: We should prefer to use tfjs-node instead of vanilla tfjs whenever possible. 

Better yet: We should use `tfjs-node-gpu` when that resource is available. 

I'm still getting used to the `platform/` pattern used in this project, but it seems like a good model for how we can accomplish this in the short term. 

In the medium term, how do we extend this pattern to mobile platforms? 

## References
- https://github.com/tensorflow/tfjs-node
- https://www.tensorflow.org/js/guide/nodejs
- https://www.tensorflow.org/js/guide/platform_environment
- #3028

**Comment by sjmiles** [comment]
Today I generally handle static-linking problems by having platform-level (or entry-point if you prefer) configuration.

E.g. shells built for a particular platform can choose to employ the Pouchdb storage (Web) or not (Node).

Dynamic configuration (run-time detection) is a different kettle of fish. I suppose understanding what can be detected and how would be the first step.

**Comment by alxrsngrtn** [comment]
I'm reading more about what we get out of the box with tfjs. It's a sophisticated system. I'll post a summary of what I've found below.

**Comment by alxrsngrtn** [comment]
# Tensorflow for Javascript

## Platform & Environment
- tf supports multiple backends. Only one is used at a time. 
- Backends are generally chosen automatically. 
- To find what backend you are using: `console.log(tf.getBackend()); `
- To set the backend: `tf.setBackend('cpu');`
- Global flags can be set for dev/prod: 
  - `tf.enableProdMode()` will remove correctness checks in favor of performance
  - `tf.enableDebugMode()` will log to the console every operation that is executed, runtime performance information (memory footprint, kernel exec time). This will greatly slow down the applicaitons. 

### Browsers vs Node
Browsers
- For Browser environments, the `'webgl'` backend is the most powerful (x100 than vanilla CPU). 
- While results are synchronously returned, matrix computations are usually not yet ready. Values are computed asynchronously and references to the results are returned immediately. 
  - make sure to use async calls, like `x.data()` or `x.array()` over their synchronous counterparts, which will block the UI thread. 
- *`webgl` requires explicit memory management!*
  - Call `dispose()` on tensors no longer in use: `a.dispose(); // a is a tf.tensor`
  - Wrap values inside the `tf.tidy(...)` function, and values not returned will be cleaned up automatically: 
     ```
      const a = tf.tensor([[1, 2], [3, 4]]);
      const y = tf.tidy(() => {
         const result = a.square().log().neg();
         return result;
     });
     ```
  - These two functions improve performance even in contexts where there is garbage collection (node or cpu), so it's ok to use for whatever environment. 
- On mobile devices, WebGL supports reduced precision (16 bit floats, not 32bit). This requires model adjustments
- Due to WebGL's GPU loading and caching strategy, prediction is often faster on the *second* function call. Depending on the situation, you might want to "warm up" the model: 
   - ```
      const model = await tf.loadLayersModel(modelUrl);

      // Warmup the model before using real data.
      const warmupResult = model.predict(tf.zeros(inputShape));
      warmupResult.dataSync();
      warmupResult.dispose();

       // The second predict() will be much faster
       const result = model.predict(userData);
      ```

Node
- In the `'node'` backend, Tensorflow's C API is used to accelerate operations, and will use hardware acceleration, like CUDA, when available. 
- Unlike WebGL, TF operations will be completed before we get a tensor back. This means calls, like `tf.matMul(a, b)` will block the UI thread. 
  - Recommendation: Run `Tensorflow.js` in worker threads to not block the main thread.

**Comment by alxrsngrtn** [comment]
Going to close issue for now due to #3097 . We can reopen this later if necessary. 

Status as of this closure: 
- Web: will use `tfjs`
- Node: will use `tfjs-node` (calls the underlying cpp API for tensorflow, which is much more performant
  - We have no dynamic support for `tfjs-node-gpu`, but this is mostly intentional.
