### ISSUE TITLE
Appveyor Build Failing: Broken Unit Test -- `Store Flow`

### ISSUE THREAD

**Issue by alxrsngrtn** [PolymerLabs/arcs#3100]
The build has been breaking within the Windows Appveyor build, but not the Linux Travis build. 

Here is a reproduction of the failed test from the Appveyor logs: 
```
  951 passing (26s)
  15 pending
  1 failing
  1) Store Flow
       applies 3 operations and 2 models simultaneously:
untimestorageNG	estsstore-sequence-test.js)
```

**Comment by Cypher1** [comment]
Fixed in https://github.com/PolymerLabs/arcs/pull/3113?
