### ISSUE TITLE
Provided-slot view not verified

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#313]
Particle may declare it its manifest that the slot that it provides should be used for a particular view.
However, it is not verify, and a Particle that doesn't have this view in its connections gets rendered
(example in arcs-hello-world project)

**Comment by noelutz** [comment]
This seems to work as expected now: https://glitch.com/edit/#!/arcs-hello-world

**Comment by sjmiles** [comment]
After choosing `Hello` shouldn't `Greetings to you` become available as a suggestion?

**Comment by mmandlis** [comment]
This issue was filed about Particle restricting the provided slot to a particular view, but the consuming particle not having that view and still rendering (there is no such example in glitch, Noe and I just hacked it on the fly).
It is supposed to be fixed by https://github.com/PolymerLabs/arcs/pull/312, which is not submitted yet.
