### ISSUE TITLE
remote provided slot not resolved for particle in a separate recipe

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#314]
arcs-hello-world
If splitting the particles to separate recipes:
recipe
  Greet
recipe
  PersonalGreet

where
particle Greet
  consume root
    provide personalGreeting
particle PersonalGreet
  consume personalGreeting

after Greet was instantiated, a slot should become available for Personal Greet, but it is not getting resolved by the map-remote-slots strategy.

**Comment by mmandlis** [comment]
this is due to the playground demo only calling the Planner to generate suggestions once.

ui.callback = () => {};

the suggestion-element callback needs to be set to smth that triggers Planner.suggest, similar to the demo-base.js nextStage() method.

**Comment by sjmiles** [comment]
In Arcs CDN v0.03 I implemented regenerating suggestions. Please try it out.

**Comment by mmandlis** [comment]
Thanks, I tested it with the hello-world and chat glitch apps, and it works fine.

**Comment by sjmiles** [comment]
In the hello-world glitch (https://glitch.com/edit/#!/arcs-hello-world) after choosing 'Hello' I expect 'Greetings to you' to become a suggestion, as per the discussion in this ticket.  

I guess it's what I expected to work as per "tested it with the hello-world glitch app". 

I must have the wrong expectation, can you explain?

**Comment by mmandlis** [comment]
in https://arcs-hello-world.glitch.me/
at first I get 2 suggestions:
"Hello and Greetings to you"
"Hello"

after I choose "Hello", I get 4 suggestions, one of which is "Greetings to you".
Is it not what you're getting?

**Comment by sjmiles** [comment]
Sigh. The toast is supposed to open again when there are fresh suggestions, this is the bug.  Because the toast didn't open I assumed there were no suggestions.

A thousand pardons.

**Comment by mmandlis** [comment]
I actually thought it was a feature, because the demo always behaved like this (I think) - it makes perfect sense to me, when user already has their content on the screen, it might be better for suggestions not to pop up.

**Comment by sjmiles** [comment]
At one point I went to special pains to allow the apps to control this behavior (I think I wanted something different in the VR demo). At any rate, this is ancient history.

After I realized my gaffe, I came to the same conclusion you did (that it's better not to pop-up new stuff until the user asks for it).

Thanks for the help!
