### ISSUE TITLE
Add input/output Types for Service Layer Calls

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#3246]
The shell service layer while simple, would benefit from having typescript typed input/output on the endpoints.

**Comment by sjmiles** [comment]
Particles are not written in TS so I'm not sure how we would utilize types on the Particle side (innerPEC).

**Comment by lindner** [comment]
I was capturing Shane's comment, so I might have grabbed it wrong.

Instead maybe we need to use the same Schema types for input/output?  Those
should work on both the host and the particle.

**Comment by shaper** [comment]
For @shans to reopen with clarification as appropriate.
