### ISSUE TITLE
Too many suggestions are shown the the user

### ISSUE THREAD

**Issue by noelutz** [PolymerLabs/arcs#325]
Can we prune less interesting suggestions? Or suggestions that are primarily subsets of a higher-scored suggestion?

Example: https://glitch.com/edit/#!/arcs-chat

**Comment by shans** [comment]
I've been looking into this. Partly we can reduce suggestions by crafting our input recipes more precisely, but I don't know that this is the right answer long-term.

**Comment by shans** [comment]
I think we can call this entirely fixed once #338 lands. #335 and #330 helped too.
