### ISSUE TITLE
Redirect the open web-shell link to a directory path

### ISSUE THREAD

**Issue by sherry-pra** [PolymerLabs/arcs#3268]
The documented arcs link `http://localhost:8786/shells/web-shell` needs an extra backslash to work since web-shell is a directory: `http://localhost:8786/shells/web-shell/`. An option might be to change this in the read-me documentation.

**Comment by sjmiles** [comment]
Just to be clear, whether or not it works without the backslash depends on the web-server, as does the prefix `http://localhost:8786`.

Is the documentation you refer the root README.md in the section about `npm start`? In that case, we can conform the URL to the specific server we start (we recently changed it, which probably explains why the / wasn't needed before). 

Bottom line, let's keep in mind that these details are dependent on the web-server (aka deployment) in use and make sure we don't hardcode/document ports or server paths where we should not.
