### ISSUE TITLE
Add Time Handling support to Host/Particles.

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#3319]
To better support Time Handling in Arcs Particles and Host the following changes will need to be made.  When finished a standard API, Service and Data Types for Time will be available.

- [x] Add javascript implementations for `Instant` and `TimeUnit`
- [ ] Add support parsing and storing `Instant` data storage type for Schemas.
- [x] Create a Clock Service with a `now`method that takes a `resolution` parameter.

P2
- [ ] Add support for a Time Particle that wraps calls to the Clock service.
- [ ] Migrate existing usages of timestamps used in Schemas
  - [ ] PipeEntity
  - [ ] TVMazeShow
  - [ ] Event
  - [ ] Words/Stats
- [ ] Migrate native accesses to Clock
  - [ ] Events/source/Calendar.js Generates a human readable time using current time as a delta.
  - [ ] Restaurants/source/ReservationAnnotation.js creates random reservation entries using the current clock.
  - [ ] PipeApps2/source/UpdateMe.js creates a local-specific readable date/time.
  - [ ]  Stardate/js/StardateTOS.js create a stardate from the clock.
  - [ ]  Products/source/AlternateShipping.js - uses a clock to calculate a date 12h in the future.
  - [ ]  Products/source/GiftList.js - calculates the time 3 weeks from today.
- [ ] Modify `src/runtime/loader.ts` to use the Realms api and the `realms-shim` package to isolate accesses to the system clock.
- [ ] Update Documentation and Examples

**Comment by Cypher1** [comment]
We have recently landed Instant support. There's some more work to do in adding a Duration type and more clock APIs but these are currently being tracked internally.
