### ISSUE TITLE
Ensure `handles` is always set for particles.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#3560]
Breakout from discussion: https://github.com/PolymerLabs/arcs/pull/3539#discussion_r323023621

It sounds like we need to update runtime particle support in some manner such that we can be confident `handles` is always set. @sherry-pra noted sometimes particles may override `setHandles`. In her hot code reload integration test she explicitly sets `this.handles`. @mykmartin notes we need to do this follow-on work, so filing issue to track.

**Comment by sherry-pra** [comment]
Fixed in this commit [#3595](https://github.com/PolymerLabs/arcs/pull/3595).
