### ISSUE TITLE
Loading Particle with Javascript Error Hides Messagre

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#3603]
If there is a compile error in the Javascript definition of the particle, the error message only says the Javascript cannot be loaded and does not include any reason.

See screenshot:
![Screen Shot 2019-09-20 at 2 37 25 PM](https://user-images.githubusercontent.com/3030811/65360766-02dbc980-dbb6-11e9-8487-f63ae2111001.png)

**Comment by Cypher1** [comment]
Quick question about the compilation problem you mention.

Could this problem actually be a failed load (i.e. wrong path) or is it a build problem for a wasm particle?

This may help: https://github.com/PolymerLabs/arcs/pull/3607

**Comment by SHeimlich** [comment]
In this case the error was I had mis-matched curly braces ({}). I had the same issue occur when I had forgotten to put a value after the "=" in a variable declaration (ie, var foo = ;). I'm working with Javascript files at the moment, The file path was definitely correct in both cases as I'd been working with the same file structure for awhile.

**Comment by piotrswigon** [comment]
@Cypher1 are you looking into this? I've seen you've had a stab at exploring it.

**Comment by piotrswigon** [comment]
I think it would be worthwhile exploring how to fix this sooner rather than later.

**Comment by Cypher1** [comment]
Would you like to chat about it on Syd's Tuesday (not sure where you are right now) in a time you and @SHeimlich can both make?

**Comment by Cypher1** [comment]
Got talking to Myk about the bug and found some of what was going on.
Opened a PR  (https://github.com/PolymerLabs/arcs/pull/3661) to address the surface of it but am hoping that @SHeimlich can follow up and check that this is now working as expected.
