### ISSUE TITLE
missing references in particle manifest files don't result in errors

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#362]
A particle declaration like this:

```
particle MergeBodiesOfWater in 'MergeBodiesOfWater.js'
  ShowBodyOfWater(in [BodyOfWater] in0, in [BodyOfWater] in1, out [BodyOfWater] merged)
  affordance dom
  description `Merge 2 input bodies of water ${arg0} and ${arg1}`

```

Won't work - the particle names don't match in the 2 declarations (MergeBodiesOfWater != ShowBodiesOfWater), and the arguments in the description won't resolve ( (in0,in1) != (arg0,argv1) ).

If possible, we should give the user load-time errors that this particle definition won't work with as much detail as possible so they can fix it easily.

We may also want to think about removing the need to state the particle name twice as it's an opportunity to make mistakes like this.

**Comment by shans** [comment]
Maria: do you want to take the description side of things and I'll make sure that a particle manifest without at least 1 definition won't load?

**Comment by mmandlis** [comment]
Shane, sg, or I can do both.
