### ISSUE TITLE
Nested handles inside recipes don't resolve.

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#3630]
If you do something like

```
recipe foo
  Particle
    in a
      out b
```
then `out b` never resolves. Weird, huh?

**Comment by mmandlis** [comment]
i'm confused, is this particle spec nested inside a recipe?

**Comment by Cypher1** [comment]
I think the example I saw was something more like
```
particle Parent
    in a
        out b
particle Child
    in c

recipe foo
    Parent
        a <- outer
            b -> shared
    Child
        c <- shared
```

And this wasn't resolving.

(This is here as a reminder for me to test this properly.)

**Comment by Cypher1** [comment]
Closing as no-repro (once I used the correct fate). As the user involved, I'm dismissing this as user error.
