### ISSUE TITLE
Outdated manifest persists in WebShell

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#3715]
I was updating a manifest to have a particle point to `move` instead of `humanMove`, but the changes did not seem to be propagating through. The graph in Arcs dev tools explorer was showing the particle still pointed to `humanMove` instead of `move`. Refreshing the page did not solve the issue, nor did hard reload or empty cache and hard reload. After clearing the cache, cookies, indexed DB, and local storage, the graph pointed to `move` and the program executed as expected.

**Comment by shaper** [comment]
Is there a clear repro here?

**Comment by sjmiles** [comment]
I accidentally closed this, but it may be the best move since some time has passed and it doesn't seem to be a chronic problem?
