### ISSUE TITLE
Build machinery to place Arcs artifacts in APK assets/

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#3819]
Create a mechanism via which:

* WASM modules being the output of the isolated Kotlin and Cpp particle compilation end up in the APK's assets/ folder.
* Arcs manifests containing recipes implementing a given feature (and a transitive closure of manifests imported by that manifest, json stores and ideally JS particles) end up in the APK's assets/ folder.
* A root manifest consisting of import statements of all the manifests for separate features gets generated and end up in the APK's assets/ folder.

Ideally at compile time we ensure that if we put an arcs manifest in the assets/, we also put all the manifests this manifest imports as well as all the particles this manifest references.

Some agreed on technicalities:

* We will use fully qualified paths, e.g. if a manifest is /bazel-root/a/b/c/Manif.arcs, it should end up as /assets/a/b/c/Manif.arcs.
* WASM modules are placed in the at their fully qualified path without any prefix related to the build system (e.g. `bazel-bin`).

E.g.
For the following directory structure:
```
/a/b/c/Feature.arcs
/a/b/c/HelloParticle.kt
```
and the following build output (assuming bazel)
```
/bazel-bin/a/b/c/HelloParticle.wasm
```

the manifest should reference the wasm module in the following way (see #3666):
```
particle HelloParticle in `HelloParticle.wasm`
  (...)
```

and the assets/ structure should be:
```
/a/b/c/Feature.arcs
/a/b/c/HelloParticle.wasm
```

**Comment by piotrswigon** [comment]
An additional requirement from #3821:

The generated root manifest (`Root.arcs`?) needs to be present on disk after performing APK Build. This is in order to load it when we switch to loading artifacts from the development machine.

It doesn't matter much where it ends up (somewhere in bazel-(bin|out|genfiles)?), ALDS will map the paths so that it all works, but it needs to be there somewhere.

**Comment by csilvestrini** [comment]
#3875 was just submitted, which generates a root manifest and bundles everything up into a filegroup. In theory, you should be able to include that in an android assets folder.

However, it is not preserving the directory structure correctly. We wanted to keep the repo directroy structure so that everything inside the assets folder uses the same repo paths. Instead we have this:

```
Archive:  android_files/assets.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  1980-01-01 00:00   assets/
      685  1980-01-01 00:00   assets/Harness.arcs
      197  1980-01-01 00:00   assets/bundle.arcs
      533  1980-01-01 00:00   assets/example.arcs
   120791  1980-01-01 00:00   assets/example_particle.wasm
       17  1980-01-01 00:00   assets/nested.arcs
       25  1980-01-01 00:00   assets/nested.js
   920809  1980-01-01 00:00   assets/test_particle.wasm
    18519  1980-01-01 00:00   assets/test_particle.wasm.js
---------                     -------
  1061576                     9 files
```

(in this example, `nested` was a folder elsewhere in the repo)

This does not have an obvious fix...

**Comment by piotrswigon** [comment]
Is this caused by how bazel treats filegroups?

**Comment by csilvestrini** [comment]
Pretty much, yep. I've been playing around with it, and have had some luck with zipping/taring the files and preserving the directory structure, but then the files are zipped up inside the android assets folder, and you won't be able to load them individually with file://android_assets/...

**Comment by csilvestrini** [comment]
Found a potential workaround: https://yaqs.corp.google.com/eng/q/5704916260356096

**Comment by piotrswigon** [comment]
Shall we make the Demo app use these new rules and then consider the issue done? WDYT @csilvestrini

**Comment by csilvestrini** [comment]
Yep! That's what I'm aiming for :-)
