### ISSUE TITLE
Tweak strategy-explorer and suggestions-element so they can be reused in multiple contexts

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#382]
The strategy-explorer and suggestions-element modules provide Web Components that we want to use in applications and environments beyond runtime/browser/demo*. 

There are a few minor bits that need tweaking to support flexible reuse (mostly, removal of `require` and some minor factoring).

I mentioned in a team meeting that this code was **forked** in arcs-cdn. I think this was misunderstood to mean the design of functionality was altered, but really the changes were only to enable reuse as above. With this issue resolved, the code in this repo can be The Source of Truth and the arcs-cdn will contain only build artifacts.

**Comment by shaper** [comment]
Obsolete with much code shuffled and reworked since, AFAIK.
