### ISSUE TITLE
go/arcs-live is down

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#3838]
with error:
`wasm.js:17 GET https://live.arcs.dev/build/runtime/bimap.js net::ERR_ABORTED 404`

**Comment by mmandlis** [comment]
assigning to @mykmartin who added this class, please, reassign as appropriate.

**Comment by mykmartin** [comment]
Weird... looking now.

**Comment by mykmartin** [comment]
So bimap.ts is in the live repo: https://github.com/PolymerLabs/arcs-live/blob/master/src/runtime/bimap.ts

..but not in the build dir: https://github.com/PolymerLabs/arcs-live/blob/master/build/runtime/bimap.js

There doesn't seem to be anything in our travis.yml config or the Travis web console that would cause this, and Travis is green for the last couple of PR builds. 

Looking at https://github.com/PolymerLabs/arcs-live/blob/master/build/tsconfig.tsbuildinfo, bimap.ts is present under `fileInfos`, `referencedMap` and `semanticDiagnosticsPerFile` but missing from `exportedModulesMap`. By comparison, wasm.ts is in all of them.

I have no idea what could be causing this...

**Comment by shaper** [comment]
Arcs-live is still failing but quite differently. closing this.
