### ISSUE TITLE
Dismantle *dom* machinery and tests

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#3839]

**Comment by shaper** [comment]
Is this dismantling, or removing? Does this including adding tests for the new UI Broker logic, or is there a separate issue for that?

**Comment by sjmiles** [comment]
It’s _dismantling_ because these concepts are not entirely isolated and vestigial code and tests need to be carefully extracted so I don’t inadvertently affect necessary code or accidentally nerf tests.

I think I should make a separate PR for writing new tests. It was not obvious at first, but the test coverage also has mixed concerns so there is overlapping work. Iow, aiming to end up with similar coverage requires identifying the scope of the removed tests, which will take some time.

**Comment by sjmiles** [comment]
Largely accomplished.
