### ISSUE TITLE
Make loader configurable by ArcsService

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#3915]
We likely need an API exposed by the Pipes Shell to Arcs Service that allows configuring the loader. I imagine that we could have a loader configuration like this:
```
{
  'https://$internal/': 'file:///android_asset/',
  'https://$external/': {
    root: `http://${host}:${port}/`,
    buildDir: 'bazel-bin/',
    buildOutputRegex: /\.wasm$/,
  }
}
```

The developer would be able to switch between $internal and $external depending on whether they want to load particles and recipes they modify on their machine, or whether they want ones embedded in the APK. This is described in #3821 BTW.

We don't really need`$internal`, as we can use file:///android_asset/ URLs directly.

However, we **do need** $external as opposed to loading from http://localhost:8786/ directly, as $external has the special sauce that redirects loading of .wasm files from bazel-bin.

Now, we could hardcode http://localhost:8786/ in the pipes-shell.js, but it's bad manners, as:

* The developer may want to use a different port (they already may have something on 8786)
* The developer may want to use a different host (e.g. when running an Android app in the emulator we can use the IP directly)

So, given that the port (and maybe host) needs to be overridable with some runtime settings / properties, ArcsService needs to be able to configure the loader. Some API to be called before or during initialisation seems like a way to go. Thoughts?

**Comment by sjmiles** [comment]
Done in #3925
