### ISSUE TITLE
Look for preponderance opinion on Runtime statics

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#3999]
Runtime.ts currently uses a gambit where the most recent instantiated runtime object (or a freshly created one) is the target of static methods.

I find this an ergonomic benefit as most (all, at the moment) of our apps only need a single runtime configuration (it generally represents the relationship of the application with the filesystem). Otherwise, we'd have to plumb dozens of `runtime` arguments through the system.

Other perspectives find this surprising and would prefer to not use this pattern.

Would be good to have some more folks weigh in.

**Comment by shans** [comment]
I actually intend this to be an interim measure only; the idea is that we gradually plumb the runtime through (but remove a bunch of "opts" args at the same time, so things get better), then when we finally have no global state we can make explicit construction of a Runtime object part of the lifecycle control.

**Comment by sjmiles** [comment]
Cool, thanks for the note, see #4136.
