### ISSUE TITLE
codelab

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#401]
A codelab that takes a developer through developing an initial flow.

One suggestion is the Greeting demo - walking through building that (is https://github.com/sjmiles/arc-stories/tree/master/artifacts/HelloWorld the canonical version?)

Maybe at the end, though, drop in a link to all of our other particles and have all this cool stuff just happen. @sjmiles had an experience like this when he dropped a link to @noelutz's video manifest into one of his manifests - all of a sudden it became much more capable.

**Comment by shaper** [comment]
Larger work item in future around developer documentation, SDK, tutorial. Closing in deference to that future workstream.
