### ISSUE TITLE
Add Android SDK to `Dockerfile.CI` to enable Android tests/builds in Travis

### ISSUE THREAD

**Issue by alxrsngrtn** [PolymerLabs/arcs#4026]
Also, can we add Android SDK to it? This'll make it easy to enable Android tests/builds in travis later.

_Originally posted by @cromwellian in https://github.com/PolymerLabs/arcs/pull/4008_

**Comment by csilvestrini** [comment]
Closing in favour of #3968 which predates it (and has slightly more info)
