### ISSUE TITLE
particles/Native/Kotlin Folder 

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#4035]
Are we still using any of the code in particles/Native/Kotlin? If not, is it time to delete it from the repo to remove unused code?

(Both open questions 😄 )

**Comment by cromwellian** [comment]
I'm going to repurpose it. There's some coroutine oriented APIs in there that I want to play with to see if i can get them running again in wasm, and if so, move them to src/wasm/kotlin
