### ISSUE TITLE
CRDTs must return empty operation lists when merging results in no change

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#4037]
The CRDT merge `target.merge(subject)` method always returns a two-sided update that represents the things that need to be applied to the target (`modelChange`) and the subject of the merge (`otherChange`). The notion is that modelChanges get sent on in "the same direction" and otherChanges get sent "back".

A change can be a list of operations, or a model.

Because otherChanges get sent back, it's critical that null changes (i.e. everything in the target was already in the subject) are communicated as empty operation lists rather than a model, because if a model is sent back then we enter into an infinite merge loop.

You can see addition of this behaviour in TS in #4000; that's a large patch so you might want to look specifically at:
https://github.com/PolymerLabs/arcs/pull/4000/files#diff-d8448d5e20f73164c9830d60af835eeb (the change to collection CRDTs)
https://github.com/PolymerLabs/arcs/pull/4000/files#diff-5120055127f1b50e0a3bd40de5241ce8 (the change to singleton CRDTs)
https://github.com/PolymerLabs/arcs/pull/4000/files#diff-e3a9fd8023c45cefa89447f3dffcb51a (some utilities for null changes)
https://github.com/PolymerLabs/arcs/pull/4000/files#diff-f881f7c9ac41f37fb46f006603ff2aaf (a test for the collection behavior.

We'll need to implement this for both the Kotlin and the Java CRDTs.

**Comment by jasonwyatt** [comment]
I think once #4052 and #4049 are merged, we'll be good-to-go on the kotlin side.

**Comment by jasonwyatt** [comment]
I'll mark this as finished for now, since we are going to have javaharness use the kotlin CRDTs.
