### ISSUE TITLE
no error when mixing up <-, ->, or =

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#404]
When a view is linked in an incorrect direction, the recipe is silently skipped. We should provide more feedback to developers (since the system knows that there's a conflict between the particle definition and how the recipe has been wired).

**Comment by mmandlis** [comment]
Theoretically it is possible to have 2 particles with the same name that have different directions view connections. For example (as far-fetched as this example may seem):

particle SomeParticle
  SomeParticle(in Foo foo)
and 
particle SomeParticle
  SomeParticle(out Foo foo)

so the direction <- or -> is an indication which of the 2 particles should really be used.
if the recipe author doesn't care about the direction, = should always work (please, file a bug, if it doesn't)
