### ISSUE TITLE
* not working for slots in new syntax

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#4043]
Specifically, trying `root: consumes *` for a parent particle or `ui: consumes *` for a child particle fails. Error message from the console (Web Shell) below:

![image](https://user-images.githubusercontent.com/3030811/68496932-4216b600-0208-11ea-842f-2be6ba057983.png)

**Comment by Cypher1** [comment]
Thanks Sarah, please post the manifest that this is showing up in. I can't use the error message to debug without more information.

If this is in a particle, the new syntax does not support this for Slots (as slots do not actually have a type, we're simply using the `Slot` vs `[Slot]` type markings to differentiate between slots and set slots.

If this is in a recipe particle, then no * is needed, or expected.

I believe this is working, but I'd like to be able to test it before saying more.

**Comment by SHeimlich** [comment]
Created an MVP branch: https://github.com/SHeimlich/arcs/pull/new/star-slot-error

Also see screenshot:

![Screen Shot 2019-11-14 at 10 22 43 AM](https://user-images.githubusercontent.com/3030811/68884874-eeeda900-06c8-11ea-8289-714864ebf9bf.png)

**Comment by Cypher1** [comment]
Finally got to look into this a bit more. As I've implemented it, the 'foo: consumes *' notation was only for the annotation of Ids in recipe handle and slot declaration.

The intended usage, currently, is to leave off the '*'.

I'm going to close this for now but plan to revisit it as part of v2.
