### ISSUE TITLE
sigh from clean start fails to run Wasm integration test

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#4044]
After https://github.com/PolymerLabs/arcs/pull/4040 running `./tools/sigh` runs wdio tests which include a Wasm test for Kotlin Tutorial 1. However, sigh does not currently run bazel build and thus the .wasm file required is missing and the test fails.

I know we want sigh to not trigger bazel. Should there be a new team-adopted way to 'run and test all of the things locally via bazel'? @csilvestrini @mykmartin

**Comment by raulverag** [comment]
No. It's real. I had to run Bazel to build the Kotlin stuff to get the test to pass, but then didn't connect the fairly obvious dots to realize that this makes a sigh dependency on Bazel, which we know we don't want. The short-term solution would be to move the test in question into Bazel, perhaps via a flag or env variable in sigh in order to reuse the existing sigh infrastructure.

**Comment by csilvestrini** [comment]
The `arcs_ts_test` rule already does this. It lets you run a test via `bazel test ...`, which then gets executed using `sigh` using a special `--bazel` flag that gets passed in to sigh.

Here's the definition of `arcs_ts_test`:

https://github.com/PolymerLabs/arcs/blob/6c72e65535742e3bdf6a113b22b071c9d00e1e32/third_party/java/arcs/build_defs/build_defs.bzl#L43

And here's the special handling in sigh for that flag:

https://github.com/PolymerLabs/arcs/blob/8338417fa8d490cd7c993c77e124acfb625e0372/tools/sigh.ts#L660

And here's one of the tests where it's used:

https://github.com/PolymerLabs/arcs/blob/e94ea120d5920cf628382556c7ad611612f459b8/src/tests/hotreload-integration-test.ts#L174-L176

You could add something similar for wdio tests.

**Comment by raulverag** [comment]
Perfect. Thanks, Cameron. I'll fix this today then.

**Comment by raulverag** [comment]
Actually, this isn't as simple as I thought. Sigh runs the shell tests just by spawning a wdio (i.e. Chromedriver) process, which is speced to run a set of tests, one of which requires Kotlin. This is all in shell-land, not sigh. Which means that this is not a new problem. The npm tests did the same thing and would have failed without a prior bazel build too. I'm going to ask around for opinions on how to restructure in order to fix this, as I don't think it's obvious.

**Comment by raulverag** [comment]
So it seems that if the shell tests rely on both the sigh build and the bazel build, and we accept bazel calling sigh but not sigh calling bazel, then the shell tests should be run via a bazel command, not a sigh command. But the only way I know of firing up both a server and a test client from bazel would be to write a wrapper that does them, which we actually already have with sigh. So I propose changing the new testShells and testWdioShells sigh commands to work only from bazel, and add bazel targets to run them from bazel, with the correct build dependencies.

**Comment by csilvestrini** [comment]
The way it works with unit tests is:
1. Running `sigh test` without arguments will run all of the "non-bazel" unit tests
2. Running `bazel test` will run `sigh test --bazel` for each "bazel test". Only tests flagged as requiring bazel should be run.

We can do the same thing here. Running `sigh testWdioShells` could run all of the non-bazel wdio tests, and then bazel can invoke `sigh testWdioShells --bazel` to run the bazel-only variants. That would let us continue to use sigh only to run all the tests that don't depend on bazel.

**Comment by raulverag** [comment]
Sure, I understand the sigh plumbing, but this isn't a matter of sigh plumbing. The tests are laid out in a single file referenced by wdio-conf.js and run all together as a single Chromedriver run. To make use of the sigh plumbing I will have to refactor the Chromedriver tests. The solution I proposed above is simpler (in fact it's part of your suggestion), with the caveat that all the Chromedriver tests would have to be run from bazel.

**Comment by raulverag** [comment]
Mick has suggested just checking in a WASM binary for integration testing purposes, so I think I'm going to do that. We can revisit when the bazel/sigh interaction evolves.

**Comment by raulverag** [comment]
#4065 Implements Mick's suggestion, and fixes this issue.
