### ISSUE TITLE
arcs_kt_schema failing across multiple files

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#4046]
If schemas are defined in one *.arcs file, and used in a second *.arcs file, the build fails. Log reads:

```
INFO: Analyzed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 4 targets...
INFO: From Generating Kotlin entity schemas:
Could not find any particle connections with schemas in 'particles/Tutorial/Kotlin/5_Collections/CollectionsSchemas.arcs'
log-factory: binding logFactory to level [0]
bazel-out/darwin-fastbuild/bin/particles/Tutorial/Kotlin/5_Collections/CollectionsSchemas_GeneratedSchemas.kt
ERROR: /Users/sarahheimlich/Documents/GitHub/arcs/particles/Tutorial/Kotlin/5_Collections/BUILD:3:1: output 'particles/Tutorial/Kotlin/5_Collections/CollectionsSchemas_GeneratedSchemas.kt' was not created
ERROR: /Users/sarahheimlich/Documents/GitHub/arcs/particles/Tutorial/Kotlin/5_Collections/BUILD:3:1: not all outputs were created or valid
INFO: Elapsed time: 5.530s, Critical Path: 4.56s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
```

I was able to reproduce the bug quite easily, see https://github.com/SHeimlich/arcs/tree/arcs_schemas-bug

**Comment by alxrsngrtn** [comment]
I just checked the diff. 

You should try referring to the name of the schema gen rule (i.e. `:collections_schemas`) and not the name of the produced artifact.

**Comment by alxrsngrtn** [comment]
For example, try writing the rule like [this](https://github.com/SHeimlich/arcs/blob/b0200e5605455824b1fa2653445b7eebd4e668f6/particles/Native/Wasm/BUILD#L40).

**Comment by SHeimlich** [comment]
I think that's how I'm writing the rule?

What I've got:
```
arcs_kt_schema(
    name = "collections_schemas",
    srcs = ["Collections.arcs"],
    srcs = ["CollectionsSchemas.arcs"],
)

arcs_kt_binary(
    name = "Collections",
    srcs = ["Collections.kt"],
    deps = [":collections_schemas"],
)
```

My understanding was the dependency on `:collections_schemas` in the `arcs_kt_binary` rule is referring to the produced artifact. Is this correct? Should I be doing this differently?

**Comment by alxrsngrtn** [comment]
This looks correct.

**Comment by alxrsngrtn** [comment]
To translate the difference to my understanding of bazel: The manifestation of the artifact could be anything. Internal to the `arcs_kt_binary`, we indicate to the build system that one file is produced and there are n transitive dependencies (see [Providers](https://docs.bazel.build/versions/master/skylark/rules.html#providers)). This knowledge gets used to plan an efficient build (in the creation of an action graph) before execution. 

By referring to the name of the rule (`:collections_schema`), you're informing the build system of a dependency relation. How many times it creates the artifact, what the file is called, etc. are implementation details.

**Comment by alxrsngrtn** [comment]
If in the future, `arcs_kt_schema` produces more than one file, or the file name changes, the rule that you have written won't need updating. `arcs_kt_binary` will know to depend on everything produced by `arcs_kt_schema`.

**Comment by SHeimlich** [comment]
Oops, sorry. Copy-pasta error. I copied the diff. There is only one srcs as you suggested. I've edited above, but just for clarity, the rules are:
```
arcs_kt_schema(
    name = "collections_schemas",
    srcs = ["CollectionsSchemas.arcs"],
)

arcs_kt_binary(
    name = "Collections",
    srcs = ["Collections.kt"],
    deps = [":collections_schemas"],
)

```

**Comment by alxrsngrtn** [comment]
I see what the issue is now. 
The schema generator only generates schemas for particle connections. If a manifest file has no particles (and thus no connections), we don't generate anything. That's why you're getting the `not all outputs were created or valid` error.

**Comment by alxrsngrtn** [comment]
If you change the target manifest to `Collections.arcs`, it will work.
In any case, this indicates that the schema2pkg is not documented well enough.

**Comment by alxrsngrtn** [comment]
Sorry Sarah, I've misunderstood you. I misread the diff, sorry for the confusion.

**Comment by alxrsngrtn** [comment]
This has been addressed.
