### ISSUE TITLE
Change DomParticle API names (React-like method names not particularly helpful esp. to Polymer folks)

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#405]
DomParticle (maybe should be SimpleParticle?) uses some React-like concepts (external props vs internal state, asynchronous validation [rendering]) and so I chose sort-of React-like names for some methods/parameters. 

At this point I think choosing naming that better reflect the true API is more important to reducing weirdness than trying to hint at similarities to other tools. 

In the same vein, the use of `_` on methods is a reflection of good Custom Element practice. Although there certainly are similarities between Particles and Custom Elements, I believe the usage of `_` is just weirdness at this point and should be eliminated.

**Comment by smalls** [comment]
Nice! I'm going to mark this closed with the last batch of changes unless there's more to do, @sjmiles?
