### ISSUE TITLE
Store was not found in volatile storage in dev shell

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#4078]
I have a particle that loads data from a store defined with in the Arcs manifest file. Trying to load a recipe that relies on this store in the devshell results in this error message.

<img width="1676" alt="Screen Shot 2019-11-14 at 5 03 46 PM" src="https://user-images.githubusercontent.com/3030811/68908977-b28a6f00-0701-11ea-88af-c65cdf8dbb96.png">

**Comment by sjmiles** [comment]
I'm happy to look into this, but I need more repro information.

DevShell's default recipe has a _store defined within the manifest_ and it seems to work, so I'll need more details.

**Comment by SHeimlich** [comment]
If you pull from https://github.com/SHeimlich/arcs/tree/kt-wasm-out-of-bounds and load `particles/Tutorial/Kotlin/Demo/TTTGame.arcs` in the dev shell, you should get the error.

**Comment by sjmiles** [comment]
Think this is stale, re-open as needed.
