### ISSUE TITLE
Uncaught Error in WebShell

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#4079]
Loading webshell results in an error message that blocks loading recipes:
```
Uncaught (in promise) Error: Type of 'id' does not match schema ([object Object] vs [object Object])
```

**Comment by sjmiles** [comment]
Can't reproduce here, are there any steps other than loading web-shell?

**Comment by Cypher1** [comment]
Sorry, what was the resolution for this error? I've seen it once or twice before so I'm happy to call it confirmed, though I do not have a repro.

We (at minimum) should have the error print the types in a human readable way.

**Comment by SHeimlich** [comment]
I saw this again today. After some playing around I was able to get it to go away by switching back to volatile memory from firebase. Not sure how that is related... but I have not seen the error since.
