### ISSUE TITLE
entityClass constructor doesn't take parent type properties into account when using schema.org

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#417]
Unfortunately I don't have a good repro for this, but the entityClass method doesn't seem to take properties of parent types into account.

My rawData looks something like this:

`{description: "Shop at the Google Store for Android phones and ta…hromecast, Nest, plus a selection of accessories.", offers: Array(13), name: "Pixel"}`

The description element is inherited by http://schema.org/Product from http://schema.org/Thing. However, in Schema.entityClass() (~schema.js:67), properties is:

`["color", "gtin12", "gtin8", "model", "gtin14", "gtin13", "sku", "award", "mpn", "productID", "material", "category", "awards", "logo"]`

These are only direct properties of schema.org/Product.

**Comment by smalls** [comment]
The codepath that I reached this on was using JSON.stringify(o), where 'o' is an instance of the Product entity.

**Comment by smalls** [comment]
I don't see the issue when using schema defined in our manifest files.

**Comment by shans** [comment]
This was an interesting one. There seems to be a bug in the way schema.org generates structured representations - we were _loading_ Thing correctly but it didn't contain anything useful.

I've worked around the issue for now by reconstructing Thing from the representation of Product.
