### ISSUE TITLE
tools/setup is broken on linux workstations

### ISSUE THREAD

**Issue by jasonwyatt** [PolymerLabs/arcs#4178]
From the logs:

```
99 silly lifecycle   'cross-env tools/sigh check && cd devtools && npm install' ]
100 info lifecycle arcs@0.0.0~prepare: Failed to exec prepare script
101 verbose stack Error: arcs@0.0.0 prepare: `cross-env tools/sigh check && cd devtools && npm install`
101 verbose stack spawn ENOENT
101 verbose stack     at ChildProcess.<anonymous> (/usr/local/google/home/jwf/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
101 verbose stack     at ChildProcess.emit (events.js:189:13)
101 verbose stack     at maybeClose (internal/child_process.js:970:16)
101 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
102 verbose pkgid arcs@0.0.0
103 verbose cwd /usr/local/google/home/jwf/github/arcs
104 verbose Linux 4.19.67-2rodete2-amd64
105 verbose argv "/usr/local/google/home/jwf/.nvm/versions/node/v10.15.3/bin/node" "/usr/local/google/home/jwf/.nvm/versions/node/v10.15.3/bin/npm" "install"
106 verbose node v10.15.3
107 verbose npm  v6.13.1
108 error code ELIFECYCLE
109 error syscall spawn
110 error file sh
111 error errno ENOENT
112 error arcs@0.0.0 prepare: `cross-env tools/sigh check && cd devtools && npm install`
112 error spawn ENOENT
113 error Failed at the arcs@0.0.0 prepare script.
113 error This is probably not a problem with npm. There is likely additional logging output above.
114 verbose exit [ 1, true ]
```

**Comment by shaper** [comment]
The very first "Install dependencies" step looks to be failing at "prepare", and it does `cross-env tools/sigh check && cd devtools && npm install`, so it's like it doesn't have `cross-env` module installed yet, but I see it in `devDependencies` and AFAIK those are supposed to be installed before the `prepare` step.

Also, I wonder what changed, since this used to work (and works for me currently).

@jasonwyatt perhaps try running the equivalent of [this script](https://github.com/PolymerLabs/arcs/pull/4177/files#diff-1bfe00e1e6f80f01276e2d9c65a03a94) and then re-running setup?

I also see in your fuller log this bit prior to the `cross-env` issue: `<excerpted>/.nvm/nvm.sh: line 148: 192980 Aborted                 $NVM_NPM_CMD install -g npm`

**Comment by alxrsngrtn** [comment]
An unrelated issue: 
At the end, sigh prompts the user to "Serve the project: `npm start`", but we moved to `tools/sigh devServer`.

**Comment by alxrsngrtn** [comment]
Why are we using `cross-env`? It seems like it's there to solve a problem that we don't have: https://github.com/kentcdodds/cross-env#the-problem (specifically, we are not setting environment variables). 

I've tested removing it on my machine, and the install works fine. 

Removing cross-env is a nuclear option, but it sounds like it would resolve the issue.

**Comment by shaper** [comment]
We typically were using it to allow Unix-like shell commands on Windows. `tools/sigh check && cd devtools && npm install` won't do the right thing in a Windows command shell for example. I am sure we could structure what we do prepare-wise to work around differently though.

**Comment by shaper** [comment]
@jasonwyatt this is the issue tracking what we looked at together earlier this week, the next step we thought was to try fully removing your current nvm/npm install and reinstalling as user, not sudo, if that's feasible, or whatever is needed to fix the "Aborted" that seems to happen with your npm commands currently.

**Comment by shaper** [comment]
If it remains broken perhaps @piotrswigon can look at it with you in person at some point.

**Comment by jasonwyatt** [comment]
I attempted fully-removing npm/nvm and was still running into issues. Will chat with Piotr soon.

**Comment by jasonwyatt** [comment]
Closing this. It seemed to be an issue with some conflicting Node versions on my workstation and isn't a common problem on all linux workstations.
