### ISSUE TITLE
Parser does not accept multi-line types

### ISSUE THREAD

**Issue by Cypher1** [PolymerLabs/arcs#4219]
Tracking the potential need for allowing multi-line syntactic structures (such as types) in manifests.

Currently, long inline schemas become very tedious (e.g. in `particles/TicTacToe/particles/MoveApplier.arcs` we have a handle connection definition like so:

```
  boardResult: writes Board {p00: Number, p01: Number, p02: Number, p10: Number, p11: Number, p12: Number, p20: Number, p21: Number, p22: Number}
```
 ).

This is unsustainable and gets worse with refinement types and other 'read world types' that have a lot of type information.

My feature request is to introduce multi-line types and I think, for consistency, this should mean that we introduce bracketed stanzas (instead of just using indentation).

This bug is to track this request and work on the parser if the feature request is accepted.

Note: With a non-indentation based syntax we would allow
```
  boardResult: writes Board {
     p00: Number,
     p01: Number, 
     p02: Number,
     p10: Number,
     p11: Number,
     p12: Number,
     p20: Number,
     p21: Number,
     p22: Number
  }
```

**Comment by Cypher1** [comment]
I believe this has actually been fixed for inline schemas @piotrswigon 

I've got a PR here: https://github.com/PolymerLabs/arcs/pull/6521
That I think fixes it for top level schemas but I need to do more testing.

Is my memory correct @piotrswigon ?

**Comment by piotrswigon** [comment]
It's definitely fixed for inline schemas. I don't know about declaring inline entities or references in "external" schemas, e.g.

will this work?
```
schema Person
  address: inline Address {
    postCode: Text,
    streetNumber: Number
  }
```

**Comment by Cypher1** [comment]
Adding tests and parser support here:

https://github.com/PolymerLabs/arcs/pull/6521

**Comment by Cypher1** [comment]
Landed via the bot (which meant that the linked PR didn't auto close this issue).
Thanks @piotrswigon
