### ISSUE TITLE
Video suggestion doubled, doubled slot connections?

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#428]
[Reproduce here](https://polymerlabs.github.io/arcs-cdn/dev/app/?solo=https://noelutz.github.io/arcs-stories/artifacts/VideoPlayer/VideoPlayback.manifest&nokey)

Noe's video recipe produces duplicate suggestions:
```
Control video and show video.
Control video and show video.
```

I don't know if this matters, but I noticed strategy explorer shows, at one point, the two particles are both mapped to `slot0` which is the root slot, in another they are mapped to `slot0` and `slot1` (both are still exactly the root slot)

Scenario 1:
```
  slot 'rootslotid-root' as slot0`
```

Scenario 2:
```
  slot 'rootslotid-root' as slot0
  slot 'rootslotid-root' as slot1
```

**Comment by mmandlis** [comment]
as a work around you can add "consume root" to the recipe, ie:
```
recipe
  copy #ctrl as controls
  ControlVideo
    controls = controls
    consume root
  ShowVideo
    controls <- controls
    consume root
```

and/or i'll send a PR with the real fix shortly.

**Comment by sjmiles** [comment]
We've been living with this for a long time, it's not an emergency. I just finally looked at it a bit more closely.

> fix shortly

Thanks (you rock)!
