### ISSUE TITLE
Copybara check missing for some PRs

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#4399]
There are no Copybara check(s) on https://github.com/PolymerLabs/arcs/pull/4395 but it modifies `runtime.ts` and AFAICT that should have prompted a check. I reviewed our copybara config briefly, but perhaps this is configured elsewhere. @csilvestrini can you provide input (not a high priority per se unless it's happening often to many folks).

**Comment by csilvestrini** [comment]
It's hard to diagnose what went wrong after the PR has been merged.

If it happens again, I'd recommend doing a manual presubmit to see what goes wrong (if anything).

**Comment by csilvestrini** [comment]
If you have another example PR please reopen.
