### ISSUE TITLE
we need a way to import code into particles from shared places

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#440]
The URL is document-relative by default, so we need a way to override that. Perhaps this might go in DomParticle.

**Comment by sjmiles** [comment]
There is an object passed to DefineParticle called `resolver` that can do this work. Example from Words/GamePane.js

```
importScript(resolver(`GamePane/Tile.js`));
```

If the input path is prefixed by the name of the running Particle, `resolver` will return a path relative to that Particle's `.js` file. In the example above `GamePane` is the running Particle, and it will import a peer file called `Tile.js`.

`resolver` supports the Shell's url-mapper, so e.g., `https://$cdn` as a prefix will resolve relative to the active `shell/` folder for the running process.

`resolver` will be `undefined` if the code is not running in a browser environment.
