### ISSUE TITLE
Don't fail linking files at racing sigh builds

### ISSUE THREAD

**Issue by ianull** [PolymerLabs/arcs#4465]
Current sigh build links src/... to build/... by checking symbolic link existence and file stats under build/... first then creating a symbolic link accordingly.

Travis triggers multiple build targets that executes 'tools/sigh build' concurrently
which may cause racing condition where multiple build tasks are racing to create the symbolic links turns out EEXIST exceptions raised at some of these build tasks.

We need to consider such condition by warning users rather than failing build tasks immediately.

**Comment by shaper** [comment]
Another example I just hit:
https://travis-ci.org/PolymerLabs/arcs/jobs/638131508?utm_medium=notification&utm_source=github_status

If it looks like it will take long enough to move to another CI to warrant, we may want to review/update Travis build to prevent this race config/job-wise.
