### ISSUE TITLE
Syshealth: unregister zombie handle listeners

### ISSUE THREAD

**Issue by ianull** [PolymerLabs/arcs#4475]
### **Background**
A readable handle associating with its particle would initialize storage proxy (bound to that handle) which registers a listener to underlying storage. Subsequent data changes notify all registered listeners of the CRDT updates sequentially in their registered order. Arcs supports multiple types of particles i.e. factory, Android, etc but none of them unregister listeners even if their associating Arcs have already be completed (stopped).

### **Problem**
Say there is an ingestion Arc who keeps ingesting new data to Arcs storage and there are also one or few pull/push Arcs who are consuming the data. The number of listeners which are registered during their particles' instantiation keep increasing but never decreases, which results in serious consequences:
* Storage is iterating and notifying bunches of zombie particles; more the zombies, slower the 
   iteration.
* Memory/listeners leakage potentially cause OOM.
* If a listener was registered by an Android particle, the callback message is IPC'ed to a single
  and shared JavaBridge thread blocking and/or starving other communications. The rocketing 
  number of IPCs significantly hurts system health imponderably.
* If a receiving PEC or particles were not closed/destroyed properly, crash or anomalies may take 
  place randomly and unexpectedly.

### **A Case-Study**
Take the demo Autofill application as example:
- Press the 'Capture Person' should ingest a random person into Arcs runtime storage.
  The person handle is defined as "reads writes" which would registers a listener to storage.
- Tap the TextBoxes of Name/Password/Phone/Address would instantiate two particles, one of 
   them (DummyAutofillResponder) consumes the recently ingested person so a listener is 
   registered to the storage as well.

### **Experiment**
Press 'Capture Person' 6 times and tap the Name TextBox 5 times.

### **The Expected Result**
The Capture Person ingests to the same storage by reusing the same handle
= listener * 1
The DummyAutofillResponder is stopped via stopArc() API so expect to see its listener is unregistered at the stop flow. 
= listener * 0

Total number of listener = 1

### **The Actual Result**
Total number of listener = 11 (see the top-right rectangle)

The top-left rectangle shows where I put the breakpoints at.
The bottom rectangle shows Arcs runtime sent bunches of the **completely identical** messages to the Android particle via a message bus (here it's via a single and shared JavaBridge thread)

<img width="1201" alt="Screen Shot 2020-01-17 at 1 25 17 PM" src="https://user-images.githubusercontent.com/55406481/72594500-70b8b780-3942-11ea-8b99-b7a03873c77a.png">

**Comment by ianull** [comment]
@piotrswigon @shaper 
I do think we need this on devex.
It's not only a system-health optimization but also a critical resource leakage that must be addressed.

I'm still going on my CNY vacation for the next two weeks.
If no one wants to pick it up, I'll love to get my hands on it post-vacation.

**Comment by yuangu-google** [comment]
I also found this issue when I was running a simple robustness test. I think @sjmiles might be looking at this too.

**Comment by ianull** [comment]
@yuangu-google great! Would you mind sharing your robustness test here?
I'm not pretty sure if they are the same symptom as the listener here is what we create
at storage stack for listening to changes on a handle rather than system listeners on dom, xhr, etc. 
But they could be the same issue to some degree, here is a possible theory:
--
each update-callback is registered as a closure like: { this.XXX(...) }
The 'this' holds one side of messaging channel, which is an instance of MessagePort.
The port holds a system listener as port.onmessage(...)
The system listener keeps alive until we close the port or reassign the onmessage property to null.
--

**Comment by ianull** [comment]
@sjmiles I created a quick fix for this. Please review if it makes sense to you! Thanks.
