### ISSUE TITLE
transition to schema.org in our standard demos

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#450]
Instead of using hardcoded schema defined in manifest files we should import from schema.org

**Comment by noelutz** [comment]
Noticed a couple of issues with importing simple schema.org schemas:
 - there seems to be some type clashing. E.g., importing schema.org/Event doesn't properly work if Event already exists locally in another manifest.
 - fields from parent schema aren't being imported

Also (maybe less urgent): 
 - non-basic types are not supported

**Comment by sjmiles** [comment]
Couple other notes.

1. Current supported types I think are declared [here](https://github.com/PolymerLabs/arcs/blob/master/converters/jsonldToManifest.js#L11), where are as of this writing: `var supportedTypes = ["Text", "URL"];`

Just those two produce some reasonable types, .e.g. 
```
  {
    "name": "Place",
    "optional": {
      "faxNumber": "Text",
      "address": "Text",
      "maps": "URL",
      "branchCode": "Text",
      "isicV4": "Text",
      "hasMap": "URL",
      "telephone": "Text",
      "map": "URL",
      "globalLocationNumber": "Text",
      "logo": "URL"
    }
 ```
But there are other basic types (`Integer`, `Boolean`) we don't yet support (and `Date`, but that's not always basic).

2. Nested structures are also an issue (for schemas in general). For demos I've done some flattening of data streams so I can fit them into Entity structures.

**Comment by shaper** [comment]
Feels obsolete, can reopen/dust off if needed.
