### ISSUE TITLE
race in replaying recipes when follow-up steps depend on slots

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#458]
One of the problems blocking https://github.com/PolymerLabs/arcs-cdn/issues/16

Reproduce by following restaurant demo, i.e. on https://polymerlabs.github.io/arcs-cdn/dev/apps/web/ type 'restaurants', select suggestion and then accept e.g. the reservations suggestion. Reload:
 - Expected: You see a list with reservation times
 - Actual: Just the list, reservations only appear after hitting Ctrl-S (which reruns strategizer)

It seems that slots appear asynchronously, as a particles start up and render. We need to rerun the strategizer and look for replayable steps after new slots appear.

**Comment by seefeldb** [comment]
Insights so far:
 - https://github.com/PolymerLabs/arcs/blob/cdc4b56e652f956a8cec8ee0def6fd7846d1cdc8/runtime/dom-slot.js#L60 is where DomSlots calls SlotManager's updateInnerSlots which might be the clearest place to create a hook for changes
 - `await someArc.pec.idle;` is a related waiting pattern that might be useful as an alternative to callbacks or events.

**Comment by sjmiles** [comment]
See also https://github.com/PolymerLabs/arcs-cdn/issues/16#issuecomment-336550591
