### ISSUE TITLE
updating entities instead of setting them

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#480]
Right now we have to construct an update as 

```
newEntity = Object.assign({}, oldEntity.rawData, updatesToEntity)
```

i.e. construct a new entity based on what the particle sees of the old entity. This will break in many ways once a particle doesn't see a whole entity anymore, incl. associated ids, etc.

can we switch that to updating of fields? probably explicitly distinguish creating a new entity and updating an existing one.

**Comment by shaper** [comment]
Very stale, kicking to design work underway around storage and entity mutation. FYI @shans @seefeldb  to reopen or clarify if otherwise.
