### ISSUE TITLE
Rename inner-PEC and outer-PEC

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/arcs#488]
At the very least these should not have capital letters.

Or, we could use names like:
1. 'pec-worker' and 'pec-host', or
2. 'particle-execution-context' and 'particle-execution-host'

**Comment by shans** [comment]
why do you hate the PEC?

**Comment by smalls** [comment]
'particle-execution-*' seems friendlier to new developers than PEC does.

**Comment by shaper** [comment]
I assumed 'context' is `InnerPEC` and 'host' is `OuterPEC` but if somehow I've deviated from intent let me know. I found we actually already have a `ParticleExecutionContext` class which does nothing and is only extended by `OuterPEC`.
