### ISSUE TITLE
Coordinating front-end with `arc.instantiate`

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#534]
Possible alternate title: the shim for recreating an arc relies on identifying suggestions that match previously accepted steps fails due to a race condition.

Today `arc.instantiate` triggers asynchronous work, but there is no signal (e.g. Promise resolution) when it completes (for some definition of _completes_).

Specifically, today, persistent Arcs are recreated by playing back the user's Suggestion choices. This playback only works if the Planner returns suggestions that can be located using memoized data.  Therefore, we need to wait on `instantiate` until it's likely the context is in a known state (`slots` are manifested, in particular). 

Today the shell uses a timeout as a best guess.

**Comment by shans** [comment]
I think that as of a couple of recent changes you can:

await arc.instantiate; // all slots & handles constructed, all particles loaded
await arc.idle; // and now data has stopped changing - everything is in a quiescent state

**Comment by sjmiles** [comment]
Thank you

**Comment by sjmiles** [comment]
No long relevant.
