### ISSUE TITLE
Make dots use css animations.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#539]
Or otherwise reduce jank.

**Comment by dstockwell** [comment]
Where are the dots (code) ?

**Comment by shaper** [comment]
Under `arcs-cdn`, in `dev/app-shell/elements/arc-{app,footer}.html` and `dev/components/dancing-dots.html`.

**Comment by shaper** [comment]
I feel I should note there's also a test built atop them now, see `dev/test/specs/starter-test.js` thanks to @smalls 

So that if you do work here and break them you may now find out pre-haste rather than post-haste.
