### ISSUE TITLE
hosted version of Arcs is available at https://live.arcs.dev returns empty page :-(

### ISSUE THREAD

**Issue by ncouture** [PolymerLabs/arcs#6377]
Please let us see this early work, I've been following it since the beginning and some parts still elude me.

Thanks!

**Comment by sjmiles** [comment]
Can you tell us something about the system (OS) and browser you are using?

Also, when working, the latest iteration can look blank at startup, because it only displays a little bit of (mostly white!) UI at the bottom of the screen (one needs to mouse-over or tap to make it pop-up).

**Comment by ncouture** [comment]
It's been working across all my devices' browsers for some time now.

Can't wait to see where this and openid connect leads us. :-)
