### ISSUE TITLE
Mapping a named handle fails with undefined storage key.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#644]
While dusting off our social demo I found that this recipe bit no longer works:

`map 'FRIENDS_PROFILE_posts' #friends_posts as posts`

I "fixed it" by using a tag #friends_posts instead, see https://github.com/shaper/arcs-stories/commit/285c6f5a4b7f5252fbd0bb9a2907c0a1c665248b

I also "improved" the failure mode by adding an assert, see https://github.com/PolymerLabs/arcs/commit/54d39b6789889985effbee900fcb4f79f944f0d5

But, like:

- is specifying a named handle like this something that we intend to support go-forward, or was it just a low-fi hack thing? If we're not going to support it then perhaps we should remove support from the parser in the interest of a better developer facing experience.
- if we do intend to support it go-forward then we'll need to fix up whatever is involved w.r.t. storage keys, which will likely involve how we're synthesizing these handles in app shell land.
- there are other bigger questions around how do we ideally want to have recipes specify an input as being essentially a mailbox of all available relevant shared handles. What we're doing here is low-fi. It could be interesting to know thoughts here but that's probably outside scope of this specific issue.

This isn't a high priority but wanted to file for awareness and discussion. I think @sjmiles is amidst some profile and sharing app shell work right now.

FYI @piotrswigon @shans

**Comment by shaper** [comment]
Need to attempt repro to see whether this is still broken.

**Comment by piotrswigon** [comment]
I think we do want to allow mapping explicitly by an id.

An example use case I have in mind is having a recipe author map handles from the public arc they maintain by ID. This would allow their particles to have access to some up to date information, e.g. configs, rules, other pieces they may decouple from code.

I will take a look whether this works today.

**Comment by piotrswigon** [comment]
On a brief inspection this has to work as we use this in multiple demos. Restaurants, TVMaze, Music.
E.g.
`map 'PROFILE_all_piped-all_showcase_play_record' as fullPlayHistory`
`map 'SYSTEM_user' as user`
`map 'PROFILE_all_piped-all_tv_shows' as allPipedShows`
