### ISSUE TITLE
Implement "clear" method for collection handles

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#666]

**Comment by mmandlis** [comment]
Note: implement in both - in-memory and firebase storage.

**Comment by shaper** [comment]
Did we add this, I forget? I feel like maybe we did. Or at least discussed sometime recently. Marking P2 since it seems we do want it at some point.

**Comment by mmandlis** [comment]
I believe this was done: https://github.com/PolymerLabs/arcs/pull/2029
