### ISSUE TITLE
Referencing an undeclared Handle in a Manifest triggers assert-exception-debugger

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#684]
E.g.

```
recipe
  FooParticle
     foo = someHandle
```

Produces `Error: could not find someHandle`

If I understand #661 correctly, this specific condition should handled more gracefully because it's a common error.

**Comment by sjmiles** [comment]
Bad particle name in a recipe will also cause this debugger-assert. Aka, "could not find particle XXXX".

**Comment by mmandlis** [comment]
https://github.com/PolymerLabs/arcs/pull/682 should be already addressing this.
