### ISSUE TITLE
hinting a provide-slot in a recipe requires hinting the consume-slot, which is recursively bad

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#685]
TVShow recipe uses two lists, one for Shows and one for Episodes. These use generic list-renderers which output slots called `item`. 

The declaration for Epsiodes looks like this:

```
particle TVEpisodeList in 'https://$cdn/artifacts/Common/source/List.js'
  TVEpisodeList(in [TVEpisode] items)
  consume episodes
    provide set of item
```

It has to provide `item` because that's the slotid that `List.js` renders. 

To disambiguate the two kind of item slots, I tried to employ the slot hinting like so:

```
  TVEpisodeList
    items = episodes
    consume episodes
      provide item as episodeSlot
  EpisodeMultiplexer
    list = episodes
    hostedParticle = TVEpisodeItem
    consume item as episodeSlot
```

But now the system complains that `episodes` slot cannot be resolved (`unresolved slot: missing source-connection; missing id`). Note that the `consume episodes` line is unchanged relative to the manifest, so I don't expect this problem.

This can be fixed by more hinting, e.g. `consume episodes as espisodesSlot`, but now I have to add hinting to the provider of `epsiodes`, which means I must alias that particles `consume` entry, and so on, until many particle slots are redeclared and (often trivially) hinted in the recipe.

More info: if I implement `consume item as episodeSlot` as above (which the requisite recursive aliasing), it doesn't fully disambiguate and will match both the `item` slot and the `item as episodeSlot`. Resolving this ambiguity requires aliasing the original `item` slot also (in combination with the first effect, this results in needing to alias every single entry).

**Comment by shaper** [comment]
@mmandlis did some work above, to update with current status. Making a guess at priority.

**Comment by mmandlis** [comment]
there is more that we can improve in the area, but this particular issue was fixed.
