### ISSUE TITLE
Example of bespoke manifest for generalized source

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#693]
```
particle TVShowList in 'https://$cdn/artifacts/Common/source/TileList.js'
  TVShowList(inout [TVShow] items, inout TVShow selected)
  consume master
    provide set of item
    provide set of action
  description `see ${items}`
```
For each use of `TileList.js` (or `List.js`) I generally inline something like the above. Most of the lines are boilerplate, except for line 2 where we define the types for `items` and `selected`. 

I was under the impression that defining those types is necessary today to get the recipe to resolve. Any advice welcome!

**Comment by mmandlis** [comment]
It is still necessary today, but should no longer be necessary next week.

**Comment by shans** [comment]
@mmandlis this isn't a Transformation, shouldn't ~a already work?

**Comment by mmandlis** [comment]
I believe that generic particle specs with type variables are already used in TV Shows recipes, so closing this.
