### ISSUE TITLE
suggestions (and other state) aren't consistent through a reload

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#697]
The suggestions list changes through reloading a page. Berni suggested this as a test, but when I added the automation I found that the list changes.

For instance, when reloading after the 'Find restaurants' suggestion has been accepted (so part way into one of our demo flows):

Initial list:

- 	Edit address, select selenium's avatar, select selenium's favorite foods, and select friends.
-	Make a reservation.
-	Show Claire's wishlist (Book: How to Draw plus 2 other items).
-	Show products from your browsing context (Minecraft Book plus 2 other items) and choose from Products recommended based on products from your browsing context and Claire's wishlist (Book: How to Draw plus 2 other items) (Book: How to Draw plus 2 other items).
-	Show products from your browsing context (Minecraft Book plus 2 other items) and choose from Products recommended based on products from your browsing context and Claire's wishlist (Book: How to Draw plus 2 other items) (Book: How to Draw plus 2 other items).

After reload:

-	Edit address, select selenium's avatar, select selenium's favorite foods, and select friends.
-	Find restaurants near selenium's location.
-	Show Claire's wishlist (Book: How to Draw plus 2 other items).
-	Show products from your browsing context (Minecraft Book plus 2 other items) and choose from Products recommended based on products from your browsing context and Claire's wishlist (Book: How to Draw plus 2 other items) (Book: How to Draw plus 2 other items).

I have a branch with my WIP test: https://github.com/smalls/arcs-cdn/tree/test-that-the-suggestions-list-is-same-after-a-reload

**Comment by sjmiles** [comment]
Fwiw, the context is going to different on reload, we should probably take a look at that.

For example, the front-end reloads only the subset of handles that are specifically persisted in Firebase. I'm curious what the delta is between that set and the set of handles available before the reload.

**Comment by shaper** [comment]
Stale, we can reopen with updated proposal/description if needed.
