### ISSUE TITLE
Fix `npm test` to work on Windows.

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#711]
@sjmiles noted while doing dev on Windows, we can test on my Windows workstation together soon:

- Probably need to prefix the tools ... commands with node since the #! atop the tools scripts isn't sufficient for Windows.
- Subsequently he sees an error that looks like Windows specific file path reference issue: Error: no test file found at path */test/index.test.html.

@shaper filed this in https://github.com/PolymerLabs/arcs-cdn/issues/180

**Comment by smalls** [comment]
I think this should be fixed as of #749.

**Comment by shaper** [comment]
Top level `npm test` looks ok now. Lint command line reports too long on Windows, we may need to chunk this out: https://github.com/PolymerLabs/arcs/blob/master/tools/sigh.js#L144
