### ISSUE TITLE
Fix geolocation to only request info in response to a user gesture.

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#712]
As noted by @sjmiles Chrome currently reports, on load of app shell:

```[Violation] Only request geolocation information in response to a user gesture.```

Filed by @shaper in https://github.com/PolymerLabs/arcs-cdn/issues/163

**Comment by piotrswigon** [comment]
Honestly, I doubt it will be anywhere near top of my priority list anytime soon. FYI @sjmiles.

**Comment by sjmiles** [comment]
This is old, the geolocation stuff has changed, and console doesn't complain about it anymore.
