### ISSUE TITLE
unit tests for persistent-arc.html, dancing-dots.html, and good-map.html

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#713]
More information in the original https://github.com/PolymerLabs/arcs-cdn/issues/142.

**Comment by smalls** [comment]
More context from the original issue:

> unit tests for persistent-arc.html, dancing-dots.html, and good-map.html are disabled as they need to import the involved code which now lives in ES modules. Fixing may require emulating what arcs does via sigh test to generate and run mocha tests in a manner as touched upon in mochajs/mocha#3006

This appears to be what remains. See also TODOs in shell/test/index.test.html.

CC @shaper (original filer of PolymerLabs/arcs-cdn#142).

**Comment by shaper** [comment]
Stale.
