### ISSUE TITLE
Remember external recipes when used and surface in launcher somehow.

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#715]
@shaper writes

If a user uses a third party recipe via `solo` or `manifest` we might want to remember that and surface it in some most-frequently/recently-used list manner in the launcher.

Having a more robust registry/strategizer/etc. seems the long term approach but for now maybe we'd beneift from something more low-fidelity.

This could be crazy, so filing for discussion. @seefeldb @smalls @mmandlis 

Originally filed as https://github.com/PolymerLabs/arcs-cdn/issues/97.

**Comment by shaper** [comment]
I did work to remember the solo/manifest query param for developer arcs. We're redoing the launcher now. I think we can close this and react to actual developer feedback.
