### ISSUE TITLE
Pass suggestions-element to the slot composer

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#717]
@mmandlis writes

to properly create suggestions (similar to the change:
PolymerLabs/arcs@95a1c94#diff-bb5f1da3491bde37be05eb33223c488e)

Originally filed as https://github.com/PolymerLabs/arcs-cdn/issues/80.

**Comment by mmandlis** [comment]
This was earlier fixed by https://github.com/PolymerLabs/arcs-cdn/pull/127
