### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#722]
@seefeldb writes on https://github.com/PolymerLabs/arcs-cdn/issues/14:

Settings page with

- profile arcs
- recipes that other users used to create profile arcs

Linked from homepage

**Comment by sjmiles** [comment]
Is this still a thing, or is this an old concept? If it's still a thing, can we link to a Yuin mock as a touchstone?

**Comment by smalls** [comment]
It's definitely an old bug (I was moving bugs over from PolymerLabs/arcs-cdn). @seefeldb is there still value here, or are we going a different direction with Yuin (in which case I'll close this out?)

**Comment by shaper** [comment]
Closing in absence of commentary solicited above.
