### ISSUE TITLE
Arcs Launcher

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#723]
@seefeldb writes in https://github.com/PolymerLabs/arcs-cdn/issues/13:

Homepage with

- starred recipes as quick launch space (starred recipes TBD)
- filter checkboxes for "shared" and "profile"
- recent arcs

**Comment by sjmiles** [comment]
Is this not the old description for what is now "Launcher"? If so, I believe it's superseded by Yuin's design work.

**Comment by seefeldb** [comment]
Yes, that's superseded by yuin's latest mocks. I like "launcher" better, let's keep it.

**Comment by shaper** [comment]
This exists (though we don't have starred recipes). Closing and we can reopen more granular for other work.
