### ISSUE TITLE
Create arc description and render/edit in title

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#724]
@seefeldb writes on https://github.com/PolymerLabs/arcs-cdn/issues/12:

Create arc description and render in title.
Click on title makes it editable.

Then:

PolymerLabs/arcs-cdn@13db1da as first step

remaing:

- recalculate description from arc, instead of polling database. find some reasonable interval to update (as it captures the data).
- make title editable

**Comment by shaper** [comment]
Stale
