### ISSUE TITLE
gulp should only run if there are changes to the source files

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#729]
In the common case where the source files haven't changed, we shouldn't redo gulp build steps that won't make any changes. Now that (by default) `shell> npm test` runs gulp, this is going to get bothersome pretty quickly.

**Comment by smalls** [comment]
As a note, right now I'm relying on gulp to add a delay into the build so we don't attempt to run tests before the server's started. There are some other things that add delays (running the unit tests) but it might be better to add a real delay. It would be even better if we could wait until there's a listener on the socket.

**Comment by shaper** [comment]
gulp has been gone for a while.
