### ISSUE TITLE
Replace bower with yarn and fix shell strategy explorer bower module 404s.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#736]
Two points:

1. `bower` seems deprecated. Our install/build process outputs log messages recommending move to `yarn`.
2. The shell Selenium tests (and running locally with a clean build, even after installing things per `./tools/install`) report JS errors and 404 attempting to load some `bower` modules for the copy of the strategy explorer in `shell`.

I figure we should just swap `yarn` in for `bower`. On the second point, maybe we should stop copying in the strategy explorer, or we could disable it when running in test mode somehow, or we could fix the build to actually install the required modules whether via `yarn` or `bower`.

FYI @sjmiles @smalls

**Comment by seefeldb** [comment]
https://github.com/PolymerLabs/arcs/pull/687 should address the second, at least in the context of running the tests.

**Comment by shaper** [comment]
OK, yeah, and in addition to that change we should delete the copy in `shell/strategy-explorer` and un-wire the hotkey that toggles its visibility.

**Comment by shaper** [comment]
The bower deprecation message for posterity:

```
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

**Comment by shaper** [comment]
I looked at moving to yarn but it appears to me it's premature as the node Polymer libraries seem stale. For example https://www.npmjs.com/package/@polymer/iron-overlay-behavior was last updated two years ago and shows version 0.0.3 (though not clear if that's the right version to look at) whereas our devtools currently is using something like version 2.x.x.

I worked through using `bower-away` as noted in https://github.com/sheerun/bower-away but I had to fix up missing version numbers manually, and I don't think the resulting set of code is workable.

So I'd say stick with `bower` for foreseeable future and ignore the migration warning. Polymer 3.0 is supposed to include moving to `npm` so if we're still using Polymer at that point we can maybe shift then.

**Comment by piotrswigon** [comment]
I will definitely remove shell/strategy-explorer once it's available in DevTools, which will be very soon (I think).

Thanks for looking into updating as away from bower, I didn't even know it's deprecated-ish...

**Comment by shaper** [comment]
Explorer was moved in https://github.com/PolymerLabs/arcs/pull/687 and https://github.com/PolymerLabs/arcs/pull/764
