### ISSUE TITLE
In arcs-live, "play words" is trying to load a file that it can't find.

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#741]
URL: https://polymerlabs.github.io/arcs-live/apps/web/?arc=-L4wlGsEvYmYpJQKk2lQ&user=-L-8nAaYPWyEePqvWwgq

missing file: https://polymerlabs.github.io/arcs-live/artifacts/Common/source/DetailSlider.js

**Comment by shaper** [comment]
Pretty sure this was fixed, transient repo fire. Please reopen if not.
