### ISSUE TITLE
Explore shifting usage of runtime browser demo to app shell.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#773]
To allow deleting runtime browser demo, which is a very old version of app shell.

Need to explore speed to load, default UI, and any runtime testing interactions and make sure those are suitable in modern app shell before we can delete.

@sjmiles

**Comment by shaper** [comment]
The runtime browser is used for automated testing here:

https://github.com/PolymerLabs/arcs/blob/master/runtime/test/demo-flow-test.js

As part of that `sigh.js` builds the browser demo bits in the `webpack` target.

**Comment by dstockwell** [comment]
> The runtime browser is used for automated testing here:
> 
> https://github.com/PolymerLabs/arcs/blob/master/runtime/test/demo-flow-test.js
> 
> As part of that sigh.js builds the browser demo bits in the webpack target.

Not quite, the only parts of browser/demo that is used in the test is the manifest and its dependencies. webpack isn't a dependency for any runtime test.

**Comment by shaper** [comment]
Sweet, maybe it will be easier than I thought. I'm hoping we can just find a way to route the recipes into `shell`, and maybe have a way for it to start with suggestions pre-opened.

**Comment by shaper** [comment]
@sjmiles notes we can route the recipes today via `solo=` or `manifest=` query params. So AFAIK we could delete `runtime/browser` right now, and just keep the recipe bits, and have folks shift to using and bookmarking for convenience a url like `http://localhost:5001/arcs/shell/apps/web/index.debug.html?arc=*&user=<their preferred user id>&solo=http://localhost:5001/arcs/runtime/browser/demo/recipes.manifest` and any feature requests from there around performance or auto-open suggestions or whatever we can address separately.

And we can delete the webpack in sigh.

Thoughts?
