### ISSUE TITLE
Add "repeat" option to "sigh test".

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#779]
Have to emulate currently, with unnecessary overhead for each run and no built-in summary of pass/fail, via something like:

'for i in \`seq 10\`; do ./tools/sigh test --grep='demo'; done'

@mmandlis @dstockwell

**Comment by lindner** [comment]
Potential steps: 

- Add a new command line option to `sigh.js`
- Find the magic [mocha](https://mochajs.org/api/mocha) repeat or numtimes api.

**Comment by shaper** [comment]
@mykmartin I recall you'd found a way to use the mocha repeat through double-double-hyphens or something but I can't find it now.

**Comment by mykmartin** [comment]
@shaper Not that I can recall... webdriver has the `mochaOpts` flag, so you can do this sort of thing: `npm run test-wdio -- --mochaOpts.grep 'gl.*'`

But that's not applicable to the standard command-line tests run by sigh.

**Comment by thebrianchen** [comment]
Is the ultimate goal to optionally retry tests 'n' times until it passes, or to run tests repeatedly to determine flakiness?

**Comment by shaper** [comment]
My intent was the latter: "run tests repeatedly to determine flakiness/test latency". We do need a summary of output, I see that's been mentioned on the PR. Since otherwise we can basically effect with the shell command at the start of this issue.

**Comment by lindner** [comment]
I think we can mark this done.  You can run a large number of tests to determine flakiness and you get a summary of output.  Thanks so much @thebrianchen
