### ISSUE TITLE
Recover stack traces lost on PEC boundary.

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#809]
We could stash the stack trace in the outerPEC and recover it on problems in the worker. Our DevTools extension could potentially have some UI for that.

**Comment by shaper** [comment]
Didn't we do this, or at least part of the work? @piotrswigon

**Comment by piotrswigon** [comment]
I've just sent a PR for source-mapping stack traces sent in the RaiseSystemException (#2337), with that I think we have all we could need for this bug. I will therefore close it.
