### ISSUE TITLE
Move all debugging utilities from AppShell to DevTools

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#812]
Some things I'm aware of:
- Illuminate tool.
- Handle Explorer.
- Manifest list editor.

There are probably a few more.

**Comment by shaper** [comment]
Some of these are done, but not all, I believe. Usefulness of the preceding comment: limited.

**Comment by piotrswigon** [comment]
The only thing that is not available in the DevTools extension that is in the AppShell is the Xen Explorer. I don't plan to port it, as it is aim to help debugging the shell code - as I understand it. @sjmiles opinions?

There obviously may be issues with DevTools, e.g. Illuminate tool no longer works since we moved to shadow-dom per-particle, but those are just bugs.

I am closing this. Thanks Walter for triage.
