### ISSUE TITLE
Xen: Can't update contents of a textarea on re-render.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#850]
While working on social miniblog post editing, I find that with:

`<textarea on-change="_onCaptureText">{{name}}</textarea>`

When user completes typing and we save the text, we'd like to clear it. We see `_render` called and we return the empty string for `name`, but the textarea content keeps the value previously entered by the user.

A workaround is to use an `input` element, but we'd like to be able to use `textarea`, we think.

FYI @sjmiles

**Comment by sjmiles** [comment]
If the object returned from `_render` has a `name` field, that should always replace `{{name}}`. I'll need to look at a repro to see what is going wrong.

**Comment by shaper** [comment]
It is repro'ing 100% for me with the `EditPost` we worked on yesterday. You can try it by enabling the `https://shaper.github.io/arcs-stories/social/Social/Social.recipes` recipe in the persistent manifests and choosing the 'Write posts...' recipe from the suggestions.

`EditPost` does return `name` from `_render`. I added logging to the particle and didn't see anything obvious. I didn't look at Xen code proper yet.

**Comment by shaper** [comment]
We found we'd set `{{name}}` as text within the `textarea` tags when we should have set it with the `value` attribute. I'm not sure there's any work to be done here since we were essentially misusing things.
