### ISSUE TITLE
Some manifest errors produce generic failure: "could not normalize a context recipe"

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#851]
If possible, it would be great to have additional information about what went wrong or which manifest was problematic.

I can provide a repro case once I have the necessary PRs checked in.

**Comment by sjmiles** [comment]
I showed Maria my repro and she fixed it, so I don't have it anymore ... doh.

**Comment by mmandlis** [comment]
But I do have the repro now :) 
and i'm working on improving the error messaging.
