### ISSUE TITLE
Add development facility to disable planner timeout.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#864]
To facilitate debugging runtime planner logic. See timeout value passed around in `ArcHost._plan` and `ArcsUtil.makePlans`. In the end the timeout in question is in runtime `Planner.plan`.

There was also discussion about shifting runtime use of `NaN` to `0` for no-timeout in this case.

**Comment by shaper** [comment]
@shans @mmandlis how would you like this to be enacted? @sjmiles requested your input.

**Comment by shans** [comment]
query parameter sounds good! I'd almost prefer -1 to 0 - at least NaN is clear in that it's disabling a timer. Infinity? :)
