### ISSUE TITLE
Move app shell top action buttons to RHS triple-dot menu.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#879]
See restaurant demo mocks slides 20 - 28: https://goo.gl/ENoMZV

@sjmiles, @yuinchien was asking about this today since without it the miniblog title will be squished on mobile. Note we don't have an Arc title editor right now, but we don't need to block this work on that, and am planning to work on the title editor soon in any case.

@sjmiles I am happy to help do this work but want to make sure we don't conflict and also get any design plans you may have had. We could also just do it together next time we meet up.

**Comment by sjmiles** [comment]
Triple-dot is easy, the requisite pop-up menu that goes along with it, not so much.

I have some WIP branches towards having pop-up support, but it will take some time to integrate.

**Comment by shaper** [comment]
I think https://github.com/PolymerLabs/arcs/pull/955 includes at least part of this.

**Comment by shaper** [comment]
This is either done or obsolete IMO, depending on your perspective, with the new app shell landed.
