### ISSUE TITLE
One broken manifest should not take down the world of manifest parsing.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#889]
A couple of days ago I broke `Words.recipes` by renaming `Post.manifest`, which it imports, to `Post.schema`. With a broken import, I found that @yuinchien was in a state where her launcher provided no suggestions and had an exception about `Post.manifest` that didn't cite which parsed manifest was involved. I assumed it was `Social.recipes`, but eventually realized it was `Words.recipes` through sheer contemplation.

@sjmiles mentioned similarly the other day in discussion with @shans 

There are two issues here:
- manifest parsing is fragile and one broken manifest takes down the world
- a manifest parse failure would ideally include more information such as what happened, which manifest file (full url and filename) was being parsed, and the line number in the file at which the error occurred.

In chat discussion it sounded like improving this may be non-trivial, which is entirely believable. Perhaps improving the error info would be easier and worth doing first.

**Comment by dstockwell** [comment]
We have the MVP specified here, can file another issue if we want to take this further later.
