### ISSUE TITLE
Improve feedback for errors and debugging

### ISSUE THREAD

**Issue by mykmartin** [PolymerLabs/arcs#911]
While trying to set up a new particle, I would often end up with a blank page, with no errors or warnings in the console. There would usually be a log entry "ArcSteps - rejecting step" with no further details. It would be useful to provide more details on why a given recipe or particle has failed to appear.

**Comment by shaper** [comment]
Current common wisdom is to use the Strategy Explorer in the extension and track the involved recipes/particles through there. We could start trivially by just enhancing the log message around 'rejecting step' to suggest developers do that, and add more info on what exactly was rejected.

**Comment by piotrswigon** [comment]
I would like to believe that things have improved in last 10 months - but I guess the way to know for sure is to ask new hires to write some particles and recipes and see what they hit.

As there is no concrete feature or bug here I will close this issue.
