### ISSUE TITLE
DomParticle subclasses should avoid overriding `setViews` without calling super impl

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#928]
Otherwise those sub-classes have a requirement to ensure compatible override implementations in perpetuity, and they tend to contain duplicate code and/or use private methods.

**Comment by mmandlis** [comment]
As agreed yesterday, in a followup PR i'll move the multiplexing functionality outside ShowCollection particle.

**Comment by sjmiles** [comment]
Believe this is fixed.
