### ISSUE TITLE
Whitelist some set of elements to be used via VDOM, incl. paper-*

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#93]
incl. determining the subset of events we want to support.

requires research on whether just a subset of what gets sent in an event is enough or whether more work is needed (e.g. is the value of interest in an input field already a parameter to the event handler, so we can just subset the parameters to sanitize?)

**Comment by sjmiles** [comment]
Fwiw, shell isolates a list of these here:
https://github.com/PolymerLabs/arcs/blob/master/shell_0_6_0/configuration/whitelisted.js

Today event data is restricted to round-tripped private data the particle has installed on a node (the `key`) and a single `value` property provided by the target element.

Ensuring proper `value` property is a requirement for being a privileged (whitelisted) component.

**Comment by sjmiles** [comment]
Can we define what constitutes completion on this issue?

**Comment by sjmiles** [comment]
Sheriff says this ticket is elderly and should be in bed, not the saloon.
