### ISSUE TITLE
Refactor slot strategy to resolve when there's only 1 choice / do the combinatorial thing when there are multiple choices.

### ISSUE THREAD

**Issue by shans** [PolymerLabs/arcs#961]

**Comment by mmandlis** [comment]
FYI the original strategies did the combinatorial thing, and it resulted in identically appearing suggestions, that only differ in slot connections.
Maybe instead of doing the combinatorial thing, we need to have better slot-view restrictions?

**Comment by shans** [comment]
Ultimately both are probably required. I'll split this up into (1) refactor into 1-choice resolve / n-choice resolve and (2) investigate combinatorial results and get back to you.

**Comment by cromwellian** [comment]
@mmandlis Is there ongoing work on this?

**Comment by mmandlis** [comment]
there is no ongoing work, and MapSlots does return combinatorial results now, so I'll close this.
