### ISSUE TITLE
QA Steps for App Shell: Smoke Tests to Automation

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#975]
Issue to track notes about things that need manual testing in App Shell, with two uses: 

1. creating a QA worksheet for smoke testing by humans
2. adding coverage to the  automated tests

**Comment by sjmiles** [comment]
User Selection
User Selection Persistence
New User Flow

**Comment by sjmiles** [comment]
Recording/Playback of Arc Steps

**Comment by sjmiles** [comment]
Loss of cohesion between index.html and index.debug.html

**Comment by sjmiles** [comment]
Compatibility with iOS

**Comment by shaper** [comment]
More from https://github.com/PolymerLabs/arcs/issues/1002, we can update as we find more but wanted to note:

- [ ] Deleting an Arc
- [ ] Arc title updated to reflect plans
- [ ] Possibly sharing/boxing?

**Comment by sjmiles** [comment]
Persistence of Sharing State
Add/Remove Arcs from Launcher 
Arc Descriptions displayed/generated

**Comment by sjmiles** [comment]
Behavior when there is no selected user

**Comment by sjmiles** [comment]
We still need better QA procedures, but this ticket is now stale. Closing.
