### ISSUE TITLE
Cannot specify subid directly

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/arcs#984]
I had a template along the lines of `<div slotid="a" subid="b"></div>` but `subid` was coming out as `undefined`. 

In [dom-context](https://github.com/PolymerLabs/arcs/blob/9488d37577c79f16f9c0288318b3a4987aa70e49/runtime/dom-context.js#L99):

```js
      let slotId = s.getAttribute('slotid');
      let providedSlotSpec = slotSpec.getProvidedSlotSpec(slotId);
      if (providedSlotSpec) { // Skip non-declared slots
        let subId = s.subid;
```

I tried changing that to `s.getAttribute('subid')` which worked for me, but broke particles that set `subid={{something}}`

**Comment by sjmiles** [comment]
Interesting, what's the use case where you know a static subid? 

You can make it binding `subid={{subid}}` and put `subid: 'b'` in your render model, or we can change dom-context to use `subId = s.subId || s.getAttribute('subid');`.

**Comment by dstockwell** [comment]
> Interesting, what's the use case where you know a static subid?

For the hex boardgame, I have a grid of x*y slots where the sub id is of the form 'x-y'.
