### ISSUE TITLE
convert constraints strategy with 2 constraints resolves incorrectly

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#992]
```
schema S
particle A
  A(in S b)
particle C
  C(in S d)
particle E
  E(out S f)

// THESE RECIPES RESOLVE OK
recipe
  A.b -> E.f
  E.f -> C.d

recipe
  A.b -> E.f
  A.b -> C.d

// THESE FAILS TO RESOLVE
recipe
  A.b -> E.f
  C.d -> E.f

recipe
  A.b -> E.f
  C.d -> A.b
```

**Comment by shans** [comment]
Feel free to assign this to me too

**Comment by mmandlis** [comment]
I'll debug it now, but i don't fix it till the end of the day, i'll assign to you.
I'm also seeing weird behavior (I mentioned it yesterday in the chat), if some of the 3 particles have type variable connections - I'll push a PR with a repro (or a fix?) by eod.

**Comment by mmandlis** [comment]
the primary problem is solved. i'll send an update to the pr shortly.

**Comment by mmandlis** [comment]
The remaining problem with type variables is due to recipe._isValid() converting [Product] back to [~a] when called from resolve-recipe strategy (working on a fix).

**Comment by mmandlis** [comment]
I will open a separate issue with a detailed description for the type variable problem. it is not related to convert constraints (well kinda))
