### ISSUE TITLE
Type variable resolution with multiple handle connection

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#993]
original recipe is:
```
recipe
  ShowCollection.collection -> ProductFilter.results
  Multiplexer.list -> ShowCollection.collection
  map 'mylist' as mylist
  create as books
  ShowCollection
    consume master
      provide item as itemSlot
  Multiplexer
    hostedParticle = ShowProduct
    consume annotation as itemSlot
  ProductFilter
    products <- mylist
    hostedParticle = ProductIsBook
    results -> books
```

The `create` handle is created during init-population and its type is set to [Product].
Then resolve-recipe and convert-constraints strategies run in either order.
When adding a descendant, handle._isValid is called for the `books` handle, and:
`
let {type, valid} = TypeChecker.processTypeList(typeSet);
`
typeSet contains the 3 connections of the handles - the `out` connection has `[Product]` type, the two `in` connections have `[~a]` type. 
Depending on the order the connections appear in, `TypeChecker` returns `type` that is a set of resolved type variables, or just set of entities.

It results in 2 recipes that are considered different, because the handle's type is serialized as `// [~a]` or `// [Product]`.

**Comment by mmandlis** [comment]
as an initial solution, i just update the serialization of the handle to always use the resolved type (eg `// [Product]`
but i think a more fundamental fix is needed, so that order doesn't affect the type.

**Comment by shans** [comment]
Order isn't affecting type, and your solution is correct. The resolved type of a type variable *is* its type. We've had to apply the same fix in a few other places already.

**Comment by dstockwell** [comment]
For the case where it is fully resolved we may be able to return the resolved type from processTypeList. I'm also not sure that the serialized type needs to be part of the dedupe check anymore.

Happy to take this as I'm still doing some work in the area.

**Comment by mmandlis** [comment]
I already have a fix - just cleaning up and sending out shortly.
It would be great to ignore the serialized type in dedup check (maybe we can add to |options| parameter of the toString() whether to include the serialized type?)

But the order does affect whether the handle's type is set of entity or set of type-var. Even if the type-var is resolved to the entity type, it's not literally the same.. Let's talk more on Monday?
